### ISSUE TITLE
Spread PR review/approve workload around

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#10]
The number of contributors/contributions is growing quite rapidly.

We need to spread the review/approve workload around or we won't be able to continue to scale.

Kubernetes has a lot of processes and associated tooling for assigning reviewers and approvers. I think Kubernetes uses owners files. 

Also prow provides a PR dashboard that I think helps Kubernetes contributors see PRs that need their attention.

The purpose of this PR is to figure out what we should do and track the work to implement.

If anyone is familiar with what Kubernetes does, can you chime in and explain or provide a reference?

**Comment by ddysher** [comment]
We are using prow and kubernetes owners file internally for our dev workflow. Kubernetes is a large community while we are a small group of developers, so we've simplified things a little bit.

#### deploy kubernetes prow job

we start by deploying prow job into a kubernetes cluster. i'm not responsible to deploy prow, but IIUC, there are two features that are important to us

- to allow the bot to handle reviewer assignment, adding/removing label, close issue, etc
- setup ci for the bot to merge PRs (using an older system [mungegithub](https://github.com/kubernetes/test-infra/tree/master/mungegithub))

The first item is important in that we can remove write access to all repositories from all developers; same for the second item, plus we are now able to use owners file.

Other features like submit-queue, dashboard, etc are nice-to-have features, but not very important for ur workflow.  We are yet to discover other features from prow at this moment.

I believe kubeflow already use prow now, but i don't know how far are we now.

#### define approver and reviewer

now that bot is able to handle PR merge, we begin to define approver and reviewer. note at this moment, everyone in the org (except owners) should only have read access to all repositories.

Approver has the highest privilege, and is responsible to make sure that code change is consistent with other part of the code. Reviewer, on the other hand, cares more about the changes in a single PR.  LGTM from reviewers will not trigger PR merge from bot, only LGTM from approvers will trigger PR merge.

owners, as defined in Github owner, has admin privilege to all repositories, he should respect the rules above, i.e. do not force merge PRs

For a larger project, the owners file should be per directory; that is, every sub-directory should have an owners file.

an example repository from us https://github.com/caicloud/nirvana/pulls?q=is%3Apr+is%3Aclosed

![image](https://user-images.githubusercontent.com/2191361/36292855-b702cdee-130f-11e8-9a79-48a2f90138ee.png)

**Comment by ddysher** [comment]
SGTM.  A trial run is non-intrusive as long as we don't remove any existing permissions.

**Comment by erikerlandson** [comment]
SGTM. Would it be a good idea to somehow mirror the contents of these OWNER files on the `community` repo?  Possibly just a table of links to those files would suffice.

**Comment by jlewi** [comment]
@erikerlandson Why do we need to mirror OWNERS files? My understanding is that every repo should have an OWNERS file at the root and then this can be overwritten/extended by placing OWNERS files in other parts of the repository source tree.

So my expectation is that once we socialize the convention and document it in the community repository, everyone would know exactly where to look to find the OWNERS file containing lists of approvers/reviewers.

**Comment by erikerlandson** [comment]
@jlewi that is the question; are OWNERS files self documenting? I haven't used them. The argument for "mirroring" would be maximizing discoverability, but documenting "look for the OWNER file with most specific scope" might be fine.

**Comment by ddysher** [comment]
@erikerlandson prow will suggest appropriate assignee, point folks (pr author, etc) to correct documentation and interact with them in some cases.  Let's see if it works for us.

@jlewi what do you suggest for next step?  if we start from tf-operator, we need to setup prow job as mentioned above, and draft OWNERS files.

note it seems we use `k8s-ci-bot`, but we'd better use our own account?

**Comment by jlewi** [comment]
@ddysher I think setting up tf-operator to use OWNERS and K8s  tooling seems like a good next step. If you think we should setup our own bot; I'm fine with that. Not sure what that actually entails.

**Comment by jlewi** [comment]
So I think the next steps are

1. Ensure k8s-ci-bot has appropriate permissions on the repo (is write sufficient) or is admin needed?
2. Ensure appropriate prow plugins are enabled for Kubeflow
https://prow.k8s.io/command-help

**Comment by foxish** [comment]
On K8s, we started with contrib first as testing ground. https://github.com/coreos/findowner was helpful in finding recent contributors and getting a set of reviewers and approvers for each level in the tree. I think k8s-ci-bot just needs write for reading owner files.

**Comment by jlewi** [comment]
I found these great directions for the Kubernetes PR process.
https://github.com/kubernetes/community/blob/master/contributors/guide/owners.md#code-review-using-owners-files

The plugins were enabled so we can now do /approve, /assign, /lgtm etc..

blunderbuss is not enabled so we don't auto-suggest reviewers; that could be very useful for spreading the workload around.

Auto merging of code doesn't seem to be enabled yet and I'm not sure what that entails.

**Comment by jlewi** [comment]
Here are some docs about automatic merge:
https://github.com/kubernetes/community/blob/master/contributors/guide/pull-requests.md#the-testing-and-merge-workflow

We probably don't need that right now.

**Comment by jlewi** [comment]
We have opened up issues for follow on work. 
So I'm closing this one.
