### ISSUE TITLE
[Devstats] Figure out how to expose the dashboards publicly

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#106]
In #34 we set up cncf/devstats.  We should expose them publicly so that everyone can see them.

I think to do that we need to

1. enable anonymous access
1. Change the admin account so we don't use username and password and check in the password into source control
    It supports OAuth so that might be one solution; although that might entail also setting up https.

**Comment by gaocegege** [comment]
Could we just create a nodeport service for the Grafana?

**Comment by jlewi** [comment]
I don't think the problem is setting up ingress to make the service accessible from outside the cluster. I think the problem is how to do that while only giving read only permissions to users. Right now I think if we expose it publicly anyone who knew the admin account and password would be able to login as admin and change things.

Right now we are still using the default admin account and password and checking it into source control as part of our ksonnet app. We could change that and make it a secret. 

But Grafana supports OAuth login and can use GitHub or Google. So I lean towards turning on OAuth using GitHub and getting rid of basic auth. 

At which point I think we can make Grafana available for anonymous access.

@lukaszgryglicki what do you do for k8s.devstats.cncf.io?

**Comment by lukaszgryglicki** [comment]
All our projects allow anonymous access (read-only).
There is an admin user that I can use, but it's not available outside.

**Comment by jlewi** [comment]
@lukaszgryglicki How do you prevent the admin user from being accessible outside?

**Comment by lukaszgryglicki** [comment]
Every script in deploy/* requires passing at least two env variables:
Postgres password: PG_PASS=...
Influx pass: IDB_PASS=...
There are more *_PASS variables used in some cases, for example for `ro_user` or `devstats_team`.

**Comment by lukaszgryglicki** [comment]
In our case admin user is password protected and we *want* anonymous read only access - so everybody can see dahsboards, even edit them, but cannot save.
