### ISSUE TITLE
Create repository kubebench for benchmarking

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#115]
See kubeflow/kubeflow#708

Creating an issue here since we use community for new repositories.

**Comment by jlewi** [comment]
I created the repository.

I gave the ci-bots and cisco team write access.

**Comment by jlewi** [comment]
Lets use this issue to continue tracking setting up the repository.

[instructions](https://github.com/kubeflow/community/blob/master/repository-setup.md)

/assign ddutta

**Comment by ddutta** [comment]
Thx @jlewi
