### ISSUE TITLE
Define common issue labels for all repositories

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#12]
See kubeflow/tf-operator#326 for an initial discussion of common labels for issues.

I think most of the labels are uncontroversial e.g. labels for different priorities and furthermore should be applied consistently across all repositories.

Opening this issue to track defining those labels across all our current repositories.

Is there any easy way to enforce a common set of labels across multiple repositories?

**Comment by jlewi** [comment]
We should be able to do this programmatically using the GitHub API.
https://developer.github.com/v3/issues/labels/#create-a-label

Here's a shell script that is similar
https://gist.github.com/rentzsch/4540430

The shell script deletes all labels first; which is probably not what we want to do.

I think I'd prefer a python script so we can do things like check if label already exists and if it does maybe just change its color.

The [requests](http://docs.python-requests.org/en/master/) library should make this fairly straightforward.

**Comment by chrisheecho** [comment]
Hi team, @texasmichelle and I worked on the [first iteration of the labels.](https://docs.google.com/spreadsheets/d/1u1jelEPca6-S8Ozcq4snDOBy4q4--J7Ois2YV59PNS4/edit?usp=sharing) Please take a look and review by next community meeting. would love to get feedback if you are interested

I've added comments access to everyone who have access to kubeflow-discuss@googlegroups.com

**Comment by gaocegege** [comment]
@chrisheecho Thanks for your work, generally LGTM although I added some comments.

**Comment by jlewi** [comment]
LGTM.

Created #24 to actually sync the labels.

**Comment by texasmichelle** [comment]
@chrisheecho have we memorialized this list anywhere yet? Perhaps CONTRIBUTING.md in either [kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/blob/master/CONTRIBUTING.md) or [kubeflow/community](https://github.com/kubeflow/community/blob/master/contributing.md) would be a good place. I'll submit a PR using the Sheets doc if you haven't put them somewhere else.

**Comment by chrisheecho** [comment]
Yes that sounds good. Frankly I didn't know we had to do that. Sgtm do what
you gotta do

**Comment by texasmichelle** [comment]
Better to commit a markdown file to the repo instead of relying on a link to a Sheets doc buried in a closed issue.

**Comment by chrisheecho** [comment]
great. if you are busy with your GH issue stuff I can do this too just lmk

**Comment by texasmichelle** [comment]
It's cool - the PR is ready to merge

**Comment by texasmichelle** [comment]
As @jlewi pointed out on today's community call, `help wanted` and `good first issue` are [GitHub-wide guidelines](https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/), so it makes sense to remove `starter` in favor of these. My preference is to choose one of them,  so unless anyone really wants both, I'll create a PR with `good first issue`.

**Comment by chrisheecho** [comment]
Sgtm!
