### ISSUE TITLE
Create repository batch-predict

### ISSUE THREAD

**Issue by yixinshi** [kubeflow/community#121]
We need a repo for the batch predict related code for Kubeflow from Google. See
https://github.com/kubeflow/kubeflow/issues/662

**Comment by jlewi** [comment]
Repository created.

I added ci-bots core-approvers and @yixinshi 

Please follow 
https://github.com/kubeflow/community/blob/master/repository-setup.md

To finish setting it up. In particular please enable automatic merging.
