### ISSUE TITLE
[devstats] Set companies

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/community#125]
http://devstats.kubeflow.dev/d/9/companies-table?orgId=1

Now we do not support the company related statistics. Maybe it requires some additional configuration.

**Comment by gaocegege** [comment]
- [import_affs](https://github.com/cncf/devstats/blob/master/cmd/import_affs/import_affs.go)
- `import_affs` takes one parameter - JSON file name (this is a file from [cncf/gitdm](https://github.com/cncf/gitdm): [github_users.json](https://raw.githubusercontent.com/cncf/gitdm/master/github_users.json)
- This tools imports GitHub usernames (in addition to logins from GHA) and creates developers - companies affiliations (that can be used by [Companies stats](https://k8s.devstats.cncf.io/dashboard/db/companies-stats?orgId=1) metric)

**Comment by gaocegege** [comment]
I followed the instructions to generate a github_users.json: https://raw.githubusercontent.com/gaocegege/gitdm/master/github_users.json

**Comment by jlewi** [comment]
Couldn't we use members.yaml to determine which company each user belongs to?

**Comment by gaocegege** [comment]
We can but devstats already has a mature tool to do it. I think we could reuse it.

**Comment by jlewi** [comment]
#208 added a simple script that can use the github_users.json file and the data exported from devstats to compute # of PRs from different companies.

Here's my fork of https://github.com/jlewi/gitdm
I made some changes to compute github_users.json for Kubeflow.

**Comment by amsaha** [comment]
Following up on https://kubeflow.slack.com/archives/C8Q0QJYNB/p1542385363024300, what is pending? It seems that #208 is already merged.

**Comment by jlewi** [comment]
@amsaha I think we would like to get devstats updated so that it automatically and continuously computes PRs by companies.

I suspect there's two things we need to do

1. Figure out how to make devstats use github_users.json to compute PRs per company
1. Figure out how to regularly update github_users.json

**Comment by amsaha** [comment]
Thanks @jlewi. Will take a look soon.

**Comment by gaocegege** [comment]
@gyliu513 Awesome work!

BTW, I am not sure how to change the affiliation, in the dashboard, I am independent while I am not.

**Comment by gyliu513** [comment]
@gaocegege just create a review request to openstack like this https://review.openstack.org/#/c/625774/ , some detailed steps for how to create review request in openstack https://docs.openstack.org/infra/manual/developers.html 

Once you add all of your emails to `openstack/stackalytics`, your name will appear in your affinity.

**Comment by gyliu513** [comment]
@jlewi if the pr was submitted with setting email as your company email, then there is no need to submit or to update. But if you are not using company email to create or, you may want to submit a pr to OpenStack to correct your affiliation.

Stakalytics is becoming an official website for open source contribution, like Kubernetes, Istio, knative etc, so it would be great for kubeflow as part of it, comments?

**Comment by jlewi** [comment]
See comment
https://github.com/kubeflow/community/issues/222#issuecomment-450881197
