### ISSUE TITLE
Serve devstats at devstats.kubeflow.org not devstats.kubeflow.dev

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#129]
We should serve devstats @ kubeflow.org and not kubeflow.dev to be consistent. 

I can't remember why I initially picked kubeflow.dev. I think it was because I was experimenting with Cloud DNS and kubeflow.org wasn't administered by Cloud DNS @ the time.

**Comment by jlewi** [comment]
Interestingly, nslookup returns some incorrect results

```
nslookup devstats.kubeflow.org
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	devstats.kubeflow.org
Address: 198.105.244.130
Name:	devstats.kubeflow.org
Address: 104.239.207.44
```

The correct IP (the one used by devstats.kubeflow.dev is 35.190.42.248). I've created a DNS record in Cloud DNS for devstats.kubeflow.org. Just need to wait for it to propogate.

**Comment by jlewi** [comment]
Looks like devstats.kubeflow.org is now returning the correct address

```
nslookup devstats.kubeflow.org
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	devstats.kubeflow.org
Address: 35.190.42.248
```
Deleting the record devstats.kubeflow.dev (it will just cause confusion over time).

**Comment by lukaszgryglicki** [comment]
DevStats can now be deployed on the Kubernetes cluster using helm chart, see this:
- [helm chart](https://github.com/cncf/devstats/tree/master/devstats-helm).
- [kubernetes stuff](https://github.com/cncf/devstats/tree/master/k8s).
It uses [this script](https://github.com/cncf/devstats/blob/master/k8s/build_images.sh) to build 3 docker images: `lukaszgryglicki/devstats`, `lukaszgryglicki/devstats-minimal`, `lukaszgryglicki/devstats-grafana`.

It is also missing SSL/https and DNS (using `EKS` `LoadBalancer` deployment+service external name which defaults to something like [aws elb based name](http://a1ab28809433611e98f5602de9aa28f2-1477584054.us-west-2.elb.amazonaws.com:3000/)).
