### ISSUE TITLE
Repository for CRD that implements simple triggering/scheduling mechanisms on top of Argo workflows

### ISSUE THREAD

**Issue by vicaire** [kubeflow/community#132]
I would like to contribute a CRD that implements simple triggering/scheduling mechanisms on top of Argo workflows. Would it be possible to create a repo for this?

**Comment by vicaire** [comment]
Sounds good.

**Comment by jlewi** [comment]
I created the repository please follow instructions below to finish setting it up
https://github.com/kubeflow/community/blob/master/repository-setup.md

/assign @vicaire
