### ISSUE TITLE
Setup Cloud DNS records for gsuite

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#135]
We switched our DNS from using Google Domains to Cloud DNS. This broke gmail for kubeflow.org because we are missing MX records.

Doc with info about MX records
https://support.google.com/a/answer/174125?hl=en

/cc @ewilderj 
/priority p0
/assign jlewi

**Comment by jlewi** [comment]
Ran the following commands

```
gcloud --project=kubeflow-dns dns record-sets transaction start -z=kubefloworg
gcloud --project=kubeflow-dns dns record-sets transaction add -z=kubefloworg  --type=MX  --name="kubeflow.org."  --ttl=3600 \
	"1 ASPMX.L.GOOGLE.COM." "5 ALT1.ASPMX.L.GOOGLE.COM." "5 ALT2.ASPMX.L.GOOGLE.COM." \
	"10 ALT3.ASPMX.L.GOOGLE.COM." "10 ALT4.ASPMX.L.GOOGLE.COM."
gcloud --project=kubeflow-dns dns record-sets transaction execute -z=kubefloworg
```

**Comment by jlewi** [comment]
Confirmed that I could send email to jlewi@kubeflow.org

**Comment by ewilderj** [comment]
WFM too. Thanks for sorting this out!
