### ISSUE TITLE
setting up the dashboard for two systems(master-worker) on openstack

### ISSUE THREAD

**Issue by nilanjana2015** [kubeflow/community#144]
I have set up a kubernetes cluster with two openstack instances(master-worker). I wanted to expose the kubernetes dashboard exposed to the internet. The dashboard doesn't open from my local even after setting it up. Is there some restriction from kubernetes/openstack side? Why can't I access it from my browser ?

**Comment by jlewi** [comment]
I'd suggest looking at the docs for the K8s dashboard
https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above

If you're just trying to access the K8s dashboard then that doesn't really involve Kubeflow.

**Comment by jlewi** [comment]
What is the problem you are having with Jupyter? Are you trying to connect using `kubectl port-forward`

**Comment by nilanjana2015** [comment]
The jupyter notebooks are all up and running as I can see in my terminal(logging in into master)  but the only problem is I am not able to check it on my browser. Both are machines that I am using for creating my cluster are openstack instances.

**Comment by jlewi** [comment]
If you are trying to access the notebooks you will need to figure out how you connect to services running inside your cluster from your local machine. Did you try following the [instructions](https://github.com/kubeflow/kubeflow/blob/master/user_guide.md#bringing-up-a-jupyter-notebook) to use kubectl to port-forward to JupyterHub?
