### ISSUE TITLE
Create marketing-materials repository

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#147]
@aronchick Created the repository marketing-materials.

Creating this issue to track setup.

It looks like the repo is missing an initial commit.

**Comment by jlewi** [comment]
Added an OWNERs file; need to finish setting it up.

**Comment by jlewi** [comment]
Tide is enabled for the Kubeflow org
https://github.com/kubernetes/test-infra/blob/d813268c258ad9e0486777611f7206f9d61e3e56/prow/config.yaml#L167

So we should be good to go for automatic merging.

**Comment by gaocegege** [comment]
I think we could close the issue.

https://github.com/kubeflow/marketing-materials
