### ISSUE TITLE
new repository for chainer-operator

### ISSUE THREAD

**Issue by everpeace** [kubeflow/community#149]
Probably kubeflow/chainer-operator.

See https://github.com/kubeflow/community/blob/master/proposals/chainer-operator-proposal.md.

/area operator
/assign @jlewi

**Comment by jlewi** [comment]
Created a repository
https://github.com/kubeflow/chainer-operator

Added ci-bots with write access

Enabled branch protection on master

Please submit an OWNERs file per
https://github.com/kubeflow/community/blob/master/repository-setup.md

**Comment by gaocegege** [comment]
I think we could close the issue since we already have the repository.
