### ISSUE TITLE
Add slack auto-generates invites - Open for everyone

### ISSUE THREAD

**Issue by amitkumarj441** [kubeflow/community#15]
# Why auto-generates invites?
It helps user to get its own invite link and anyone can easily join without searching for a shared / invitation link.

Ongoing PR - #13

**Comment by jlewi** [comment]
It looks like we have the slackin APP enabled for kubeflow.slack.com
https://github.com/rauchg/slackin

We also have a shared invite link in our Getting Involved page
https://github.com/kubeflow/kubeflow#get-involved

@aronchick Is that link sending a request each time someone wants to join?

**Comment by amitkumarj441** [comment]
Actually https://github.com/kubeflow/kubeflow#get-involved is a shared invite link (I hadn't have a chance to be in trouble) and shared invite (means token) used to get access. It basically let's users to have a token in their hand (not [legacy token](https://api.slack.com/custom-integrations/legacy-tokens)).

**Comment by jlewi** [comment]
According to @vkoukis our shared invite link might no longer work.

Maybe its time to setup slackin or some other solution?

**Comment by vanpelt** [comment]
The slack invite link here has expired: https://www.kubeflow.org/docs/about/community  It should be easy for the slack admin to generate a new one that doesn't expire...

**Comment by jlewi** [comment]
@vanpelt Do you have instructions for how to generate an invite link that doesn't expire? I don't know how the original link was generated.

@aronchick Do you remember?

**Comment by jlewi** [comment]
Ok I generated a new link
I did this by selection
Administration > Invite Members > Share Link
https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

**Comment by vanpelt** [comment]
Awesome!  I'm in 😎

**Comment by tekumara** [comment]
@jlewi that link (and the link on the website) has now expired, would it be possible for you to post an new one?

**Comment by jlewi** [comment]
https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLTdkNTVhMjg1ZTExOWI0N2QyYTQ2MTIzNTJjMWRiOTFjOGRlZWEzODc1NzMwNTMwM2EzNjY1MTFhODczNjk4MTk

@tekumara Could you submit a PR to update the website?
