### ISSUE TITLE
 [Request] Repository for CRD Validation Tool

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/community#151]
I am working on CRD validation for kubeflow/tf-operator and implementing a general-purpose tool https://github.com/gaocegege/crd-validation

I think we could use the tool to generate CRD validation spec for each CRD in the community, and it should work after Kubernetes 1.11 is released with `additionalproperty` support in the validation feature. Then I request to create a repository for the tool.

**Comment by jlewi** [comment]
Can we put the tool in tf-operator for now and think about refactoring later?
Every repository brings with it non-negligible overhead.

Also assuming tf-operator will be the first use for this tool keeping it in the same repository will make it easier to summit PRs that modify the tool and tf-operator simultaneously to keep them in sync.

**Comment by gaocegege** [comment]
OK, we could put the tool in gaocegege/crd-validation and keep the thing going.

**Comment by gaocegege** [comment]
Could we move the tool to kubeflow?

**Comment by jlewi** [comment]
@gaocegege My apologies for not responding sooner. Should we just transfer over the existing repository?
Just let me know what you need from me to do the transfer.

**Comment by gaocegege** [comment]
This repo only needs a transfer. While I have no permission to create repos in Kubeflow. We have to choice:

1. Give me a temporary permission to transfer
2. @jlewi accepts the invitation in https://github.com/kubeflow-incubator and transfer it to kubeflow.

**Comment by jlewi** [comment]
I accepted the invite. @gaocegege can you just confirm here that you want me to go ahead and transfer 
https://github.com/kubeflow-incubator/crd-validation
to Kubeflow?

**Comment by gaocegege** [comment]
Yeah, I think so. 😄

**Comment by jlewi** [comment]
Done
https://github.com/kubeflow/crd-validation
