### ISSUE TITLE
accepted-proposals.md doesn't seem to be properly maintained

### ISSUE THREAD

**Issue by ddysher** [kubeflow/community#155]
https://github.com/kubeflow/community/blob/master/accepted-proposals.md

:point_up_2: should we get rid of this file and simply point community members to `proposal` directory?

/cc @jlewi @ewilderj @gaocegege @ScorpioCPH

**Comment by ScorpioCPH** [comment]
SGTM, let's simplify the proposal process.

**Comment by jlewi** [comment]
I think that's reasonable.

Should we encourage people to directly update there markdown docs to include status information.

So as an example for 

tf-operator-design-v1alpha2.md

We could have a status section with points like

2018-XX-XX - Accepted
2018-XX-XX - Implementation Started
2018-XX-XX - v1alpha2 released in 0.2

**Comment by ewilderj** [comment]
Makes sense to me.

**Comment by ddysher** [comment]
/assign

Assign to myself, trying to catch up with kubeflow status. 

I created a PR to update the proposals: https://github.com/kubeflow/community/pull/156, PTAL

**Comment by gaocegege** [comment]
@ddysher 
Thanks!

**Comment by ddysher** [comment]
https://github.com/kubeflow/community/pull/156 is merged

/close
