### ISSUE TITLE
[Request] Repository for TFJob Java Client

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/community#161]
@JetMuffin contributes Java client for TFJob. And the contribution needs 2 repos: one for Java client and one for spec generation tool.

I request to introduce it into kubeflow org from kubeflow-incubator org. WDYT

@jlewi

**Comment by jlewi** [comment]
@gaocegege My apologies for not responding sooner. Should we just transfer over the existing repositories?

**Comment by gaocegege** [comment]
@jlewi We need some additional work to do. I think @JetMuffin will help us.

**Comment by jlewi** [comment]
SGTM. When you're ready to actually move the repository just find me on slack so we can coordinate.

**Comment by gaocegege** [comment]
Thanks.

/cc @JetMuffin
