### ISSUE TITLE
[Proposal] Kubeflow Base Images and Supporting Vendors

### ISSUE THREAD

**Issue by tmckayus** [kubeflow/community#165]
This is a proposal originally drafted by Jeremy Lewi with contributions from others, it may still need more eyes and refinement before we consider it final.

The goal is to create a set of guidelines for supporting multiple distros as base images in kubeflow components.

https://docs.google.com/document/d/1B3LumU7u9dJA0ElM37KlPeSHJzSSpLV1l52E9ZmbJvo/edit#heading=h.alaoz7uek0k7

**Comment by jlewi** [comment]
Thanks @tmckayus what would next steps look like?

**Comment by carmine** [comment]
It'd be great to see a prototype of a proposed solution, or start with a proposed solution and go from there. Take one of the kubeflow components (or each type of component as per the google doc) and demonstrate what the solution could look like.  This is for producing images, and ideally the e2e test for those as well.
