### ISSUE TITLE
Turning multiple end user machines (PCs, Macs, RPi ... etc) into one giant k8s cluster 

### ISSUE THREAD

**Issue by sbhamad** [kubeflow/community#169]
Hi Kubeflow community,

I am new to kuberenetes && kubeflow and i have a simple question.

is it possible to turn every end user machine (PCs, Macs, RPi ... etc) who with full consent downloaded my electron research app that should turn their machines into nodes that ultimately comprise a k8s cluster which then i can run kubeflow.org on to do ML research?

Thanks

**Comment by jlewi** [comment]
This is outside the scope of Kubeflow. This would be a question for the Kubernetes community to figure out  how to assemble user machines into a K8s cluster.
