### ISSUE TITLE
Add links to good first issue and help wanted

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#17]
Our docs for contributions should provide links for searching for all issues labeled with "help wanted" and/or "good first issue".

We'd like the search results to search across all repositories in the Kubeflow org.

**Comment by gaocegege** [comment]
I think https://github.com/issues?q=is%3Aopen+is%3Aissue+org%3Akubeflow+archived%3Afalse+label%3A%22good+first+issue%22 works for us.

**Comment by texasmichelle** [comment]
Annoyingly, search does not support boolean OR, so I included separate links for each of the existing labels, as well as the new starter label.
