### ISSUE TITLE
[devstats] Use devstats to identify top contributors

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#172]
Now that devstats is back up
devstats.kubeflow.org

It would be great to use it to identify top contributors and recognize them at our summit in September.

**Comment by jlewi** [comment]
This table allows us to break down contributors by number of PRs.
https://devstats.kubeflow.org/d/13/developers-table?orgId=1&var-period_name=v0.2.0%20-%20now&var-metric=prs&var-period=anno_1_now

**Comment by gaocegege** [comment]
I think we could close the issue since we already support it.
