### ISSUE TITLE
Need a way to allow others to tag issues for different releases

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#173]
Setting labels on issues requires write permission which is overly broad.

Prow has two relevant commands
/label  - Allows members of the org to set certain labels

The label plugin provides commands that add or remove certain types of labels. Labels of the following types can be manipulated: 'area/*', 'committee/*', 'kind/*', 'priority/*', 'sig/*', 'triage/*', and 'wg/*'. More labels can be configured to be used via the /label command.

/milestone

The milestone plugin allows members of a configurable GitHub team to set the milestone on an issue or pull request.

Unfortunately, I think prow configures milestone to use a group for Kubernetes which wouldn't make sense for us.

I think a quick fix would to just be to use the label

area/X.X.X

as opposed to

release/X.X.X

We can start doing this for our 0.4.0 release.

**Comment by jlewi** [comment]
After #200 is merged we can close this once we verify the label sync ran and we have the label added to all our repos.

**Comment by jlewi** [comment]
The correct command is

/area 0.4.0

**Comment by jbottum** [comment]
Great.   I just tried it on this open item and it worked.   Thanks!

https://github.com/kubeflow/kubeflow/issues/1620

**Comment by jlewi** [comment]
To remove you can do

/remove-area 0.4.0
Full help here
https://prow.k8s.io/command-help?repo=kubeflow%2Fkubeflow

**Comment by jlewi** [comment]
Adding it back
/area 0.4.0

**Comment by jbottum** [comment]
Yes, I did it and It removed the label.
