### ISSUE TITLE
Document release planning process

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#174]
We should create an markdown doc describing the release planning process.

It probably makes sense to add it to our existing releasing doc here:
https://github.com/kubeflow/kubeflow/blob/master/docs_dev/releasing.md

We need to document how we assign/track issues for each release.

Per #173 I think the short term solution is to use a label like

area/X.X.X

This way any member of the Kubeflow GitHub org should be able to tag issues using the prow

/label area/X.X.X

command

To define labels for the release you can submit a PR adding it to this YAMl file
https://github.com/kubeflow/testing/blob/master/label_sync/kubeflow_label.yml

A cron job periodically ensures that the labels in that file are added to all repositories.

/cc @jbottum

**Comment by jbottum** [comment]
Hey Jeremy - Thanks for the advice.    I have started to look at the
existing open issues.

I am thinking that we should look at the top candidates on that list i.e.
the existing features that are labeled in 0.4, the existing P0 and P1 that
are not in another release.     This doc works to identify those features:

https://docs.google.com/document/d/13vBugi1eHND9WFDtasEhvY8BkFJ8MUfahTFsVG13_LU/edit
