### ISSUE TITLE
Create a features repo for PMs

### ISSUE THREAD

**Issue by chrisheecho** [kubeflow/community#189]
For PM community group and to have a backlog of features and related process, I would like to have a permission to create a repo please! @jlewi @aronchick

**Comment by chrisheecho** [comment]
Fantastic, basically it's following the structure that https://github.com/kubernetes has. They have a split between community and features. I see community as the overarching guidance and governance place, where as Features repo will primarily be a working space for the PMs. In addition, it's a place to track features per release so we have PM+Release folks working together in a repo.

 New feature request issue in one of the existing repos might make sense in some cases where an issue/bug can turn into a feature in the future. However, if it's a brand new features with a proposal or roadmap centric discussion, I think it makes more sense to have it in the features repo.

**Comment by jlewi** [comment]
Thanks created it.

**Comment by chrisheecho** [comment]
you da man

**Comment by idvoretskyi** [comment]
@jlewi the intent is to have a repo similar to https://github.com/kubernetes/features, which heavily inspired the KubeFlow PM group to have a features repo here.

Thanks for creating!

cc @chrisheecho
