### ISSUE TITLE
/label area/0.4.0 doesn't seem to be working 

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#191]
The ci bot doesn't appear to be responding to label commands

Related to #173 allow members to tag issues for releases.

**Comment by jlewi** [comment]
Looks like label plugin is enabled here:
https://github.com/kubernetes/test-infra/blob/a20b1356786b88cf34233eb144e0c144ff017f64/prow/plugins.yaml#L264

**Comment by fejta** [comment]
Is this what you meant? The /label I think just creates the label. Doesn't add it to the PR?

**Comment by jlewi** [comment]
Yup exactly. 

Thanks @fejta
