### ISSUE TITLE
Issue closer bot

### ISSUE THREAD

**Issue by pdmack** [kubeflow/community#194]
Other projects automatically close issues that are stale after some period of inactivity (e.g., 90 days). It sounds like maybe we have that already but it's not working?

**Comment by jlewi** [comment]
We can use this probot.
https://probot.github.io/apps/stale/

**Comment by jlewi** [comment]
Probot has been installed. Per the instructions need to create a 
.github/stale.yml  file in order to enable it.

**Comment by jlewi** [comment]
This is working. Individual repos just need to add a config file as in #3260.
https://github.com/kubeflow/kubeflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Alifecycle%2Fstale
