### ISSUE TITLE
Setup Automatic merge of PRs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#20]
Setting up automatic merging of PRs should help velocity.

@DjangoPeng I think you said someone on your team has experience setting this up and can do it.

**Comment by DjangoPeng** [comment]
Yep, we have rich experience on that. 

@ddysher

**Comment by DjangoPeng** [comment]
Yep, we could handle it.

**Comment by ddysher** [comment]
@jlewi what's the status of test infra?  to setup, we need to access test infra cluster and setup ingress rules

**Comment by jlewi** [comment]
@ddysher We currently don't run our own instance of prow. We are using the instance of prow operated and maintained by the K8s test team.

Can/should we give the existing K8s test infra the necessary permissions to merge PRs for the kubeflow org?

We do have GCP projects setup running GKE clusters where we can run additional services if needed.
The project is `kubeflow-ci` and you should have access to it.

/cc @krzyzacy @BenTheElder

**Comment by BenTheElder** [comment]
IIRC the bot needs write permissions to the repo to do merges, and then we just need to configure `tide` for this repo.

**Comment by krzyzacy** [comment]
@jlewi you can add a query similar to https://github.com/kubernetes/test-infra/blob/master/prow/config.yaml#L86-L95, or add your repo to an existing query, in our prow config

**Comment by jlewi** [comment]
@krzyzacy Thanks. Do I need to specify individual repos or can I just specify the org and have it apply to all repos in the org?

**Comment by krzyzacy** [comment]
I think you need to specify individual repos
cc @cjwagnar maybe we can enable an entire org in the future?

**Comment by jlewi** [comment]
@BenTheElder @krzyzacy @cjwagner

kubeflow/kubeflow#175 is listed as being in the tide pool but when I click the link
https://prow.k8s.io/tide

I don't actually see it in the tide pool. Does something else need to happen?

**Comment by krzyzacy** [comment]
hummm maybe because of reviewable is not green?
looks like it passed batch test
```
"prs-pending":null,"controller":"sync","batch-pending":null,"prs-missing":null,"prs-passing":[175],"level":"info","batch-passing":null,"branch":"master","org":"kubeflow"
```

**Comment by jlewi** [comment]
(I think k8s-ci bot may not have had write for kubeflow/community which is why previous commands in this PR didn't work)
/joke

**Comment by BenTheElder** [comment]
@jlewi the page there has some latency. cc @cjwagner we should load the pools much more frequently

**Comment by krzyzacy** [comment]
```
"error":"invalid character '(' after object key:value pair","component":"deck","msg":"Updating pool.","level":"error","agent":"tide"
```

**Comment by BenTheElder** [comment]
it's in the pool as WAIT now, you can see it on the page

**Comment by BenTheElder** [comment]
er no, wrong PR :(

**Comment by cjwagner** [comment]
I spun up a busybox pod and curled the tide endpoint that deck is complaining about. It looks like the offending JSON snippet is:
```json
{"Context":"coverage/coveralls","Description":"Coverage increased (+0.1%!)(MISSING) to 27.599%!"(MISSING),"State":"SUCCESS"}
```

Is this a bug in the json library?

**Comment by jlewi** [comment]
@cjwagner We have Coveralls turned on for kubeflow/tf-operator but not kubeflow/kubeflow. Does this still explain why kubeflow/kubeflow#175 wasn't auto-merged.

**Comment by jlewi** [comment]
This is working.
https://github.com/kubeflow/examples/pull/18#pullrequestreview-100679172

As @BenTheElder and @krzyzacy explained above it was the Reviewable status check not being green that was blocking the other PR. I'll change reviewable to not be a status check.

@BenTheElder @krzyzacy @cjwagner thank you so much for all your help this is awesome.
