### ISSUE TITLE
Request to join slack channel

### ISSUE THREAD

**Issue by gyliu513** [kubeflow/community#220]
@jlewi can you help send an invitation? My email address is gyliu513#gmail.com

**Comment by TimZaman** [comment]
@gaocegege Could you invite me too to the slack channel? (timbobel$gmail.com)

**Comment by gyliu513** [comment]
@TimZaman please try this one https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

**Comment by Techyuvi** [comment]
please invite me to join slack channel (yuvi.singtak@gmail.com)

**Comment by jlewi** [comment]
@Techyuvi you can grab the slack invite from our docs page
https://www.kubeflow.org/docs/about/community/#forums-and-mailing-groups

**Comment by sleep-404** [comment]
Hello @jlewi , I think the link is no longer active. Is it possible to get an updated link ?

**Comment by nehakapila94** [comment]
I would like to join the channel. Please someone send me link

**Comment by theofpa** [comment]
For future visitors of this issue, the invitation link to our slack workspace can be found in https://www.kubeflow.org/docs/about/community/

**Comment by gaocegege** [comment]
https://www.kubeflow.org/docs/about/community/#slack-community-and-channels

**Comment by skmaingi** [comment]
To join the channel one needs to have an email from only 3 domains (google.com, microsoft.com and caicloud.io)

**Comment by gaocegege** [comment]
@Bobgy Can you have a look at it?

**Comment by thesuperzapper** [comment]
The issue of Slack invites is tracked here: https://github.com/kubeflow/community/issues/473
