### ISSUE TITLE
[Discussion] Is there any work on pytorch-operator.

### ISSUE THREAD

**Issue by DjangoPeng** [kubeflow/community#23]
In the latest kubeflow community meeting, we discussed the possibility of supporting PyTorch in kubeflow. The example of tf-operator shows one way to start pytorch-operator project.

First of all, we have established a channel called `pytorch-operator` on slack. Anyone who has interest could join in and discuss with other contributors.

Secondly, we should search for if there are some existing work on `pytorch + k8s`. If so, we'd better add corresponding links, blogs, etc here.

Finally we could discuss how to `merge` and `cherry-pick` the current work around `pytorch + k8s`. When we reach an agreement on the mission and scope of `pytorch-operator` project, it's time to create a `pytorch-opeartor` repo.

WDYT @jlewi @ddysher @Jimexist @gaocegege

**Comment by jlewi** [comment]
There's an existing issue about PyTorch distributed training
kubeflow/kubeflow#179

I think a good first step for PyTorch support would be

- Provide Jupyter images with PyTorch
- Provide E2E examples using PyTorch in single distributed mode

There's a DockerFile for PyTorch here
https://github.com/pytorch/pytorch/blob/master/Dockerfile

**Comment by erikerlandson** [comment]
This might be a great vehicle to test-drive the kubeflow proposal workflow:

https://github.com/kubeflow/community/blob/master/proposal-workflow.md

**Comment by DjangoPeng** [comment]
SGTM.

The next mxnet-operator, caffe-operator and other ML frameworks could follow the workflow.

**Comment by ddysher** [comment]
before we start creating too many operators, we can leverage the so call operator-kit to make implementation easier and consistent.

https://docs.google.com/document/d/1NJhFcNezJyLM952eaYVcdfIQFQYWsAx4oTaA82-Frdk/edit
https://github.com/giantswarm/operatorkit/
https://github.com/rook/operator-kit/

**Comment by erikerlandson** [comment]
@ddysher +1
There might be other operator kits to choose from, for example
https://github.com/spotahome/kooper
A kit coming out of rook may eventually benefit from a larger community.

**Comment by jlewi** [comment]
I think we should distinguish between distributed and non-distributed PyTorch.

I think non-distributed PyTorch might be a relatively low investment; its mostly about getting the right set of Dockerfiles and an example. PyTorch seems to be growing in popularity and this might be a good way to begin connecting our community with theirs.

Distributed training and an associated operator is a much bigger investment. Supporting non-distributed PyTorch first might be a good way to gauge the interest in distributed training.

**Comment by erikerlandson** [comment]
@jlewi are you proposing an operator for standing up a non-distributed pytorch instance?

**Comment by jlewi** [comment]
@erikerlandson No. I think the motivation for a PyTorch operator is still unclear. I suspect non-distributed PyTorch covers a lot of use cases and we probably don't need an operator for that.

**Comment by ddysher** [comment]
is operator only scoped to distributed environment?  being able to manage a fleet of machines uniformly for admins, and a consistent interface for developers also sounds like a pro for us?

**Comment by jlewi** [comment]
@ddysher An operator could make sense for other use cases. For example, Argo and Seldon Core are both operators/custom resources.

Can you provide more information about the use case you are describing?

**Comment by jlewi** [comment]
@ddysher @erikerlandson I believe there is a K8s project coming out soon called kube-builder that is also supposed to solve the problem of making it easy to write APISever extensions and CRD.

I think they are just trying to figure out where to publish the code
https://groups.google.com//forum/#!topic/kubernetes-sig-api-machinery/xJnn062qF8E

**Comment by erikerlandson** [comment]
@jlewi sounds like it is getting good community buy-in.

I'm a little confused by what it means to be forking an entire incubator project, and then finding a new home for it.  Does that mean `kubernetes-incubator/apiserver-builder` is being obsoleted?

**Comment by jlewi** [comment]
@erikerlandson Don't know.
Looks like its been published here:
https://github.com/kubernetes-sigs/kubebuilder

**Comment by jlewi** [comment]
The repo for pytorch has been created:
https://github.com/kubeflow/pytorch-operator

Closing this issue.
