### ISSUE TITLE
Question: will kubeflow continue using ksonnet even if its development may end soon?

### ISSUE THREAD

**Issue by Insullone** [kubeflow/community#237]
I found the message on the front page of ksonnet (https://ksonnet.io/) that "The team behind ksonnet is stepping back from the project. As a result, work on ksonnet will end and the GitHub repositories will be archived". I want to know if there is a plan to continue using ksonnet or replace it? Thank you.

**Comment by n-batalha** [comment]
Can be closed as a duplicate?

* https://github.com/kubeflow/kubeflow/issues/2738
* https://github.com/kubeflow/kubeflow/issues/2412

**Comment by Insullone** [comment]
OK.
