### ISSUE TITLE
Create a kubeflow/kfserving repository

### ISSUE THREAD

**Issue by ellis-bigelow** [kubeflow/community#242]
With the recent Kubeflow Serving Working Group activity, it's time to have a place to collaborate together. We need a repository e.g. kubeflow/serving for its design proposals, api and schema docs, and implementations.

**Comment by ellis-bigelow** [comment]
Any thoughts @cliveseldon, @aronchick, @lluunn, @yuzisun, @rakelkar

**Comment by abhi-g** [comment]
I think this is a good idea given the recent discussions happening in the serving working group.

**Comment by cliveseldon** [comment]
Probably should consider `kubeflow/kfserving` as well. If `kubeflow/serving` then should probably ensure the repo would include all things serving related like TensorRT, raw TFServing and Seldon.

**Comment by abhi-g** [comment]
Yeah, my hope is that we move all serving components in this repository.

**Comment by ellis-bigelow** [comment]
I think the scope of the initial project we're working on is definitely enough to warrant its own repository. I want to avoid a catch-all repo for serving, as it would be confusing to consumers and developers alike.

What do you think about kfserverless?

**Comment by ellis-bigelow** [comment]
Thinking a little further on this, serverless is broader than serving. I think I like Clive's kfserving suggestion best.

**Comment by abhi-g** [comment]
Created and setup [https://github.com/kubeflow/kfserving](https://github.com/kubeflow/kfserving)
