### ISSUE TITLE
Setup project maintainers and issue triage group

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#250]
Prow has a new /project command see kubernetes/test-infra#10514.

This uses a corresponding team list to specify which users have permission to add issues to projects.

We should set that up.

/assign @jlewi

**Comment by jlewi** [comment]
There was a bug in the "/project" plugin. kubernetes/test-infra#12117
This should be fixed so we should able to go ahead an enable the plugin.

**Comment by jlewi** [comment]
Lets test it
/project fairing

**Comment by jlewi** [comment]
@taragu Any idea what I'm doing wrong in terms of using the project plugin? It looks like if I don't specify a column name I get an error as seen above complaining column isn't specified. But if I specify a column name it doesn't seem to work.

**Comment by taragu** [comment]
@jlewi Thanks for letting me know. This does look like a bug. At a glance I'm not sure what's wrong. I will open an issue and fix it.

**Comment by jlewi** [comment]
@kkasravi Seemed able to do this
https://github.com/kubeflow/kubeflow/issues/3400#issuecomment-498635486

using 

> /projects istio-kustomize-readiness

**Comment by jlewi** [comment]
I wonder if this is an issue with membership or permissions.
team is set here
https://github.com/jlewi/test-infra/blob/72c4c8e7632d2c758ffe7fa4e2c15ec24721706e/prow/plugins.yaml#L269

It looks like the team "kubeflow-project-maintainers" no longer exists.

I wonder if that's because we started sync'ing the groups from github
https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml

And we never defined the group in the YAML file.

**Comment by kkasravi** [comment]
actually that didn't work. I had to go the the particular project - open the menu tab on the far right-hand side, search for an issue and drag it to the right column

**Comment by jlewi** [comment]
I created a new group:
project-maintainers
https://github.com/orgs/kubeflow/teams/project-maintainers

Permissions are pending in kubeflow/internal-acls#129

**Comment by jlewi** [comment]
It looks like GitHub now has a Triage role
https://help.github.com/en/articles/repository-permission-levels-for-an-organization

Which would allow us to give a group of people the ability to triage issues (e.g. apply labels).
Its not clear if people with triage permission can add issues to projects. Might be worth testing that out.

**Comment by jlewi** [comment]
We already have the project-maintainers group.
https://github.com/kubeflow/internal-acls/blob/680a0b832e8b8d35f228420f3eb94fdbde35f875/github-orgs/kubeflow/org.yaml#L374

Maybe we should start by reusing that group?

**Comment by jlewi** [comment]
I have given this group Triage permissions on repositoires
kfctl
kubeflow
website
examples
metadata
tf-operator
pytorch-operator
kfserving

**Comment by johnugeorge** [comment]
> @jbottum @elviraux as part of our new issue triage process we should setup a GitHub team and grant those folks issue triage permission so that that they can add labels. We can also see if that lets them add issues to projects (its unclear from the GitHub page).
> 
> Teams and permissions should be defined in the YAML file for our github org.
> https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml

@jlewi I can also help with triaging issues.

**Comment by jlewi** [comment]
@johnugeorge Can you send me a PR adding yourself to the team.

I checked and it looks like triage permission is insufficient. I think we need write access so that

1. Triagers can edit original issue description if needed
1. Tag issues into projects.

**Comment by jlewi** [comment]
This should be all setup.
