### ISSUE TITLE
Identify PRs that need attention

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#270]
The number of PRs keeps growing; we are now up to ~500 PRs per 28 days.

The backlog of PRs seems to be growing.
We have 44 open PRs in kubeflow
https://github.com/kubeflow/kubeflow/pulls?page=2&q=is%3Apr+is%3Aopen

It would be helpful to generate a report that lists outstanding PRs that need attention.

I think a good starting point would be 

* Use GitHub API to list all open PRs in kubeflow repos
* Determine whether the last comment was by the PR creator or not
* If the last comment was by the PR creator then they are most likely waiting on a reviewer to respond
* Compute how long the PR creator has been waiting for a response and print out the issues

We could do this in Python and possible in a jupyter notebook. Jupyter might be useful for ad-hoc manipulation.

Here's a snippet for querying GitHub using graphql and python
https://github.com/kubeflow/community/blob/192964ba4bff1896f2a3667eb806350fe8ee5c81/scripts/project_stats.py#L76

**Comment by gaocegege** [comment]
Agree. We need such a dashboard for PR. Could we add labels such as `status/needs-reply` to the PRs that the last comment was by the PR creator

**Comment by jlewi** [comment]
Maybe start with a python script and then go from there?

**Comment by theadactyl** [comment]
There's a service I've been looking into to generate dashboards: https://gitalytics.com/ 
Thoughts?

**Comment by jlewi** [comment]
@theadactyl Does gitalytics provide this info?
/cc @zabbasi

**Comment by hamelsmu** [comment]
Why don’t you folks use pull panda?  It’s free and included with GitHub!  https://pullpanda.com/
