### ISSUE TITLE
[chore] Insufficient quota of container build in gcloud

### ISSUE THREAD

**Issue by gaocegege** [kubeflow/community#271]
https://console.cloud.google.com/cloud-build/builds?project=kubeflow-ci&query=status%20%3D%20%22QUEUED%22 shows that we have many pending builds.

Most builds are requested by katib. Maybe we could find a temp solution in kaitb. But I think it is better to increase the quota.

**Comment by johnugeorge** [comment]
@richardsliu created a request to increase quota

**Comment by richardsliu** [comment]
This should be fixed now. The concurrent build limit is raised to 30.

/close
