### ISSUE TITLE
Automate Updating Kubeflow Calendar

### ISSUE THREAD

**Issue by scottilee** [kubeflow/community#274]
Please add more weekly meetings to the Kubeflow calendar (https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com) such as "KF Serving Working Group Sync @ Weekly from 9am to 10am on Wednesday (PST)".

Also, are the associated Hangouts for each meeting recorded? If so, are recordings posted to a central place or retroactively added as an attachment to the meeting invite?

**Comment by scottilee** [comment]
@theadactyl I'd appreciate your help on this! The tasks would be:

1) Add all weekly meetings to the Kubeflow calendar such as "KF Serving Working Group Sync"
2) I've never seen meeting recording links anywhere. I think two good options would be to start adding them on the meeting notes doc or add them to the meeting invite afterwards.

By the way, is there a bit.ly or other url shorterned link to the Kubeflow calendar?

**Comment by jlewi** [comment]
@scottilee and others a great way to help make this happen would be to automate it with the source of truth being GitHub.

Here's how this might work

1. Define a config file (e.g. YAML) that we can check into Git
1. Create a script to populate Google calendar based on the YAML config 

This way we can use GitHub to source community contributions for keeping the calendar up to date.

**Comment by scottilee** [comment]
Good idea, I'll see if I can come up with something using https://developers.google.com/calendar/v3/reference/events/insert.

**Comment by jlewi** [comment]
@scottilee as discussed in the bug; I think we will want to use a service account to run this program.

Do you know how we authorize a service account to have access to a Google calendar? Do we just make the service account an admin of the Google calendar?

**Comment by theadactyl** [comment]
A bit unrelated, but possibly? is the fact that even trying to manually add
things to the calendar has been not working consistently. I get events
rejected after being accepted every so often.

**Comment by scottilee** [comment]
@jlewi I updated the script to use a service account. If the Google account hosting the Kubeflow calendar has the Google Calendar API enabled, create the service account and share the Kubeflow calendar with the service account email and the script should be able to modify and create events. Let me know if I can clarify anything.

https://github.com/kubeflow/community/pull/288

**Comment by jlewi** [comment]
@scottilee reopening this to continue to track automating sync'ing of the KF calendar.

**Comment by scottilee** [comment]
@jlewi Could you remind me of the requirements here? I'm assuming you want some kind of job that will periodically read [calendar.yaml](https://github.com/kubeflow/community/blob/master/calendar.yaml) and if there are differences run [calendar_import.py](https://github.com/kubeflow/community/blob/master/scripts/calendar_import.py). If that is correct, I'm thinking I could either run a [CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) in the Community Kubeflow cluster or use [Cloud Scheduler](https://cloud.google.com/scheduler/docs/creating) in the Community Kubeflow cluster.

**Comment by jlewi** [comment]
@scottilee I think that is correct. We just need to setup a cron job to run calendar_import.py regularly.

My initial thought is we should do the following

* Create a project and K8s cluster using GitOps in the community folder where we can run all of our automation

  * Call it something like "kf-automation" 

* Deploy this as a cron job.

The community folder is administered already via GitOps; with the PRs here
https://github.com/kubeflow/community-infra/tree/master/prod/namespaces

So you should be able to define a project by submitting a PR there and likewise deploy a GKE cluster by submitting a PR there.

**Comment by karlschriek** [comment]
Is there any progress on this? I'd be happy to help, but I have no access to any of the systems that need to be used here.

**Comment by karlschriek** [comment]
Also wondering why we need a cron job here? Couldn't we simply solve this with Github Actions (or whatever else we are using a CI/CD tool) and have it trigger whenever a commit comes on master where calendar.yaml has been changed?

**Comment by jlewi** [comment]
@karlschriek Why use GitHub actions as opposed to Kubernetes? All of Kubeflow's infra runs on Kubernetes and everyone in the project should be familiar with Kubernetes. GCP has built in support for IAM (e.g. workload identity) which makes working with sensitive data easier.

@karlschriek You can use https://github.com/kubeflow/community-infra to provision a cluster and GCP service account.

My recommendation would be to setup a GKE cluster and regular runs of the calendar sync tool. I would sync to a calendar you control so you are able to figure out what needs to happen to grant the Google service account permissions to modify the calendar. 

Once you figure that out we can do the same for the Kubeflow calendar and then just update the script to use the Kubeflow calendar.

**Comment by karlschriek** [comment]
Yeah, sorry, could have maybe phrased the question better. I was wondering specifically about the cron job suggestion, not about running on Kubernetes, since this seems like a straightforward CI case to me. Anyway it's not really that important. I've opened a PR as suggested and will scratch around abit to get to know the current infrastructure.

**Comment by jlewi** [comment]
@karlschriek using cron to periodically run a sync which pulls the latest changes is simpler and in many more ways secure then configuring it to accept webhooks from GitHub.  One pattern that works pretty well is running https://github.com/kubernetes/git-sync in a sidecar to keep a sync'd copy of the repo. Your main container can then be a persistent daemon that watches for changes and runs the sync.

**Comment by jlewi** [comment]
I might suggest the following as next steps

1. Create a GCP service account in the project created in kubeflow/community-infra#21
    * Preferably via GitOps
1. Download the service account key for this GCP SA
1. Grant the GCP SA permissions need to administer the calendar
1. Run calendar_import.py locally using the GCP SA

This would provide a mechanism for the calendar admins to run the sync.

It would also work through the problems of authorizing a GCP SA to administer the SA.

We can then spin up a GKE cluster to run this regularly.

**Comment by karlschriek** [comment]
Alright, sound good. For the GitOps process I will set up something along these lines:

GitHub (IaC declaration) -> GCP Cloud Build (CI/CD) -> GCP Deployment Manager (IaC rollout) 

Haven't worked with Deployment Manager before, but it seems straightforward enough. Any experience to the contrary? Could also substitute with Terraform though, it has pretty good GCP support.

**Comment by jlewi** [comment]
> GitHub (IaC declaration) -> GCP Cloud Build (CI/CD) -> GCP Deployment Manager (IaC rollout)

I think we can do something simpler.

* Create GKE cluster
* Containers the calendar sync code
* Deploy the calendar sync code
* When the calendar sync code runs get the latest data from GitHub

A very simple solution here is to use https://github.com/kubernetes/git-sync to run a sidecar that clones the repository and then modify calendar sync so it runs in a loop on some time interval

You can also deploy the config as a config map and then use ACM to sync the config map to the cluster and not rely on the sidecar.

**Comment by karlschriek** [comment]
What did you have in mind with creating the service account "preferably via
GitOps" then? That is what I was referring to, i.e. provisioning the needed
GCP infrastructure (service account, GKE cluster etc.).

**Comment by jlewi** [comment]
@karlschriek We use  Cloud Config Connector to declaratively manage GCP infra. The GitOps part is already configured.

You create a service account using the [IAMServiceAccount resource](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iamserviceaccount)

At this point you can download a service account via gcloud or pantheon and use that to run the script (once we get the GSA authorized to manipulate the calendar).

All of these resources should be defined in
https://github.com/kubeflow/community-infra/tree/master/prod/namespaces/kf-infra-gitops

Once the PR is merged the infra will get created automatically.
You can then create a GKE cluster the same way by defining a [ContainerCluster](https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster) resource.

If you want to enable GitOps for that newly created cluster then install [ACM](https://cloud.google.com/anthos-config-management/docs/how-to/installing) on that cluster and configure it to point to the repo and folder containing the manifests to sync to that cluster.

**Comment by jlewi** [comment]
@jtfogarty Since you were asking about the calendar; this is the issue.

**Comment by jlewi** [comment]
The calendar should now be sync'ing automatically whenever there is a change.

We can close this as soon as #428 is merged

**Comment by karlschriek** [comment]
Ok, so the sa now exists. How can grant it permission to administer the calendar?

**Comment by jlewi** [comment]
@karlschriek I took care of all the automation; the calendar is now being sync'd automatically.
