### ISSUE TITLE
Fork issue-label-bot to Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#275]
Opening this issue about creating a downstream fork of 
issue-label-bot in kubeflow.org.

https://github.com/machine-learning-apps/Issue-Label-Bot/issues

We've been working on this with the creator @hamelsmu and used it to demo motivate Kubeflow.
We also are using the label bot on our repos.

The motivation for creating a downstream fork in kubeflow.org is because we'd like to leverage prow for development and collaboration on that repo.

We could also use kubeflow-incubator but I'm not sure that's setup yet for prow.

We will be working with @hamelsmu on the issue-label-bot to allow training repo specific models.

**Comment by hamelsmu** [comment]
cc: @rand @herbfei @inc0

**Comment by jlewi** [comment]
This has been forked.
https://github.com/kubeflow/Issue-Label-Bot

**Comment by jlewi** [comment]
@inc0 and @hamelsmu gave you write permissions.
I bootstrapped an OWNERs file
https://github.com/kubeflow/Issue-Label-Bot/commit/721825ed44f463ecc59c45ec4f19867d3af44b96

I added myself, @inc0 and @hamelsmu 

If there are additional folks that should be added just an open a PR.
