### ISSUE TITLE
Setup GitHub actions to auto-add/remove issues needing triage to a Kanban board

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#278]
It would be really valuable if we could we use Kanban boards to track issues.
In particular, it would be great to track issues which need to be triaged

I think we could do this by having separate Kanban boards for

* Bugs
* Features
* Customer Questions

We can then auto-add issues into one of these projects based on the labels auto applied by our label classification bot.

These issues would then show up in the TODO column and the person doing triage could move them to the appropriate column

**Comment by jlewi** [comment]
kubeflow/Issue-Label-Bot#2 due this as part of the issue label bot.

**Comment by jlewi** [comment]
Looks like there is a GitHub app we could probably use already to do this.
https://github.com/philschatz/project-bot

**Comment by jlewi** [comment]
Installed project-bot on kubeflow/community and kubeflow/testing repositories.
For testing

Will we run into issues with the fact that our projects are org level?

**Comment by jlewi** [comment]
Looks like there are some issues getting this to work.
https://github.com/philschatz/project-bot/issues/9

**Comment by jlewi** [comment]
It would be great if someone could try this out either on their personal repo or on a kubeflow repo to see if we can get it to work for us. I think it would be super-helpful to triage issues.

**Comment by gaocegege** [comment]
I think the feature is really helpful. I can take a look.

**Comment by gaocegege** [comment]
I created a fork https://github.com/gaocegege/project-bot for https://github.com/apps/project-bot-for-orgs. After the test, I think we can support org-level projects but I am not sure why the original app does not support it. Maybe the config of the app is missing.

But, the app has limited support for adding new cards. Maybe it is better to maintain a new app for kubeflow community. We may want to add some custom commands rather than add_issues or add_prs.

**Comment by jlewi** [comment]
@gaocegege So you built an app from your fork? Did you make any changes? 

Did you verify that the official version of the app doesn't work?

> But, the app has limited support for adding new cards. Maybe it is better to maintain a new app for kubeflow community. We may want to add some custom commands rather than add_issues or add_prs.

What is the limitation for adding new cards? 

I think the functionality we'd like is as follows

* Someone files an issue
* The issue is labeled "Bug"
* The issue is automatically added to the TO DO column in the bug project

Does that work today?

**Comment by gaocegege** [comment]
@jlewi 

> Did you verify that the official version of the app doesn't work?

The upstream code itself can work. But I cannot use it for my org. But after I fork and run the code in another app with right permissions, it can work.

> What is the limitation for adding new cards?

It only supports add_issue and add_pr. If it works for us, then we do not need to update the code.

> Does that work today?

No, it only supports adding cards when there is new issues or prs. Labels only can be used to move the cards from one column to another. We cannot let the bot add the card when the label is added.

If we want it, we need to update the code.

**Comment by jlewi** [comment]
Thanks @gaocegege. If it doesn't support adding issues to when labels are added then I don't think it provides us the functionality we need most.

In that case, I think it makes the most sense to add that functionality to our existing label bot.
https://github.com/kubeflow/code-intelligence/blob/f8ccf35ceea09a35d00142627864651d21365ee7/Issue-Label-Bot-v1/flask_app/app.py#L163

@gaocegege Any interest in picking that up?

**Comment by gaocegege** [comment]
I can have a look if it is not in high priority (I may not have much time for it these days)

**Comment by jlewi** [comment]
@gaocegege Not super high priority but any help is certainly appreciated.

**Comment by jlewi** [comment]
Update:
We have defined criterion for whether an issue needs triage
https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md

We have code for computing whether an issue needs triage based on these criterion and adding it to the appropriate project
https://github.com/kubeflow/code-intelligence/blob/master/py/issue_triage/triage.py

We currently run this as a batch job.

We'd like to automatically trigger this whenever an issue changes (i.e. labels or projects change). There are two ways we could do this

1. GitHub Actions
1. A GitHub web app

Creating a GitHub action might be nice. One idea would be to define a GitHub Action workflow that looks like the following

1. Fetch labels and projects for an issue
1. Run some code which returns labels and kanban boards to add or remove from the list
1. Apply changes to labels and kanban boards

All of the business logic is in the 2nd step. Ideally for steps 1 and 2 there would be existing GitHub actions that we could reuse for many different use cases.

This way we could reuse the business logic.

I looked but didn't quite see an action that would allow us to add/remove an issue from a Kanban board closest I could find was.
https://github.com/marketplace/actions/github-project-automation

**Comment by hamelsmu** [comment]
@jlewi this is definitely doable, I would like to take a crack at it.  Some questions:


1.  Can you flesh out this a bit more: `whenever an issue changes (i.e. labels or projects change).` what do you mean by project change? - is that a repo change?  Is it possible to list all the triggers?

2. Can you tell me the recommended way to use `triage.py` in terms of the entry point, etc.?  

3. Which repo should I start on, and can I get admin access to that repo so I can test out the Action?

Thanks

**Comment by jlewi** [comment]
Thanks @hamelsmu 

* Our triage [process](https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md) defines a set of conditions that must be true for an issue to be considered triaged

  * The conditions are basically conditions on the set of labels and projects that an issue must have

* When the following events occur we want to run a check to see whether an issue needs triage or not because these events will affect whether it needs triage or not

    * Issue is created
    * Issue is closed
    * Labels added/removed
    * Issue added or removed from projects

* If an issue needs triage it should be added to the needs triage process
* Once the triaged conditions are satisfied the issue should be removed from the needs triage project

* In terms of entrypoint; I think this might be even simpler then I thought given how the code is written

* The [notebook](https://github.com/kubeflow/code-intelligence/blob/master/Issue_Triage/notebooks/triage.ipynb) has a section for how to triage a single issue  its basically just the following lines of code

   ```
    triager = triage.IssueTriage()
    url = "https://github.com/kubeflow/kubeflow/issues/1583"
    issue_info = triager.triage_issue(url)
   ```

  *  The code uses the environment variable GITHUB_TOKEN to get a credential that allows updating the project

* So I think we just need to use something like python-fire to create an entrypoint that invokes that code and then we can build a Docker container and create a 1 step GitHub Action Worklfow

**Comment by jlewi** [comment]
@hamelsmu made you an admin on kubeflow/testing. You are also an admin on code-intelligence. So you can use those repos for testing.

**Comment by hamelsmu** [comment]
Just to confirm my understanding:

When one of the triggers occurs that you outlined above, all that we need to do is run the following code?

```py
triager = triage.IssueTriage()
triager.triage_issue(url)
```

Is that it?  Or am I missing something?  If that is the case I can do this fast

**Comment by hamelsmu** [comment]
@jlewi I believe we are 90% done.  I have some additional questions in [this pr](https://github.com/kubeflow/code-intelligence/pull/59)

**Comment by jlewi** [comment]
@hamelsmu   regarding https://github.com/machine-learning-apps/kubeflow-triage

1. The project ID card is currently hard coded https://github.com/kubeflow/code-intelligence/blob/ef8c8f863c3830b555068b5ad2ad15dba0dd42b2/py/issue_triage/triage.py#L28

    * But if you expose that as environment variable to allow configuration via GitHub Actions then we could just put that in the GitHub action workflow

1. Instead of baking the code into the docker image; could we just have a wrapper script that clones the repo and then invokes the code from the repo?

   * This way we don't have to rebuild images to pick up any changes.

**Comment by hamelsmu** [comment]
It’s best to have the code for the Action to be used across all your repos to be defined in its own repo for various reasons.  Having all other workflows clone that repo and build an image to run the code every time from scratch will consume lots of compute and may cause you to run short of your free tier 

I refactored the code so that the project card is not hard coded if you look at the Action that is an input variable.

**Comment by jlewi** [comment]
Once #59 is merged I think the follow on work before we close this issue is

1. Update the community proposal with instructions for how to enable the GitHub action on a repo
    * https://github.com/kubeflow/community/blob/master/proposals/issue_triage.md
1. Enable the action on the kubeflow/kubeflow & kubeflow/website repos
1. Move the docker images into the Kubeflow docker-hub organization
    * https://github.com/kubeflow/code-intelligence/issues/66

**Comment by hamelsmu** [comment]
> The project ID card is currently hard coded https://github.com/kubeflow/code-intelligence/blob/ef8c8f863c3830b555068b5ad2ad15dba0dd42b2/py/issue_triage/triage.py#L28

Note this is only hardcoded when you don’t use the Action when you use the action we grab this value from the ENV variable

**Comment by jlewi** [comment]
Successful run on kubeflow/kubeflow
https://github.com/kubeflow/kubeflow/commit/0050623ff9843ca0ae32d995d0e396873bcf6df6/checks?check_suite_id=330176524

Issue that was successfully added to the needs triage Kanban board
https://github.com/kubeflow/kubeflow/issues/4530

**Comment by hamelsmu** [comment]
Should this issue be closed?

**Comment by jlewi** [comment]
Yes.
