### ISSUE TITLE
Do we need the status check "require branches to be up to date before merging"

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#28]
We currently use the status check "Require branches to be up to date before merging"

I think this pretty much means as soon as one PR for a repository is merged every other PR for the repo needs to be resync'd.

This seems impractical and a major pain point.

I think we can probably drop this.

I'm guessing that if tide tries to merge a PR and there are conflicts it will fail?

I think the downside of disabling this check is that presubmits aren't testing the merged code so presubmits could pass but postsubmits could fail.

The constant rebasing seems like a major drag on velocity so I think we should get rid of it.

tide will rerun the presubmits. I wonder if there's a way when tide reruns the test to run the tests on the merged code.

What do others think?

/cc @BenTheElder @krzyzacy @DjangoPeng @ddysher

**Comment by jlewi** [comment]
I disabled the check on kubeflow/kubeflow
Consider it an experiment.

**Comment by BenTheElder** [comment]
> I'm guessing that if tide tries to merge a PR and there are conflicts it will fail?

*our* presubmits always merge PRs into master locally when testing, and tide / prow should be aware of the commits supplied to the test jobs -- AFAIK we only merge if the latest commits were tested, but this does rely on your Prow jobs actually testing ht right commits.
