### ISSUE TITLE
Create an issue triage schedule and one-off training

### ISSUE THREAD

**Issue by theadactyl** [kubeflow/community#286]
Can we create a schedule (calendar or otherwise) for issue triage rotation with templates for metrics, etc, we want people to collect.

Also, might be good to have a one-off 30 minute meeting to walk potential volunteers through the issue triage process.

**Comment by scottilee** [comment]
I'm happy to help with triaging. Please let us know when you've sent out the invite as I think a meeting would be a good idea to understand guidelines and current processes.

**Comment by jbottum** [comment]
Scott - we are setting up a call for Monday.    What is your email ?  Please uni-cast back to me.   Josh.bottum@arrikto.com

**Comment by theadactyl** [comment]
Josh can you let me know what you have planned? I'd like to invite the
wider community in case there are more potential triagers. let's do this a
bit more programmatically.

**Comment by hamelsmu** [comment]
Linking this related issue here: https://github.com/kubeflow/community/issues/278
