### ISSUE TITLE
List participants

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#29]
We should have a page that lists all the companies/organization that are participating and contributing to Kubeflow.

Here's an initial list

CaiCloud,
Canonical, 
CoreOS, 
Google, 
Project Jupyter, 
Red Hat, 
Seldon, 
Weave,

/assign @aronchick

**Comment by gaocegege** [comment]
http://stackalytics.com/?project_type=kubernetes-group&release=all&metric=commits

I think https://github.com/openstack/stackalytics is a good reference.

**Comment by gaocegege** [comment]
We have the member list in YAML, then could we close the issue?
