### ISSUE TITLE
v0.7 blog post

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#294]
Opening this issue to track the blog post for 0.7.

@jbottum has created a draft blog post.

/assign @jbottum

**Comment by sarahmaddox** [comment]
Do you have a link for the draft blog post?

**Comment by jbottum** [comment]
Here is the current link.

https://docs.google.com/document/d/13fv-D0m40v1ugE1Pt8kXe0T7xA5MSS1yno3dUK732r8/edit#

**Comment by sarahmaddox** [comment]
Thanks @jbottum Please would you change the "Docs KANBAN" link in the table to the following:
https://github.com/orgs/kubeflow/projects/33

**Comment by theadactyl** [comment]
Published here:  https://medium.com/p/1e63036c07b8/
