### ISSUE TITLE
Setup kubeflow.org domain

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#3]
We need to setup the kubeflow.org domain.

The domain was purchased by @DjangoPeng and Caicloud and contributed to the community. Thank you very much.

The domain has been transferred to Google Domains to facilitate setup.

Current owners:
@DjangoPeng (CaiCloud)
@jlewi (Google)
@aronchick (Google)

There were a bunch of custom resource records defined
![custom_resource_records](https://user-images.githubusercontent.com/777219/35976116-ed804acc-0c93-11e8-9e48-8903070b69e7.png)

These look like vestiges of using the original domain registrar. @DjangoPeng  can we delete these?

**Comment by jlewi** [comment]
@DjangoPeng I think the MX records are configuring the domain to use namecheap for email; I'd like to get rid of those and switch to using gsuite.

**Comment by DjangoPeng** [comment]
@jlewi LGTM.

Please go ahead.

**Comment by jlewi** [comment]
gsuite is enabled; admins

@DjangoPeng (CaiCloud)
@jlewi (Google)
@aronchick (Google)
@mattf (Red Hat)

**Comment by jlewi** [comment]
The domain is all setup.
