### ISSUE TITLE
[Front-end] Creation of a new repo for Shared UI Components

### ISSUE THREAD

**Issue by avdaredevil** [kubeflow/community#309]
## About
As MLMD Lineage work is maturing, we wanted to migrate the components to a shared repository so these lineage components could be imported as shared dependencies between KFP and KF Metadata, without code duplication.

This will eventually extend to further code sharing of cross-codebase front-end configs or dev tools.

Ideal name `shared-components`

### Meta
/area metadata
/area front-end
/priority p0
/assign @avdaredevil
/cc @kwasi @jlewi

**Comment by jlewi** [comment]
@avdaredevil the name `shared-components` seems overly generic. I assume this is only for frontend related components? Can you suggest a name to that effect; maybe

* kubeflow-frontend

Is this repository only for metadata related components?

Suppose we have reusable widgets say for namespace selection; would that also go in this repo?

**Comment by avdaredevil** [comment]
Hi @jlewi, perhaps `frontend-components`?

Currently the only scope is for lineage components, but the intention is for this to be a shared repository for all full stack resources.
- this would include namespace-selector if we chose to export that as a shareable component
- Or global lint rules that can be enforced across code bases

**Comment by jlewi** [comment]
@avdaredevil did you consider just putting the shared components in a directory in an existing repository? e.g. kubeflow/kubeflow?

I don't have a strong oppinion either way. The main advantage of reusing kubeflow/kubeflow is that you avoid some of the maintenance costs of maintaining an additional repository; e.g. setting up prow jobs for E2E tests.

If the folks working on the front end are willing to take that on then I'll go ahead and create the repo.

Here are instructions to give you some idea of what you would need to do.
https://github.com/kubeflow/community/blob/master/repository-setup.md

Should we shorten the name to just frontend?

**Comment by jlewi** [comment]
@avdaredevil and @kwasi I went ahead and created kubeflow/frontend so if you think having a separate repo is worth the maintenance costs and you are willing to shoulder those you can go ahead and start using it. Otherwise we can just archive it.

**Comment by avdaredevil** [comment]
Hi @jlewi, thanks for setting it up. Just for context:
- We did consider using an existing repo, but unfortunately, since the intention of this repository is to be able to be installed via `npm` we need all these files to be in one repo (with a package.json)
- A standalone library procedure would look something like (assuming internal name in package.json is `kf-frontend-components`)
  >
  **_Installation_**
  ```shell
  npm install -S https://github.com/kubeflow/frontend
  ```
  **_Usage_**
  ```js
  import {LineageView, ArtifactType, ...} from 'kf-frontend-components/MLMD'
  ```

**Comment by jlewi** [comment]
Thanks @avdaredevil
