### ISSUE TITLE
Document Repository Setup

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#31]
Now that we have multiple repositories in the GitHub org we should standardize and document how repositories should be configured.

Background
kubeflow/community#22
kubeflow/tf-operator#433

Some things to cover
* Setting up Prow and basic tests
* Per  kubeflow/community#22 we don't want GitHub to require pull request reviews because we will rely on prow and tide to merge PRs based on /lgtm & /approve
* Reviewable should not be configured as a status check because this blocks tide (kubernetes/test-infra#7140)

**Comment by gaocegege** [comment]
I think it should be in high priority since the docs in tf-operator is outdated and the users may be puzzled.

**Comment by jlewi** [comment]
@gaocegege Which docs? Why would users be affected by repository configuration?

**Comment by gaocegege** [comment]
@jlewi Not the config, I mean that the README in tf-operator is outdated. For example, we have no master now but the README is not updated. If we have docs repository we could put all docs in one repo and there is no consistency problem between different repos.

**Comment by jose5918** [comment]
I'll take this since I just started the process of setting up the PyTorch repo

**Comment by jose5918** [comment]
Still working on it https://github.com/kubeflow/testing/issues/72, but will finish documenting once I get through all the rough spots and actually have a fully set up repo.

**Comment by jlewi** [comment]
Some additional things we should document [here](https://github.com/kubeflow/community/issues/53#issuecomment-378329912)
