### ISSUE TITLE
Document process for contributing to the Kubeflow Blog Post

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#316]
We need to do a better job 

1. Documenting the process for submitting/contributing a blog to Kubeflow
1. Documenting reviewers/approvers for Kubeflow blogs posts

We currently have this [Google Doc](https://docs.google.com/document/d/1b-k_Y9cl9-7pOCdbd5tEJX8LRRAkodtopioFma1WvLs/edit) but its a bit outdated.

* All blog posts are now in medium; we don't use the website anymore for blog posts.

I suggest

* We convert the Google doc to a markdown doc and check it into the community page
* We take a stab at updating the process on how people can get their blog posts reviewed and approved
* We link to it from the contributing guide on the website

/cc @elviraux @terrytangyuan @theadactyl @jbottum

**Comment by terrytangyuan** [comment]
@jlewi Thanks for creating this issue to track!

> All blog posts are now in medium; we don't use the website anymore for blog posts.

Is this why https://github.com/kubeflow/website/tree/master/content/blog (found in the Google doc) doesn't work anymore?

**Comment by jlewi** [comment]
Yes; that is why the link no longer works

**Comment by terrytangyuan** [comment]
@theadactyl @jlewi I just sent you an email on a new blogpost. Let's try publish it on Medium first. We can also test the rest of the process (such as checking into community page) once the documentation is updated.

**Comment by jlewi** [comment]
It looks like we have both a 

1. A Kubeflow publication https://medium.com/kubeflow
1. A kubeflow medium account - which is linked to the kubeflow twitter account 
    * This is listed as an editor of the Kubeflow publication

It looks like we currently have a bunch of editors of the kubeflow publication but not any writers.

I think ramachandrank@google.com has indicated he would be willing to help administer the blog post; so we probably need to make him an editor.

**Comment by jlewi** [comment]
@jbottum @StefanoFioravanzo Since you are asking about the blog. I think there are two paths forward

1. Wait for @ramachandrank to get back from vacation
1. Find ways to administer the blog so we don't get blocked when @ramachandrank goes on vacation.

I'm unclear whether or not we can allow non-Googlers to do the final approval of the blog post. However, even if we need a Googler to push the final button there's probably a lot we can do to reduce the toil and build redundancy.

* We need a process for collecting approvals from the subject matter experts (SME)
   * How do we publish drafts so that we can collect LGTMs from SME
* Does medium's permission model allow people to get blogs ready for posting without granting them the ability to publish the final blog?

**Comment by jlewi** [comment]
A GitHub issue template might be a great way to standardize the process for submitting a blog post and driving it to conclusion.

**Comment by terrytangyuan** [comment]
@jlewi Would a PR template be better for that so people can mark any required items as well as in-line comment/review for the content of the blog post? 

> Does medium's permission model allow people to get blogs ready for posting without granting them the ability to publish the final blog?

Yes, people can submit their blog for publication under Kubeflow's Medium account and then editors can choose whether to publish the final blog.

**Comment by jlewi** [comment]
@terrytangyuan What would the contents of the PR be?

**Comment by terrytangyuan** [comment]
@jlewi The PR contains the content of the blog post so that SMEs can write in-line comments. It might be good to also check-in the blog posts as markdown docs one of the Kubeflow repos since we may not use Medium forever and at some point we may need to migrate old posts to new platform. Just my two cents thinking long-term.

**Comment by jlewi** [comment]
@terrytangyuan Checking in blog posts as PRs would be useful for reviews but I'm not sure how well that works with medium. Can you write medium posts in markdown?  Looks like you might be able to: https://www.producthunt.com/posts/markdium; We use to publish blog posts on website by checking in PRs but we decided to switch to medium.

**Comment by terrytangyuan** [comment]
I haven't used markdium so cannot comment on its usability. Another option is to post blog somewhere on our website and then use Medium's [story import functionality](https://medium.com/p/import) to import it to Medium. I used it when I worked on [the MPI Operator blog post](https://medium.com/kubeflow/introduction-to-kubeflow-mpi-operator-and-industry-adoption-296d5f2e6edc). Sometimes manual edits are needed but the efforts should be low. 

Medium is an okay option for now and seems mainstream but one concern I always have is that a reader can only read limited number of Medium articles per month unless paying $5 per month so sometimes our content may not reach Kubeflow audience.

**Comment by jlewi** [comment]
I would suggest we scope this issue to figuring out the process around medium. Switching to a different blogging platform is a bigger undertaking.

**Comment by hamelsmu** [comment]
👋  Hello Community I would love to propose a solution for writing blogs in a free, transparent way that can go through code reviews on GitHub, and as a bonus can convert Jupyter Notebooks directly to blog posts (In addition to markdown).  

See [fastpages](https://github.com/fastai/fastpages), it is a project developed with the [fastai](https://github.com/fastai) community and has been battle-tested by thousands of users and is one of the most popular blogging platforms in the data science community.

I am the lead developer of fastpages and would be happy to assist and or support the Kubeflow community directly.  I think fastpages will solve many of the problems discussed on this thread.  Please let me know your thoughts!  

cc:/ @aronchick @T-Holland

**Comment by hamelsmu** [comment]
Oh and I forgot to mention, I'm happy to come to an upcoming community meeting to demo fastpages to everyone if that is helpful (unless the README and documentation, etc has convinced you enough already!).   Thank you

**Comment by jlewi** [comment]
Should we setup a kubeflow repo for fastpages? We could potentially use this in addition/alternative to our medium blog to see how well it works for us. We could potentially serve it at "blog.kubeflow.org" or "fastpages.kubeflow.org".

**Comment by hamelsmu** [comment]
@jlewi thats a good idea.  If you want to try it out just follow the instructions on the README to setup a new repo template

**Comment by jlewi** [comment]
@terrytangyuan @jbottum @StefanoFioravanzo WDYT? Is it worth it to create a copy of the fastpages repo so we can start experimenting with it? 

I think fastpages has two huge advantages

1. We can manage blog posts through git
1. We can publish notebooks

I think the latter is a huge difference from what we have today with medium and previously using hugo and netlify.

Using notebooks would make it very easy to include code in our blog posts and eventually add automation to ensure the code doesn't break.

**Comment by terrytangyuan** [comment]
Sounds good to me. The fact that a reader can only read limited number of Medium articles per month if not paying is really concerning to me. So I am leaning towards a different platform.

**Comment by jbottum** [comment]
@jlewi Fastpage seems to have some advantages.  Can you provide a view on who will be in the approval process from a Google standpoint and how long a typical approval process will take (...from a clean post submission) ?   i.e. is 5 days a reasonable target for google approvals ?

**Comment by jlewi** [comment]
@jbottum fastpages vs. medium doesn't change who would have to review a blog. fastpages would only change the mechanics of the review process i.e. git. That might speed up the review process because its well understood and we know how to automate it.

**Comment by jlewi** [comment]
I created the fastpages repo we need to finish setting it up though kubeflow/fastpages#2

**Comment by hamelsmu** [comment]
@jlewi Yeah man I'm interested

**Comment by jlewi** [comment]
@hamelsmu I'm so excited about fastpages and blog.kubeflow.org ; I can't wait to try it out for blogs written using notebooks.

Regarding guidelines and documenting the process; now that blogs are just submitted .md or .ipynb files I think we can file the standard GitHub review process.

As noted [above](https://github.com/kubeflow/community/issues/316#issuecomment-651274211) I think we want to identify to sets of reviewers

* Subject matter experts (SMEs)
* Googler who gives the final sign off

Maybe we should just create a [pull request template](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) with these guidelines?

**Comment by terrytangyuan** [comment]
@hamelsmu @jlewi Looking great! Excited to see this is making progress. Our GSoC student is interested in trying this out as well (created https://github.com/kubeflow/blog/issues/8 to track and discuss further).

**Comment by hamelsmu** [comment]
I added preliminary instructions on the process in https://github.com/kubeflow/blog/pull/9

Please review

**Comment by terrytangyuan** [comment]
What should we do with Medium then?

**Comment by hamelsmu** [comment]
We can migrate all the Medium posts like I did with @terrytangyuan 's post as an example

What do you think @jlewi ?   We should probably get some opinions first from the community and not rush into it

**Comment by jlewi** [comment]
> What do you think @jlewi ? We should probably get some opinions first from the community and not rush into it

+1 For now lets let people choose medium or fastpages. If people stop using medium then we can figure out how to turn it down.

**Comment by terrytangyuan** [comment]
Agreed.

**Comment by jlewi** [comment]
Thanks @hamelsmu  for creating: https://github.com/kubeflow/blog/blob/47396ab365b2e7b89e3454500014b4bec1463347/README.md#blog-submission-instructions

We need to create an OWNERs file in the root of the repo with the folks that can approve PRs.

**Comment by hamelsmu** [comment]
@jlewi do you want to create this file?    Is there anything you want me to do?

**Comment by jlewi** [comment]
@hamelsmu nothing for you to do.

@jbottum at @terrytangyuan should we add a doc say
https://github.com/kubeflow/community/tree/master/how-to

pointing people at the right places?

**Comment by theadactyl** [comment]
hi all, was there a resolution on the doc topic? Should we finalize the recommendation and documentation in the next community meeting?

**Comment by terrytangyuan** [comment]
@theadactyl The process is now in place and there's instruction in the README of this repo: https://github.com/kubeflow/blog

**Comment by jlewi** [comment]
Thanks @terrytangyuan

**Comment by theadactyl** [comment]
Thanks!
