### ISSUE TITLE
[Process/Tools] needed to follow up with area owners about issues

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#324]
We need a process or tools to ensure that area owners are responding to issues in a timely fashion.

Right now the triage process assigns area labels to issues. But we have no follow up to ensure that the area owners are following up on those issues.

@jtfogarty Any thoughts?

**Comment by jbottum** [comment]
we have 12 weeks in a sprint, maybe we talk about 10 issues per Community call.  User, PM, Eng should agree on P0, P1, etc. and if in/out or need more info

**Comment by jtfogarty** [comment]
I like @jbottum 's idea but it depends on the area owners attending the meetings.  Do we have a doc that maps areas to owners?
