### ISSUE TITLE
[Slack] Process for channel creation

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#326]
We should define a process for creating and administering slack channels.

Previously anyone could create a channel and that was leading to an explosion in number of channels (77 I think). I don't know that having all these channels was doing anyone any good.

**Comment by jlewi** [comment]
@karlschriek Do you want to investigate this since you want to create a channel for model management?

What permissions would you need to create channels?

How would people go about requesting you create channels when they need one?

**Comment by eterna2** [comment]
I think we can create a slack bot (which is linked to a repo) to create channels.

Pple can just make a PR to a slack repo. CI will trigger to create a channel using the slack API. 

https://api.slack.com/methods/conversations.create

**Comment by mameshini** [comment]
I can help with managing Slack channels.  My Slack id is https://kubeflow.slack.com/team/UAN46K11N
@Igor Mameshin (igor@agilestacks.com)

I can monitor this repo and discussions list for requests to create a new channel.  The goal is to use existing channels as much as possible and create new ones as appropriate.

**Comment by jlewi** [comment]
Thanks @mameshini I made you a workspace admin. Can you figure out a place to document somewhere how people would go about requesting new channels?

**Comment by jlewi** [comment]
Maybe create a folder "slack" and add an OWNERs file and put the docs there?

**Comment by mameshini** [comment]
Sounds good, I will create a "slack" folder.  We can use it to document the process for requesting new channels, Slack Guidelines, and add the OWNERS file.  I will take a stab at creating the initial version of Slack Guidelines.

**Comment by terrytangyuan** [comment]
We created a new channel #wg-training for the new Training WG that we just established. However, it seems like the channel can only be private. Would any of you be able to change it to public?

**Comment by terrytangyuan** [comment]
Just realized the documentation is already in place: https://github.com/kubeflow/community/tree/master/slack

Thanks @mameshini! I'll reach out to you via DM.

**Comment by terrytangyuan** [comment]
This can be closed now. Thanks @mameshini! 

/close
