### ISSUE TITLE
kfp-tekton-api 

### ISSUE THREAD

**Issue by animeshsingh** [kubeflow/community#336]
/kind feature

Need a new repo called "kfp-tekton-api", and seeded with initial kubeflow pipeline code (using a kubeflow bot, to neutralize any contributions counted twice et all). This will act as a staging repo for folks working together to get kfp-tekton compiler output now integrated in the backend to work with kfp api and ui.

**Comment by jlewi** [comment]
@animeshsingh What do you mean by staging repository? Could you please provide a little bit more explanation of how you see code being divided among the different repositories.

**Comment by animeshsingh** [comment]
@jlewi plan is to rename the kfp-tekton project to kfp-tekton-compiler, as a standalone python project. If someone needs a KFP DSL/Python interface for Tekton, can be used independently, and can be leveraged independently by taking the compiled out to Tekton directly.

kfp-tekton-api, or maybe a better name is kfp-tekton-backend is going to be the project essentially taking the compiled output, and plugging it in KFP engine, which is turn will talk to Tekton. Hence we need the base code seeded from kubeflow pipeline master, and then start plugging the Tekton code in.

**Comment by jlewi** [comment]
@animeshsingh Seems reasonable to me. As a matter of formality can one of the other OWNERs in 
https://github.com/kubeflow/kfp-tekton/blob/master/OWNERS (so @Tomcli @ckadner ) LGTM the creation of the new repository as well and the desired name.

**Comment by Tomcli** [comment]
Sounds good.
LGTM

**Comment by jlewi** [comment]
https://github.com/kubeflow/kfp-tekton-backend
