### ISSUE TITLE
What to do about kubeflow-incubator GitHub Org

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#338]
There is a second GitHub Org 
https://github.com/kubeflow-incubator

This is not currently used for anything.
More importantly its not administered/owned by the same people who own and operate the Kubeflow GitHub org.  This org is missing some of the protections we have setup on the kubeflow GitHub org e.g.

1. Ensuring there are multiple admins to ensure we don't loose access
1. Managing it declaratively  and transparently using GitOps and peribolos
1. CLA checks

A couple options 

1. Do we just delete it? Possibly transferring any repositories to the kubeflow GitHub org?
1. Do we manage it the same way as the kubeflow GitHub org

There is a non trivial cost to administering a GitHub org. So my preference would probably to stick with a single GitHub org until we have need for multiple GitHub orgs.

/cc @gaocegege

**Comment by terrytangyuan** [comment]
+1 to delete it but possibly transferring some of the repos to Kubeflow org. However, since there were no CLA checks, this might not be trivial to do.

**Comment by gaocegege** [comment]
Agree to delete it since maintaining a second org has huge cost and we do not see the benefit.

**Comment by gaocegege** [comment]
I think we can deprecate these projects in the incubator since ppl at Alibaba do not maintain it now.

**Comment by jlewi** [comment]
https://github.com/kubeflow-incubator/charts
* Doesn't look like there is actually in this repo so I think we can just delete it.
* @gaocegege Do you want to just delete it?

https://github.com/kubeflow-incubator/gen
* This looks like a fork of kubernetes-client/gen
* @jetmuffin do we still need this fork? looks like last commit was 2018

https://github.com/kubeflow-incubator/genspec
* We could transfer this to kubeflow/kubeflow and then archive it

**Comment by gaocegege** [comment]
https://github.com/kubeflow-incubator/charts

We can delete it.

**Comment by jetmuffin** [comment]
[https://github.com/kubeflow-incubator/gen](https://github.com/kubeflow-incubator/gen)

yep, we only modified  some parameters to swagger and scripts in this repo, I think we can delete it and just re-fork from master if needed.

[https://github.com/kubeflow-incubator/genspec](https://github.com/kubeflow-incubator/genspec) 

Agree to archive this repo : )
