### ISSUE TITLE
DevStats to track velocity for Kubeflow

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#34]
Kubernetes has a great set of dashboards for velocity related metrics
https://k8s.devstats.cncf.io/d/44/time-metrics?orgId=1&var-period=w&var-repogroup_name=Kubernetes&var-repogroup=kubernetes&var-apichange=All&var-size_name=All&var-size=all&var-full_name=Kubernetes

There are dashboards for things like
PR time to LGTM
# approvers/# reviewers
https://k8s.devstats.cncf.io/d/38/reviewers?orgId=1

It would be great to get the same metrics for Kubeflow.

**Comment by jlewi** [comment]
Here's the code behind that
https://github.com/cncf/devstats

**Comment by ScorpioCPH** [comment]
@jlewi That's great!

**Comment by gaocegege** [comment]
That is awesome!

**Comment by jlewi** [comment]
@lukaszgryglicki I created a postgres database and I ran gha2db to load the data from my repo into it.

Is it possible to run a simple query e.g dump a time series of number of PRs per day? I tried using runq to run some of the sql files in util_sql/top_unknowns but I'm not sure what arguments to provide and I keep getting segfaults.

**Comment by lukaszgryglicki** [comment]
First you need to run query in `psql`.
To count commits/day you can count push events
See `gha_events` table.
Select type = 'PushEvent' and group by `created_at`

util_sql/top_unknowns.sql contains "macros":
- {{ago}}
- {{lim}}

So to run it, you must provide replacements.
Correct command would be for example:
- `PG_PASS=your_password PG_DB=dbname ./runq util_sql/top_unknowns.sql {{ago}} '1 month' {{lim}} 10`:

```
root@devstats:~/go/src/devstats# PG_PASS=<<redacted>> PG_DB=gha ./runq util_sql/top_unknowns.sql {{ago}} '1 month' {{lim}} 10
2018-04-18 06:54:38 /runq: /------------------+--------+---\
2018-04-18 06:54:38 /runq: |actor             |actor_id|cnt|
2018-04-18 06:54:38 /runq: +------------------+--------+---+
2018-04-18 06:54:38 /runq: |rdcastro          |241302  |216|
2018-04-18 06:54:38 /runq: |jonyhy96          |33408569|189|
2018-04-18 06:54:38 /runq: |k82               |18107181|172|
2018-04-18 06:54:38 /runq: |wking             |209920  |164|
2018-04-18 06:54:38 /runq: |theopenlab-ci[bot]|33714816|156|
2018-04-18 06:54:38 /runq: |ymqytw            |2589105 |151|
2018-04-18 06:54:38 /runq: |justaugustus      |567897  |141|
2018-04-18 06:54:38 /runq: |zhaoxpZTE         |15881573|140|
2018-04-18 06:54:38 /runq: |Steve53           |13792782|133|
2018-04-18 06:54:38 /runq: |grayluck          |4760200 |133|
2018-04-18 06:54:38 /runq: \------------------+--------+---/
2018-04-18 06:54:38 /runq: Rows: 10
2018-04-18 06:54:38 /runq: Time: 590.562158ms
root@devstats:~/go/src/devstats# 
```

**Comment by lukaszgryglicki** [comment]
BTW: computed time series are in the `influx` database.
Postgres database contains all data that I can get from GitHub archives (GHA).

**Comment by lukaszgryglicki** [comment]
So I have a green light to setup DevStats instance for Kubeflow (and to create good documentation during doing so).
All I need now is a root access to some server where I can set up everything.
After I set up everything you change the root password and/or remove my SSH access keys so I cannot use it anymore.

@jlewi

**Comment by jlewi** [comment]
That's fantastic. If you send me the email associated with your google account; I can give you access to the GKE cluster and GCP project where we'd like to deploy this.

**Comment by lukaszgryglicki** [comment]
lgryglicki@cncf.io
I wa sthinking about bare metal server.
I have no knowledge (yet) how to deploy stuff on the cluster.
You can talk with me on slack or skype: "lukaszgryglicki"

**Comment by jlewi** [comment]
We used to run postgres on K8s for Airflow. This is how we did

1. Instructions for creating a [PD](https://github.com/kubeflow/tf-operator/blob/e2b13e09c6cab08ae9b990f6e7f05826ac02e567/test/test-infra/airflow/README.md#one-time-setup)
1. [K8s Deployment](https://github.com/kubeflow/tf-operator/blob/e2b13e09c6cab08ae9b990f6e7f05826ac02e567/test/test-infra/airflow/deployment.yaml) to deploy postgres in a container backed by PD on the cluster.

**Comment by jlewi** [comment]
Which slack channel? (We use kubeflow.slack.com)

**Comment by lukaszgryglicki** [comment]
Kubernetes then #devstats - you can pm me.

**Comment by jlewi** [comment]
So here's my guess of what we need to do

1. Create PD's for postgres and influx DBs
1. Create a Deployment for postgres
1. Create a Deployment for influx DB
1. Create a Docker image with Devstats code
1. Create K8s jobs to run the devstats scripts
   - structure  to setup postgres DB
   - ./grafana/influxdb_setup.sh to setup ingress db
  - gha2b to load the data into postgres
1. A deployment for grafana

**Comment by lukaszgryglicki** [comment]
I can't probably help with that :-(
We already discussed this on DevStats repo and it was decided that I shouldn't work on porting DevStats to K8s yet.
@jberkus started some work about this, I can only help with bare metal deployment.

If you are interested in this, there are tiny packets servers that will be able to handle that.
Unless @dankohn want me to dive into K8s porting.

**Comment by jlewi** [comment]
No problem. Thanks for all the great work on devstats; looks fantastic.

**Comment by lukaszgryglicki** [comment]
For k8s you can ask @jberkus for bare metal - I can create the instance for you, for me helping with k8s version of devstats - I need a green light from @dankohn.

**Comment by jlewi** [comment]
@lukaszgryglicki does the outline provided above make sense though? Was there anything obvious I missed.

Thanks for the offer. I think I'd prefer to deploy it on K8s even if that means setting it up ourselves. I think longer term that will be easier to manage and I don't think it will be that hard to convert to K8s.

**Comment by lukaszgryglicki** [comment]
My knowledge about K8s deployments is quite limited by I can see the following componentes:
- One grafana instance per project (N pods)
- One postgres database per project + logs instance (N + 1 pods) (it will also have cron jobs for DB backups)
- One influx instance per project (N pods)
- One or N instances of devstats tools (why? we can either have one running all sync jobs one after another, just like the bare metal does now, or [better imho] one instance per each project) (N or 1 pod(s)) - this will include cron job imho
- Current DevStats also has "webhook" tool that manages CI and CD (continuous integrations/deployment) - not sure if we want the same tool in k8s deployment, if so then it looks complex at first glance.

**Comment by jlewi** [comment]
Do we need to run some binary regularly to execute the queries and load the data into influxdb? Is this handled by the [devstats binary](https://github.com/cncf/devstats/blob/master/cmd/devstats/devstats.go)

**Comment by lukaszgryglicki** [comment]
`devstats` binary calls all other binaries correctly, actually this is all that it does.
All other binaries are here to allow the user to execute parts of the workflow manually or in the special mode.
Most of the switches are described in `context.go` and all binaries are listed in `Makefile`.

**Comment by lukaszgryglicki** [comment]
Binaries that are called by `devstats` are:
- `structure`
- `gha2db`
- `db2influx`
- `z2influx`
- `gha2db_sync`
- `annotations`
- `idb_tags`
- `get_repos`
- `ghapi2db`
Some other binaries that can be used manually, but are not called by `devstats`:
- `runq`
- `import_affs`
- `idb_backup`
- `webhook`
- `merge_pdbs`
- `idb_vars`
- `replacer`
- `pdb_vars`
- `idb_tst`
- `sqlitedb`

**Comment by jlewi** [comment]
Will devstats create the database's if they don't already exist? If not is there an option to automatically run the setup scripts that will create the DBs but only if they exist?

Can we just start devstats and leave it running in order to periodically get the latest data? Or do we need to invoke it from a cron job?

**Comment by lukaszgryglicki** [comment]
- Devstats will not create the database, initial setup is described in ADDING_NEW_PROJECT.md
- If there are no databases at all, automatic deploy scripts will currently fail, they're added after we had - say 15-16 projects out of current 22.
- I've worked today on automatic deploy on ARMv8 but this work is not yet ready.
- So currently the situation is that if we already have some projects, we can add new ones totally automatically by using CD (continuous deploy) and "[deploy]" message in the commit on the production branch. The script executed is "devel/deploy_all.sh" - but again - it won't handle initial state when there is nothing yet. Sorry :-( this is a bare metal binary not set of k8s pods yet.

- Devstats can be used to automatically sync everything but it needs to run every hour from the cron job, see examples and comments in `crontab.entry` file.

**Comment by jlewi** [comment]
@lukaszgryglicki @jberkus so I have devstats running and I'm definitely getting data into the postgress database. I'm not sure though if data is making into influx though. Any suggestion how to test?

I'm a little confused about how to setup grafana. I looked at the instructions [here](https://github.com/cncf/devstats/blob/master/INSTALL_UBUNTU17.md) but its not clear to me how we configure GRAFANA to access the postgres and influx databases.

**Comment by lukaszgryglicki** [comment]
You can SSH into Influx container and see.
Locally this is done via:
- `influx -host localhost -username gha_admin -password ... -database gha`.
And the for example:
- `show series` or `select * from annotations`.

I've just Installed Ubuntu 18.04-beta.2 in the VirtualBox and will be testing automatic deploy when there is no single database set up yet.

Grafana requires apache to proxy https. Https is enabled when you have server DNS name using Let's encrypt.
You will probably need something simpler, like no apache proxy and no HTTPS at the beginning, just Grafana over HTTP.
Some info about installation is here: https://github.com/cncf/devstats/blob/master/GRAFANA.md but it probably needs to be heavily modified.

I'll create install docs for Ubuntu 18.04 using automatic deploy with minimal configuration possible.

**Comment by jlewi** [comment]
Thanks.

I think for K8s (and possibly non K8s deployments) it would be helpful to have two scripts (one for postgres and one for influxdb) that I could run on startup that would check whether each database was initialized and if not initialize it. This would eliminate the manual steps right now.

**Comment by jlewi** [comment]
@lukaszgryglicki How do I backfill influxdb? I'm only seeing time series data from 04/16 onwards. I think this is because I originally ran devstats with projects.yaml configured to a start date of 04/14. I backfilled  the postgres database by running gha2db.

**Comment by lukaszgryglicki** [comment]
I would use `shared/reinit.sh` script.

**Comment by jlewi** [comment]
Using reinit.sh worked. The time series data is complete.

**Comment by jberkus** [comment]
@jlewi realistically I won't be looking at the kube deployment until after KubeCon and Red Hat Summit, mid-May.  At that point I'll be happy to pitch in on whatever you've started.

Database initialization really isn't hard, you just tie creating a database directory (initdb for postgres) together with creating the empty database.   That way if the database is started you can assume it's also ready.

Grafana is really the hard part in all this, because it's not designed to run in a container.

**Comment by lukaszgryglicki** [comment]
Actually, Grafana ran in a container some time ag in DevStats.
there are container builds of Grafana AFAIK.
I've added new installation doc, that describes how to set up projects just from the point when there are no databases yet.
This is just a single command call with many ENV variables set.
It finally worked from really zero to full deployment of two projects on a VirtualBox and Ubuntu 18.04-beta.2
This is the document I've created: https://github.com/cncf/devstats/blob/master/INSTALL_AUTO_DEPLOY.md

**Comment by lukaszgryglicki** [comment]
No other data sets.
You should ssh into the container with Influx and just do show series/few selects there
You can take Grafana's dashboards to see the actual query to the Influx DB and then try to do it manually.
Really no idea what happened, I would say that you don't have data in the influx instance or maybe some permissions issue....

**Comment by jlewi** [comment]
Thanks. So here's the activity query from Grafana

```
SELECT /^[[repogroups]]$/ FROM "repo_group_activity_[[period]]" WHERE $timeFilter
```

It looks like this query is parameterized by fields that are settable via Grafana. Do you know if there's an easy way to get the actual query for a given set of UI settings?

**Comment by jlewi** [comment]
Looks like I'm missing repo_group_activity

```
> show series
key
---
all_prs_merged_d
all_prs_merged_d12
all_prs_merged_d2
all_prs_merged_d3
all_prs_merged_d4
all_prs_merged_d7
all_prs_merged_h
all_prs_merged_h12
all_prs_merged_h2
all_prs_merged_h3
all_prs_merged_h4
all_prs_merged_h7
all_prs_merged_w
all_prs_merged_w2
all_prs_merged_w3
all_prs_merged_w4
company_all_activity_d
company_all_activity_d7
company_all_activity_w
company_all_authors_d
company_all_authors_d7
company_all_authors_w
company_all_comments_d
company_all_comments_d7
company_all_comments_w
company_all_commit_comments_d
company_all_commit_comments_d7
company_all_commit_comments_w
company_all_commits_d
company_all_commits_d7
company_all_commits_w
company_all_contributions_d
company_all_contributions_d7
company_all_contributions_w
company_all_contributors_d
company_all_contributors_d7
company_all_contributors_w
company_all_issue_comments_d
company_all_issue_comments_d7
company_all_issue_comments_w
company_all_issues_d
company_all_issues_d7
company_all_issues_w
company_all_prs_d
company_all_prs_d7
company_all_prs_w
company_all_review_comments_d
company_all_review_comments_d7
company_all_review_comments_w
episodic_contributors_all_contributors_d
episodic_contributors_all_contributors_w
episodic_contributors_all_prs_d
episodic_contributors_all_prs_w
episodic_issues_all_contributors_d
episodic_issues_all_contributors_w
episodic_issues_all_issues_d
episodic_issues_all_issues_w
events_h
issues_age_all_all_median_d
issues_age_all_all_median_d7
issues_age_all_all_median_w
issues_age_all_all_number_d
issues_age_all_all_number_d7
issues_age_all_all_number_w
issues_age_all_p0_median_d
issues_age_all_p0_median_d7
issues_age_all_p0_number_d
issues_age_all_p0_number_d7
issues_age_all_p1_median_d
issues_age_all_p1_median_d7
issues_age_all_p1_median_w
issues_age_all_p1_number_d
issues_age_all_p1_number_d7
issues_age_all_p1_number_w
issues_age_all_p2_median_d
issues_age_all_p2_median_d7
issues_age_all_p2_number_d
issues_age_all_p2_number_d7
issues_age_all_p3_median_d
issues_age_all_p3_median_d7
issues_age_all_p3_number_d
issues_age_all_p3_number_d7
issues_closed_d
issues_closed_d7
issues_closed_w
issues_opened_d
issues_opened_d7
issues_opened_w
new_contributors_all_contributors_d
new_contributors_all_contributors_w
new_contributors_all_prs_d
new_contributors_all_prs_w
new_issues_all_contributors_d
new_issues_all_contributors_w
new_issues_all_issues_d
new_issues_all_issues_w
new_prs_all_d
new_prs_all_d3
new_prs_all_d7
new_prs_all_w
new_prs_all_w3
new_prs_all_w7
non_author_all_median_w
non_author_all_percentile_15_w
non_author_all_percentile_85_w
num_stats_all_companies_d14
num_stats_all_companies_d7
num_stats_all_companies_w4
num_stats_all_developers_d14
num_stats_all_developers_d7
num_stats_all_developers_w4
num_stats_all_unknowns_d14
num_stats_all_unknowns_d7
num_stats_all_unknowns_w4
opened_to_merged_all_median_d
opened_to_merged_all_median_w
opened_to_merged_all_percentile_15_d
opened_to_merged_all_percentile_15_w
opened_to_merged_all_percentile_85_d
opened_to_merged_all_percentile_85_w
pr_comments_median_d
pr_comments_median_d7
pr_comments_median_w
pr_comments_percentile_85_d
pr_comments_percentile_85_d7
pr_comments_percentile_85_w
pr_comments_percentile_95_d
pr_comments_percentile_95_d7
pr_comments_percentile_95_w
prs_age_all_median_d
prs_age_all_median_d3
prs_age_all_median_d7
prs_age_all_median_w
prs_age_all_median_w3
prs_age_all_median_w7
prs_age_all_number_d
prs_age_all_number_d3
prs_age_all_number_d7
prs_age_all_number_w
prs_age_all_number_w3
prs_age_all_number_w7
prs_approve_state_approved_d7
prs_approve_state_approved_w
prs_approve_state_awaiting_d7
prs_approve_state_awaiting_w
prs_authors_all_d
prs_authors_all_d3
prs_authors_all_d7
prs_authors_all_w
prs_authors_all_w3
prs_authors_all_w7
repo_commenters_all_d
repo_commenters_all_d3
repo_commenters_all_d7
repo_commenters_all_w
repo_commenters_all_w3
repo_commenters_all_w7
repo_comments_all_d
repo_comments_all_d3
repo_comments_all_d7
repo_comments_all_w
repo_comments_all_w3
repo_comments_all_w7
reviews_per_user_all_d
reviews_per_user_all_d7
reviews_per_user_all_w
reviews_per_user_kubeflow_community_d
reviews_per_user_kubeflow_community_d7
reviews_per_user_kubeflow_community_w
reviews_per_user_kubeflow_examples_d
reviews_per_user_kubeflow_examples_d7
reviews_per_user_kubeflow_examples_w
reviews_per_user_kubeflow_experimental_kvc_d
reviews_per_user_kubeflow_experimental_kvc_d7
reviews_per_user_kubeflow_experimental_kvc_w
reviews_per_user_kubeflow_hp_tuning_d
reviews_per_user_kubeflow_hp_tuning_d7
reviews_per_user_kubeflow_hp_tuning_w
reviews_per_user_kubeflow_kubeflow_d
reviews_per_user_kubeflow_kubeflow_d7
reviews_per_user_kubeflow_kubeflow_w
reviews_per_user_kubeflow_pytorch_operator_d
reviews_per_user_kubeflow_pytorch_operator_d7
reviews_per_user_kubeflow_testing_d
reviews_per_user_kubeflow_testing_d7
reviews_per_user_kubeflow_tf_operator_d
reviews_per_user_kubeflow_tf_operator_d7
reviews_per_user_kubeflow_website_d
reviews_per_user_kubeflow_website_d7
reviews_per_user_kubeflow_website_w
time_metrics_all_median_open_to_merge_d
time_metrics_all_median_open_to_merge_d7
time_metrics_all_median_open_to_merge_w
time_metrics_all_percentile_85_open_to_merge_d
time_metrics_all_percentile_85_open_to_merge_d7
time_metrics_all_percentile_85_open_to_merge_w
```

**Comment by jlewi** [comment]
So it looks like one problem is that gha_repos is empty.

I ran the following query to update that table

```
update gha_repos set repo_group = 'kubeflow', alias= 'kubeflow' where org_login in ('kubeflow');
```

I'll file a bug to run it periodically.

**Comment by jlewi** [comment]
I reran devstats and now influx db shows the following time series

```
repo_group_activity_d
repo_group_activity_d7
repo_group_activity_h24
repo_group_activity_m
repo_group_activity_q
repo_group_activity_y
repo_group_commits_d
repo_group_commits_d7
repo_group_commits_h24
repo_group_commits_m
repo_group_commits_q
repo_group_commits_y
```

**Comment by jlewi** [comment]
Looks like a bunch of data is still missing
```
> SELECT kubeflow FROM "repo_group_activity_d"
name: repo_group_activity_d
time                 kubeflow
----                 --------
2018-04-19T00:00:00Z 169
```

Lets try rerunning shared/reinit.sh

Note: Running reinit.sh complains about missing ` 'open ./metrics/shared/idb_vars.yaml: no such file or directory'

I just created an empty file and that seemed to work.

**Comment by jlewi** [comment]
So the timeseries now looks to have all the data.

```
> SELECT kubeflow FROM "repo_group_activity_d"
name: repo_group_activity_d
time                 kubeflow
----                 --------
2018-01-29T00:00:00Z 21
...
2018-04-19T00:00:00Z 169
```

**Comment by jlewi** [comment]
Grafana is complaing

```
pq: relation "metric_table" does not exist
```

**Comment by jlewi** [comment]
I manually edited the influxdb query in Grafana to be

```
SELECT kubeflow FROM "repo_group_activity_[[period]]" WHERE $timeFilter
```

That worked.

So the problem appears to be that Grafana isn't properly updating

**Comment by jlewi** [comment]
So it looks like the problem was that the dashboards are using [Grafana variables](http://docs.grafana.org/reference/templating/) whose value is supposed to be populated from influxdb. But when I imported the dashboards I must set the data source incorrectly because it was trying to read the data from the postgre data which didn't work as a result I was getting the error "template variables could not be initialized".

I edited the dashboard via the UI and that fixed things.

Now I just need to figure out how to load all the json files defining the dashboards into Grafana.

**Comment by jlewi** [comment]
@jberkus @lukaszgryglicki Is there a script I can use to create dashboards from all the json files in a directory? If the dashboards already exist I'd like them to be overwriten.

**Comment by jlewi** [comment]
See grafana/grafana#10052

Looks like we can configure Grafana to load dashboards from a directory.

**Comment by jlewi** [comment]
Found some helpful [instructions](https://github.com/aerogear/proposals/blob/dac71073deaa442727c4989f028a15e66aee88f1/metrics/prometheus-metrics-endpoints-and-auto-discovery.md#default-visualisations) about how to configure Grafana to load dashboards from files in conjuction with a config map.

**Comment by lukaszgryglicki** [comment]
In my case, I was copying grafana.db file from the test server to another server.
And then I could update dashboards using `cmd/sqlitedb` tool.
See scripts: in `devel/*sqlite*`
Unfortunately, `sqlitedb` tool cannot import new JSONs atm, it only supports updating.
I'll try to add such a feature.

Postgres variables are created by `pdb_vars` tool (see `devel/pdb_vars_all.sh`), Influx variables are created by `idb_vars` tool (see `devel/idb_vars_all.sh`), they both have yaml configuration in pdb.yaml/idb_vars.yaml.

**Comment by jlewi** [comment]
Thanks.  I ended up configuring Grafana to load dashaboards from files. I store the dashboards in a config map so its super easy to update them (just ks apply).

/cc @jberkus

**Comment by lukaszgryglicki** [comment]
OK great.

**Comment by ant31** [comment]
@jlewi have deployed devstat on k8s? is there any resources/source code to re-use of your deployment ?

**Comment by gaocegege** [comment]
@ant31 I think you can find the artifacts here: https://github.com/kubeflow/community/tree/master/devstats

**Comment by ant31** [comment]
@gaocegege  great, thanks !
