### ISSUE TITLE
Additional community call (zoom) hosts needed

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#341]
We need additional people to host community meetings. We can only give 1-2 additional people permission to use the kubeflow zoom account and access the recordings.

Current admins are listed here
https://github.com/kubeflow/community/blob/master/how-to/kubeflow_assets.md#zoom

* What is the minimum permission needed to host zoom calls and access the recordings?
* Existing [process](https://github.com/kubeflow/community/blob/master/how-to/community_meetings.md)
   *  Doc is outdated

Expectations for anyone who volunteers

* You are willing to host KF meetings 
* You are willing to sort out and document the process around doing this

/cc @animeshsingh

**Comment by lalithvaka** [comment]
@jlewi, I can definitely help out as needed. Please grant me access. I will start with all the community zoom meeting recordings posted to the drive as well as the notes document. 
/cc @animeshsingh

**Comment by jlewi** [comment]
@lalithvaka Could you do me a favor and look up the zoom permission model and tell me what level of access you think you need? Fewer priveleges is better.

**Comment by lalithvaka** [comment]
@jlewi Per what I can see, you just need to invite me as a member with my email ID (lalith.vaka@gmail.com) and I should be able to access the cloud recordings if available. Also, each meeting thats scheduled, you can enable settings to add one or more members as host(s) - below screenshot.
![image](https://user-images.githubusercontent.com/8292387/84460379-a0809880-ac1e-11ea-8748-5ffb532b606b.png)

You can also enable auto record all meetings if they are not enabled
![image](https://user-images.githubusercontent.com/8292387/84460495-eccbd880-ac1e-11ea-882a-ac521d53149f.png)

Let me know if you need any additional info. There is a custom role(s) you can create, but not much of a use in this context. I do not have a paid zoom account to see if there are any settings / limits we can do beyond this.

**Comment by jlewi** [comment]
@lalithvaka Thanks! I've sent you an invite can you please accept.

I also added @rmgogogo 

@lalithvaka  could you 

1. Send me a PR updating the assets page
1. Update the page describing how we manage zoom

Any thoughts on how we should rotate and manage who hosts a particular meeting?

**Comment by lalithvaka** [comment]
@jlewi Thanks for sending the invite. What I realized now, is that with member privileges, all I would be able to do is host the meeting if an admin adds me as an alternative host to specific meeting series. Unfortunately I can not view the recordings unless they are scheduled by me or I get admin role. [Zoom Ref](https://support.zoom.us/hc/en-us/articles/205347605-Managing-cloud-recordings).  

If you grant me an admin role, I would be able to view / download and post the recordings to Community meetings team drive. 

I also need to be granted access to [ Community meetings team drive](https://drive.google.com/drive/u/2/folders/150C-v6Hb8gtPZMucyd_65ozyCiY50zFD) to my lalith.vaka@gmail.com.

**Comment by jlewi** [comment]
Please read: https://github.com/kubeflow/community/blob/f83d7281bd6e2869865145147fff3f16e2238089/how-to/sharing_docs.md
To figure out how to get access drive

I don't think I can change your membership type; I removed you and then added you back (so you'll have to reaccept the invite).

I'm only an admin.

I think the owner @ewilderj might need to change your account type to admin to grant you admin access

After you accept the invite; can you see whether you can start meetings using the KF community number?

**Comment by jlewi** [comment]
@lalithvaka Now that Google Meet is free; would that be easier then using zoom?

**Comment by 8bitmp3** [comment]
@jlewi I was just going to ask about that - https://www.blog.google/products/meet/bringing-google-meet-to-more-people/

We have been using Google Hangouts and now—Google Meet—for TensorFlow-related design meetings. There is no 40-minute limit like in the free Zoom video chat but we stick to 60 mins max.

@krishnadurai I think we just got cut off from the KF on-prem Zoom as soon as the limit was mentioned. Shall we explore Google Meet but have a policy of 1 hour max? (Meetings can also be recorded.)

**Comment by jlewi** [comment]
@8bitmp3 With Google Meet how are video recordings managed? Are the automatically uploaded to gdrive?

**Comment by 8bitmp3** [comment]
@jlewi from what I understand, they're managed by the host (at least one of the Googlers) and then stored on a GDrive with a link shared on a public Doc. May I introduce you to @ematejska and @dynamicwebpaige, who have hosted and are hosting awesome TensorFlow meetings. Maybe you can speak to them internally @ Google. 🙌

**Comment by lalithvaka** [comment]
Had the same question, I could not find the recording option in the free version(as individual). Unless GSuite is free to Googlers who are managing opensource projects.

**Comment by krishnadurai** [comment]
@8bitmp3 I vote for Google Meet if we are able to add multiple hosts to the meeting.

**Comment by 8bitmp3** [comment]
@krishnadurai while recording may not be available right now—I think some Google-led ones may need to be reviewed for content before being released—we can do our best maintain the notes in the doc(s) like in some other SIGs. If you need assistance, I can be a co-host for KF on-prem, as the time zone allows it. cc @jlewi

**Comment by krishnadurai** [comment]
Sure we could look to have you as a co-host.

**Comment by jtfogarty** [comment]
I'm available in helping host the community meetings (weekly community as well as the On-Prem)

**Comment by animeshsingh** [comment]
I believe between @jlewi @lalithvaka @jtfogarty this seems nicely covered.

**Comment by jlewi** [comment]
@jtfogarty What is your email so I can send you a zoom invite.

Per @lalithvaka 's comment above It looks like there's still some issue figuring out the right permissions to allow @lalithvaka and @jtfogarty to be able to host meetings.

I'm not the OWNER so I don't think I can make other people admins.

@ewilderj is the OWNER

**Comment by lalithvaka** [comment]
Thank you @jlewi. 
@ewilderj , can you please add my self (lalith.vaka@gmail.com) as well as @jtfogarty (j.007ba7@gmail.com) as admin users on the Zoom account so that we could help out in posting recordings to GDrive as well as host community meetings as needed? Thank you.

**Comment by animeshsingh** [comment]
As a backup - add [my email ](animation2007@gmail.com)as well. I can take up the duties on a need basis if regular hosts aren't available

 cc @ewilderj @jlewi

**Comment by jlewi** [comment]
@lalithvaka and @jtfogarty I added both of you; @jtfogarty your invite is pending please accept.

@lalithvaka Are your permissions enough to host the community meeting? Are you able to start the meeting for the community call?

@animeshsingh we ran out of licensed users so I couldn't add you.

**Comment by lalithvaka** [comment]
@jlewi , I am currently listed as a member. With this access, I can be invited as an additional host under the advanced settings of the meeting invite. Once I(or @jtfogarty ) get added as an additional host, we probably could host the community meetings(Never tested). Please see the reference screenshot on how to add additional host [here](https://github.com/kubeflow/community/issues/341#issuecomment-643040977). 
With member access, we will not be able to download zoom recordings unless we get an admin access.

**Comment by jlewi** [comment]
Thanks @lalithvaka I'm not the owner of the meeting so I don't think I can add you as hosts; I think the room/meeting is owned by @ewilderj  so we'll have to ask him after the long weekend.

**Comment by jlewi** [comment]
Google [meet pricing](https://apps.google.com/meet/pricing/?utm_source=google&utm_medium=cpc&utm_campaign=na-US-all-en-dr-skws-all-all-trial-b-dr-1009156&utm_content=text-ad-none-any-DEV_c-CRE_435199693897-ADGP_Hybrid+%7C+AW+SEM+%7C+BKWS+~+BMM+//+Google+Meet+//+Google+Meet-KWID_43700053724035182-aud-983735361597:kwd-299210509137&utm_term=KW_%2Bgoogle%20%2Bmeet-ST_%2Bgoogle+%2Bmeet&gclid=CjwKCAjwr7X4BRA4EiwAUXjbtwPXsr9fRz_hqFG14IzyjJVTXXED2GkTbWczuLNeqR2e_41mD5ryYBoCts8QAvD_BwE&gclsrc=aw.ds)

I did some quick experiments with Google meet and it looks like we would have the following problems

1. Someone with a @kubeflow.org email would need to start the meeting
1. Anyone without an @kubeflow.org meeting needs to "ask to join" and then be let in. 
    
The 2nd of those seems like the biggest issue. We've had meetings with 50+ people.

**Comment by jlewi** [comment]
@jtfogarty @animeshsingh @jtfogarty @jbottum I think I've hosted enough community meetings and would like to pass the baton to someone else. I will host the 07/21 and 07/28 meetings but after that someone else will need to take over. 

It looks like whoever takes this on needs to accomplish the following

1. Figure out an appropriate rotation
1. Figure out an appropriate video conferencing solution
    * Per the discussion on the thread I think we need to stop using the existing zoom call (https://zoom.us/j/799749911) because we can't scalably manage permissions
1. Get the calendar invite updated

**Comment by jlewi** [comment]
cc @cliveseldon @yuzisun @ellistarn @neuromage @paveldournov @elikatsis @vpavlin @yanniszark @Jeffwan @krishnadurai @terrytangyuan @gaocegege @andreyvelich @johnugeorge @aronchick @stefanofioravanzo @elviraux @kimwnasptd @krazyhaas

**Comment by jtfogarty** [comment]
Hi Jeremy, 

Josh and I are talking about this.  

We should be ready for the August 4th meeting.

Does anyone happen to know what other open source communities use for video conferencing?

**Comment by terrytangyuan** [comment]
TensorFlow community uses Google Meets/Hangout. Argo community uses Zoom.

**Comment by 8bitmp3** [comment]
@jlewi if the admins use macOS Catalina or above, screen recording with sound is pretty easy. One can use the built-in screenshot app/settings or QuickTime's video recording option. To capture audio in the video, install Blackhole via Homebrew (`brew cask install blackhole`) and then follow the official multi-output [setup](https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device).

**Comment by 8bitmp3** [comment]
> TensorFlow community uses Google Meets/Hangout. Argo community uses Zoom.

Also, TensorFlow community calls are hosted by Googlers, so they have full Google Meet features to host a meeting for 100+ people, record to GDrive, etc.

**Comment by jlewi** [comment]
@jtfogarty @jbottum Any update on this, can we get the calendar updated ahead of next week's meeting?

**Comment by jtfogarty** [comment]
I’ll update the calendar ASAP
