### ISSUE TITLE
Additional calendar admins needed

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#342]
We need additional admins for the [Kubeflow Calendar](https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com&ctz=America%2FLos_Angeles)

We currently have some partial tooling for managing the calendar. The [script](https://github.com/kubeflow/community/blob/master/scripts/calendar_import.py) configures the calendar based on [calendar.yaml](https://github.com/kubeflow/community/blob/master/calendar.yaml)

The script currently needs to be run manually by someone with admin privileges to the calendar.

Expectations for would be volunteers

* Figure out what needs to happen to gain access to the calendar
* Commit to helping SIGs/WGs/ etc... get meetings added to the calendar
* Document the process
* Work on automating the process to make it more scalable
* Move calendar.yaml into its OWN folder and create an OWNERs file
* Review and approve updates to the calendar

**Comment by 8bitmp3** [comment]
@jlewi Maybe we should also update the format/expand the community page https://www.kubeflow.org/docs/about/community/ and include a list of all SIGs in addition to the existing Slack channels with all the details about how people can participate. 

For instance, we could use something similar to https://www.tensorflow.org/community/ that leads to > https://www.tensorflow.org/community/forums > https://www.tensorflow.org/community/forums#special_interest_groups (there's a sense of flow).

Things are little fragmented right now but the users are growing, so it's all good, just an admin thing. Just got an email from Model Management SIG from @karlschriek - there's an issue with accessing the calendar. (I can help with all this later - right now there're things on https://github.com/kubeflow/website that require attention that I signed up for)

**Comment by jlewi** [comment]
@8bitmp3 maybe open a separate issue about that?

@karlschriek Are you willing to be a calendar admin?

**Comment by jlewi** [comment]
@karlschriek regarding your question in https://github.com/kubeflow/community/issues/342 

I believe the only ones with calendar access are myself and @theadactyl; @theadactyl and I can't afford to keep being the only ones administering the calendar. So before anything else gets added to the calendar we need to find 1-2 people willing to take on being a calendar admin.

**Comment by jtfogarty** [comment]
I'm happy to help out and be a calendar admin.

**Comment by jlewi** [comment]
Thanks @jtfogarty What's your Google account?

@scottilee also mentioned helping out with automating the calendar sync.

**Comment by jlewi** [comment]
@scottilee reopened kubeflow/community#274 to update sync'ing of the KF calendar.

**Comment by yuzliu** [comment]
I am happy to help after getting an internal approval from my company.

**Comment by jlewi** [comment]
Thanks @yuzliu 

@yuzliu and @karlschriek if your willing to help I think the first steps would be

1. Open up a PR moving calendar.yaml into its own folder and create an OWNERs file
1. Open up PR in https://github.com/kubeflow/internal-acls  to create `calendar-admins.members.txt` 
    * We will use this to create a google group to administer the calendar and add the emails of people who should
       have access

**Comment by karlschriek** [comment]
PRs openend:

https://github.com/kubeflow/community/pull/357
https://github.com/kubeflow/internal-acls/pull/277

**Comment by nicholas-abad** [comment]
I'd be happy to help out and be a calendar admin too!

**Comment by jlewi** [comment]
The group calendar-admins@kubeflow.org has been created and has the members listed in #304.

I have granted the group calendar-admins@kubeflow.org permission to make changes to events on the kubeflow calendar.

**Comment by karlschriek** [comment]
@jlewi officially we have additional calendar admins now, but most of us don't actually know how to update the calendar. Since https://github.com/kubeflow/community/issues/274 is still open it still needs to be done manually. I would actually prefer just taking on https://github.com/kubeflow/community/issues/274 getting the automation up and running, but also for that we would need access and instruction on what to do where. Could you or someone else fill us in?

**Comment by jlewi** [comment]
Closing in favor of #274.

I believe we will need to implement automation as I believe an @kubeflow.org account is needed and needs admin privileges on the calendar.

I believe when @james-jwu tried adding his account it didn't work.

**Comment by jlewi** [comment]
It looks like the issue with non kubeflow.org accounts was a permission setting.
 https://support.google.com/a/answer/60765

Specifically for secondary calendars we needed to modify the gsuite settings to allow editing of events by people outside the org.

**Comment by jlewi** [comment]
@jtfogarty @karlschriek @yuzliu Can you check whether you are able to edit the Kubeflow calendar now?

/cc @james-jwu @Bobgy

**Comment by jtfogarty** [comment]
@jlewi I have NOT able to add or modify they calendar from the webpage.  Did you want me to try to run the python script?
As a side note, the Tuesday 8AM pst meeting is no longer on the calendar.

**Comment by jlewi** [comment]
@jtfogarty Thanks for the info. I'm in the process of automating the syncs so no need to keep trying it.

Can you file a bug about the Tuesday community meeting? It looks like there might be something wrong with the config.
