### ISSUE TITLE
GitHub Discussions as a centralized KF community forum

### ISSUE THREAD

**Issue by 8bitmp3** [kubeflow/community#345]
As the community is growing, there's more and more stuff being discussed under Issues and on Slack channels. **GitHub Discussions** can potentially help. It should have some of the main features of Discourse—it's a message board/forum—which PyTorch and fast.ai use effectively to engage with the community And Discussions shouldn't need hosting, since it's already here on GitHub (unlike Discourse). And, it should be able to save history unlike the free version of Slack, which the Kubeflow community currently uses. 

Recent example: Google Brain's JAX team (cc @hawkinsp who is a maintainer there) https://github.com/google/jax/discussions. 

I assume there is/will be integration with Projects ("Trello"), PRs, Issues, since it's on GitHub already.

**What are you thoughts? 👍🙌👎🤔** Cheers

Related: 
- https://github.com/kubeflow/community/issues/326 by @jlewi about the Slack channel creation, maintaining/administering
- https://help.github.com/en/github/building-a-strong-community/about-team-discussions

**Comment by jlewi** [comment]
It looks like you enable discussions per repo.
I tried to enable it on kubeflow/kubeflow but got a 404 when I clicked setup GitHub discussions

**Comment by shawnzhu** [comment]
There are two features from GitHub about the idea of discussion:

1. Team discussion - available for github.com now, which is mentioned above 
1. GitHub discussion - Not available today, beta for public repository coming soon. new feature announced in GitHub universe in May 6th. see details from https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions and a live example: https://github.com/githubevents/satellite2020/discussions

I would vote for 2) but needs to wait until it's available.

**Comment by jlewi** [comment]
Before we turn on GitHub discussions; I would like to see some guidelines for when to use slack, mailing list, GitHub Issue, vs. GitHub discussion.

Lets use this thread to discuss and then we can add it to the contributor page.

**Comment by 8bitmp3** [comment]
> Before we turn on GitHub discussions; I would like to see some guidelines for when to use slack, mailing list, GitHub Issue, vs. GitHub discussion.
> 
> 
> 
> Lets use this thread to discuss and then we can add it to the contributor page.

There should be similar READMEs for Contributing in other projects where we can find some samples of we can borrow. I’ll do some searching and get back to you.

@jlewi Can I also introduce an idea of more active use of project management tools such as Github Project(s)? There are a bunch of stale issues such as this one I came across randomly because the stale[bot] has been busy sending notifications https://github.com/kubeflow/website/issues/1412 Project boards can help seeing the big picture and if folks can’t finish something they can de-assign themselves and ask for help.

For example, we already have a v1.1 board that’s quite active here https://github.com/orgs/kubeflow/projects/36. 

(This is related to v1.1 release too - including docs stuff - I think https://github.com/kubeflow/website/issues/1984)

For more info: https://help.github.com/en/github/managing-your-work-on-github/about-project-boards

> Project boards are made up of issues, pull requests, and notes that are categorized as cards in columns of your choosing. You can drag and drop or use keyboard shortcuts to reorder cards within a column, move cards from column to column, and change the order of columns.
>
> Project board cards contain relevant metadata for issues and pull requests, like labels, assignees, the status, and who opened it. You can view and make lightweight edits to issues and pull requests within your project board by clicking on the issue or pull request's title.

**Comment by jlewi** [comment]
@8bitmp3 Should we open a new issue to discuss the ufe of project management tools?

**Comment by 8bitmp3** [comment]
@jlewi would the KF backers be open to sponsoring a paid account to save the archives?

**Comment by jlewi** [comment]
@8bitmp3 I'm not sure what you are talking about; a paid account for what? What archives are you referring to?

**Comment by 8bitmp3** [comment]
@jlewi for Slack - doesn't it archive if you pay them?

**Comment by jlewi** [comment]
@8bitmp3 Slack's pricing model is prohibitively expensive because its per user $8 month. That ends up being about $36K per year  right now and would continue to grow as we get more users.

**Comment by 8bitmp3** [comment]
@jlewi $36k+ is a bit too much indeed.

Regarding:

> guidelines for when to use slack, mailing list, GitHub Issue, vs. GitHub discussion.

I am for the guidelines but also think intuitively people would head to Slack before realizing there's a page somewhere with the guidelines (like T&C, people may read it once and forget). And if there're probably no full-time moderators, it may get more complicated.

If the _habit_ is to go to a familiar platform to ask a question and folks use Slack, Discord or G Chat for other projects and/or at work, they'd go to Slack before an admin or a moderator - if there is one - would direct them to a relevant channel (Slack Channels, GitHub Issues/PRs, Google Groups, GitHub Discussions). 

So, Slack is good and familiar IMHO but also can be hard work because it's not structured and can be very noisy as more users join  it. Things are not split into subcategories and there's no archive.

With GitHub Discussions _in theory_ you'd have a channel to share information/ask questions that's also part of the GitHub Issues/PRs ecosystem. It is basically what Google Groups is/was designed for. (In Google Groups there's less noise and people who subscribe to KF-Discuss can read the messages in their own time by checking emails.) But with Google Groups, you need a Google account AFAIK and I'm not sure how actively maintained that platform is after they updated the general design (can it integrate with GitHub, which is a Microsoft product?)

> There are two features from GitHub about the idea of discussion:
> 
> Team discussion - available for github.com now, which is mentioned above
> GitHub discussion - Not available today, beta for public repository coming soon. This is a new feature announced in GitHub universe in May 6th. see details from https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions and a live example: https://github.com/githubevents/satellite2020/discussions
> I would vote for 2) but needs to wait until it's available.

Agree with @shawnzhu . We wait for the beta?

**Comment by shawnzhu** [comment]
@jlewi @8bitmp3 @pdmack if any org owner 👍 the idea of GitHub Discussion, I could try to ask GitHub for a beta.

**Comment by 8bitmp3** [comment]
> @jlewi @8bitmp3 @pdmack if any org owner 👍 the idea of GitHub Discussion, I could try to ask GitHub for a beta.

@shawnzhu yes please, thank you!

**Comment by shawnzhu** [comment]
FYI: GitHub Discussions is available for all public repositories now. see https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/#%e2%9c%a8-improved-daily-experience
