### ISSUE TITLE
Create kubeflow/experimental-pytorch

### ISSUE THREAD

**Issue by jose5918** [kubeflow/community#35]
Based on this proposal https://github.com/kubeflow/community/pull/33, we would like to create a repository to start working/experimenting with a pytorch operator.

**Comment by gaocegege** [comment]
I think we could create kubeflow/pytorch-operator, then we don't need to update the name of the repo in the future.

**Comment by jose5918** [comment]
Yeah either way sounds good to me. I just used this name for the issue because it was suggested on the proposal

**Comment by jlewi** [comment]
Created kubeflow/pytorch-operator.
@jose5918 I gave you admin access so you should be able to set it up.

Can you please set up the repo? As part of the repo can you create a doc covering the process of setting up a new repository kubeflow/community#31

Can you also make it abundantly clear in the README.md that its an experimental repo.

**Comment by jose5918** [comment]
Sure I will do that and make sure people are aware it's experimental

**Comment by gaocegege** [comment]
I think we could close the issue now.
