### ISSUE TITLE
Request to add KFP community meeting to KF community calendar

### ISSUE THREAD

**Issue by james-jwu** [kubeflow/community#359]
Folks in KFP community have been asking whether KFP community meeting can be added to KF community calendar. Jeremy suggested I open an issue for this request.

Our meeting times are every two weeks, alternating between Wed. 10am-10:40am, and 5:30pm-6:10pm. Today (07/08) we are having it at 5:30pm.

If cancellations or changes are necessary, I hope there is a process where the calendar events can be changed quickly.

**Comment by awcchungster** [comment]
+1

**Comment by krazyhaas** [comment]
+1

**Comment by karlschriek** [comment]
Is this still relevant? Seems pretty stale

**Comment by james-jwu** [comment]
This is already done. Closing.
