### ISSUE TITLE
Represent On Premise Working Group

### ISSUE THREAD

**Issue by krishnadurai** [kubeflow/community#363]
@jlewi @animeshsingh @jtfogarty I'm forking this discussion from #348 in order to keep both these discussions focussed.

@jlewi 's comment:
> @krishnadurai Are you asking because prospective leads for this working groups are missing from the set of folks I explicitly called out for feedback? I would defer discussion about specific WGs to subsequent issues/proposals. Prospective WGs are free to start issues or PRs to begin discussing their charter and other aspects.

@jtfogarty's comment:
> @jlewi Is this the proper place to suggest an On-Prem WG? I can be a point person @jtfogarty

The on-prem group has been functioning over the past year and has contributed numerous features to Kubeflow, by representing users of Kubeflow who install it in on-premise or bare-metal servers.

A few of the efforts which were ideated and implemented from this group include:

1. Parity of installation and features for Kubeflow in on-premise environments across releases.
2. Authentication and Authorization for non-cloud deployments, which need a generic solution.
3. Improving the security of Kubeflow images.

I recommend that we do keep this group functional, as a working group. This enables more users to adopt Kubeflow in an on-premise environment and seek the support of fellow users.

@animeshsingh 's comment:
> I would containing on-prem customization requests in Control Plane + Common Services WG. To me, there are different kinds of Cloud, on-prem being a variation of it.

This is certainly a proposal we could consider in order to have a WG represent the interests of on-premise users.

/cc @johnugeorge @ddutta @jbottum @yanniszark @lalithvaka @mameshini

**Comment by jlewi** [comment]
Thanks @krishnadurai 

What projects (i.e. code) would the WG own? 

Would the WG own a reference/vanilla distribution of Kubeflow?

**Comment by mameshini** [comment]
AgileStacks will contribute a set of kustomize scripts validated to deploy Kubeflow on existing on-prem Kubernetes clusters.  We are currently able to run Kubeflow 1.0 on upstream Kubernetes 1.16.  It includes deployment for Istio, Minio, Harbor, MySql, cert-manager, dex which require on-prem specific configurations.  This on-prem distribution of Kubeflow can be owned by the on-prem WG.

**Comment by animeshsingh** [comment]
@krishnadurai all the items you listed fall in one of those two categories, i.e. control plane, or common services

> Parity of installation and features for Kubeflow in on-premise environments across releases.
installation is Control Plane job, and some would use kfctl, some operator (e.g. IKS, OpenShift), some Juju charms (e.g. Ubuntu), some kpt/kustomize (Google...)

> Authentication and Authorization for non-cloud deployments, which need a generic solution.
Part if common services umbrella, Istio +Dex

> Improving the security of Kubeflow images.
Security should be a common service, with KF providing a base, but different providers, on-prem or cloud extending it for their needs

**Comment by krishnadurai** [comment]
@jlewi @mameshini mentions we intend to maintain a reference implementation for KF deployment. With respect to code ownership - we don't have independent components yet, though we might need to modify existing components for compatibility.

@animeshsingh I agree with the view that security can be a different entity - though it doesn't fit in the common service categorization. In turn, I'm not convinced of the common service terminology which I think should be merged with the control plane group.

On the thought of whether if on-premise can be represented by the control plane group, we need to consider modification of the control plane group's goals to be inclusive of these priorities:

1. Parity of installation and features for Kubeflow in on-premise environments across releases.
2. Authentication and Authorization for non-cloud deployments, which need a generic solution.
3. Improving the security of Kubeflow images.
