### ISSUE TITLE
Cancel outreach community meeting

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#364]
Attendance for the outreach meeting is pretty low < 10 people.
https://github.com/kubeflow/community/blob/49e849fa935558583a227ccad9eecf788715843d/calendar.yaml#L81

Should we cancel this meeting?

Especially now that we are forming WGs; maybe we should chann

/cc @elviraux @jbottum @jtfogarty @animeshsingh @theadactyl

**Comment by animeshsingh** [comment]
yes - can be discussed on main community calls if needed

**Comment by jbottum** [comment]
@aronchick @elviraux @pdmack @kkasravi Participation in the Kubeflow PM / Outreach calls is very low.   Outbound marketing of KF by the Community is low.   It appears that we may not have a PM Working Group.    I think this structure will impact our ability to grow the Community.   I am cautious to eliminate these calls without a replacement.

**Comment by jlewi** [comment]
@jbottum I have removed the call from the calendar for now. If someone would like to resume them they will needed to be added back to the calendar with a suitable host.
