### ISSUE TITLE
WG Sponsorship for Notebooks

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#379]
Per the governance discussions. All projects ultimately need to find WG sponsorship or they will eventually be archived.

This means the notebook infrastructure will need to find an appropriate WG to take ownership of related assets.

/cc @StefanoFioravanzo @kimwnasptd @vkoukis @yanniszark

**Comment by kimwnasptd** [comment]
@jlewi, @StefanoFioravanzo and I would be happy to take ownership for this.

**Comment by jlewi** [comment]
@kimwnasptd Which WG are you thinking? Are you planning on putting this under an existing WG or forming a new one?

**Comment by jlewi** [comment]
Closing this because the notebook work group has been formed.
