### ISSUE TITLE
WG Sponsorship PodDefaults controller

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#381]
Per our governance discussions all projects need to find WG sponsorship or they will be archived.

Opening this issue to figure out what to do about the PodDefaults admission hook.

It looks like PodDefaults currently has no owners:
https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook

cc @wdhorton @discordianfish

**Comment by StefanoFioravanzo** [comment]
Hi @jlewi . I want to mention both @yanniszark and @elikatsis who should be interested in driving this WG. They are on vacation now, so they will jump into the discussion as soon as they come back

**Comment by yanniszark** [comment]
I have experience with the PodDefault code, which I have extended for our use-cases:
https://github.com/kubeflow/kubeflow/pull/4317
As such, I can help review code and approve PRs.

**Comment by jlewi** [comment]
Thanks @yanniszark .  We still need to find WG sponsorship or else make alternative arrangements. The PodDefaults controller is probably insufficient to warrant its own WG.

Is there a Kubernetes SIG that might be a good candidate to take this on?

**Comment by thesuperzapper** [comment]
The PodDefaults controller (also known as `admission-webhook`) is owned by `wg-notebooks`
