### ISSUE TITLE
Kubeflow calendar was not updated with the new meeting

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/community#403]
I added AutoML WG meeting in this PR: https://github.com/kubeflow/community/pull/396.

Calendar doesn't seems to be updated with the new meetings: https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com.

@jtfogarty @karlschriek @nicholas-abad @yuzliu Is there any way to check logs from the [update script](https://github.com/kubeflow/community/blob/master/scripts/calendar_import.py) or understand why it is not updated ?

/cc @jlewi @Bobgy

**Comment by jlewi** [comment]
@andreyvelich the script is not run automatically. The calendar admins need to run the sync. Can you please update the docs to make this clear if it isn't already?

**Comment by andreyvelich** [comment]
@jlewi Sure, I will submit the PR.

**Comment by Bobgy** [comment]
@jlewi @james-jwu Can you help me understand how to set up the env to be ready for the script?
I installed some pypi packages and currently stuck at
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/gongyuan/secrets/kf-calendar.oauth_client.json'
```

How do I get this oauth_client.json?

**Comment by james-jwu** [comment]
I sync'd the calendar. @andreyvelich please verify.

@Bobgy I did it by creating the oauth json file. You can create oauth credential in one of you GCP projects.

**Comment by andreyvelich** [comment]
@james-jwu @Bobgy Thanks, now I can see the AutoML meeting in Kubeflow calendar.
