### ISSUE TITLE
Define process/templates for SIGs

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#409]
There are a couple proposals floating around for SIGs. These are coming up in contexts where we'd potentially like to establish a mechanism for collaborating around issues that cut across WGs and don't necessarily involve owning one or more repositories

Examples include

* On prem (cc @jtfogarty @lalithvaka )
* Data/Feature management (cc @woop)

This is what SIGs are for.

It looks like we haven't formalized the definitions and processes around formation of SIGs.

Kubeflow SIGs basically correspond to Kubernetes WGs. So we can start with
https://github.com/kubernetes/community/blob/master/committee-steering/governance/wg-governance.md
And just replace "WG" with "SIG".

Looking at Kubernetes; it looks like the same YAML file is used to define work groups and sigs.
https://github.com/kubernetes/community/blob/894d555ed3e675236b350081898f0a966a77ad14/sigs.yaml#L2699

**Comment by Bobgy** [comment]
@jlewi is there anything left for this issue?
Looks like we have formed a SIG already
