### ISSUE TITLE
8am Community Call Is Not Showing Up on the calendar beginning 09/15

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#411]
8am community meetings are no longer showing up.
https://calendar.google.com/calendar/u/0/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com&ctz=America/Los_Angeles

@jtfogarty

**Comment by jlewi** [comment]
calendar admins (@jtfogarty @karlschriek @nicholas-abad @yuzliu) could one of you please investigate and fix?

**Comment by jtfogarty** [comment]
@jlewi The yaml file has not changed in 18 days.  Can you rerun the job that pulls in the yaml and updates the calendar?  I don't know how to do this and I don't think I have permissions to either. Thanks

**Comment by jlewi** [comment]
@jtfogarty @Bobgy ran it and fixed the issue.
Moving forward I will not be running the calendar sync. Can you and the other calendar admins please look into either getting the permissions needed to run the sync or else automating the sync.
