### ISSUE TITLE
AutoML meeting doesn't have reminder

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/community#413]
[AutoML WG meeting](https://github.com/kubeflow/community/blob/master/calendar/calendar.yaml#L350-L365) was added by @james-jwu (ref: https://github.com/kubeflow/community/issues/403#issuecomment-683536291).
For some reason, this meeting doesn't have reminder in [Kubeflow community calendar](https://calendar.google.com/calendar/u/0/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com).

As I can see from the [script](https://github.com/kubeflow/community/blob/master/scripts/calendar_import.py#L57-L62), `popup` reminder should apply to every event.

@Bobgy Do you have any ideas why even [kubeflow-discuss](https://groups.google.com/g/kubeflow-discuss) group members don't receive notifications?

/cc @jtfogarty @jlewi @karlschriek

**Comment by jlewi** [comment]
I'm not a calendar admin; please work with the calendar admins to resolve this:
https://github.com/kubeflow/community/blob/master/calendar/OWNERS

**Comment by karlschriek** [comment]
Hi @andreyvelich does the popup work for other calendar events or does it in general not work?

**Comment by Bobgy** [comment]
It might be the same problem as [my comment here](https://github.com/kubeflow/community/pull/412#issuecomment-692634176).

My fix: log in as gongyuan@kubeflow.org, remove the invite to kubeflow-discuss@ first. Then fix permission issues and rerun the calendar sync script.

**Comment by andreyvelich** [comment]
> Hi @andreyvelich does the popup work for other calendar events or does it in general not work?

@karlschriek For other events it is working. I can see the problem only with the AutoML meeting.

**Comment by andreyvelich** [comment]
> It might be the same problem as [my comment here](https://github.com/kubeflow/community/pull/412#issuecomment-692634176).
> 
> My fix: log in as [gongyuan@kubeflow.org](mailto:gongyuan@kubeflow.org), remove the invite to kubeflow-discuss@ first. Then fix permission issues and rerun the calendar sync script.

@Bobgy Does it mean that after re-run script with correct permission invite should be sent to kubeflow-discuss?

**Comment by Bobgy** [comment]
@andreyvelich no, I think you need to first remove kubeflow-discuss and add it back by running the script.
(because simply running the script makes no change to invited people)

**Comment by andreyvelich** [comment]
@Bobgy I don't have access to run this script.
Can you help with it, please?

**Comment by Bobgy** [comment]
/assign
OK, I'll take a look soon

**Comment by Bobgy** [comment]
Sorry, I don't have enough time to take this investigation.
I remember some calendar admins have been granted calendar permissions, can they look into this?
/unassign

**Comment by andreyvelich** [comment]
@jlewi @jtfogarty  Do you have any ideas how we can fix it ?
Kubeflow discuss members still don't have invite for this meeting.
I believe Kubeflow community meeting has the same issue.

**Comment by jlewi** [comment]
Duplicate of #438
