### ISSUE TITLE
Can't run make generate for wgs.yaml

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/community#415]
Running `make generate` fails with the following error:
```bash
go run ./generator/app.go
Validating wgs.yaml
ERROR: sig-feature-store: has no subprojects
exit status 1
Makefile:12: recipe for target 'generate' failed
make: *** [generate] Error 1
```

cc @jlewi

**Comment by jlewi** [comment]
@kimwnasptd  @StefanoFioravanzo @thesuperzapper @elikatsis I don't think we can merge the notebooks WG #417 is fixed; so you might want to volunteer to fix this. I'm guessing its a simple fix to the go code to remove the check that sigs have subprojects.

**Comment by kimwnasptd** [comment]
@jlewi sure, looking into it.

Quoting Jeremy's [comment](https://github.com/kubeflow/community/pull/408#issuecomment-692396749) for more context wrt sigs and subprojects:
> Yes; SIGs don't own projects so they shouldn't have sub projects.

So the proposed solution I'll implement will be to change [this line](https://github.com/kubeflow/community/blob/abb090d9af844354ee1c71b93c58f713b3961ece/generator/app.go#L290) that expects a SIG to have subprojects.

**Comment by kimwnasptd** [comment]
I'm trying to understand when this broke to make sure that this issue will be resolved with the above fix.

@woop when you were preparing the PR for the `sig-feature-store` #408 how did you run the `make generate`?

**Comment by woop** [comment]
> I'm trying to understand when this broke to make sure that this issue will be resolved with the above fix.
> 
> @woop when you were preparing the PR for the `sig-feature-store` #408 how did you run the `make generate`?

Yea this is my bad. I was on my phone so I edited the PR directly using the UI.
