### ISSUE TITLE
Missing GitHub group kubeflow/wg-notebooks-leads

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#421]
@kimwnasptd @StefanoFioravanzo @elikatsis @thesuperzapper Could one of you create the PR to add the group please?

**Comment by kimwnasptd** [comment]
@jlewi what would this PR need to change? 
Is there any other similar PR for the other WGs so I can have an idea of what needs to be done?

**Comment by jlewi** [comment]
https://github.com/kubeflow/internal-acls/blob/be09e92e81692161f38fc46db0a21ea85d605e75/github-orgs/kubeflow/org.yaml#L999

**Comment by jlewi** [comment]
@kimwnasptd @StefanoFioravanzo @elikatsis @thesuperzapper could one of you please prioritize this? Without the group it is difficult to communicate with the leads effectively.

**Comment by thesuperzapper** [comment]
@jlewi I have created PR https://github.com/kubeflow/internal-acls/pull/358
