### ISSUE TITLE
calendar_import.py needs to handle pruning and generate unique ids

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#429]
According to @Bobgy calendar_import.py may not handle pruning. i.e. when we delete events from calendar.yaml we aren't actually deleting them from the calendar.

Per: https://github.com/kubeflow/community/issues/430#issuecomment-716782210 
I think we also want to generate the IDs automatically for the calendar events; maybe by hashing them?
This will avoid future problems caused by people reusing IDs for different events.

@karlschriek @jtfogarty @yuzliu  Does one of the calendar admins want to look into modifying calendar_import.py to support removing any events not defined in the YAML?

**Comment by karlschriek** [comment]
I could look at it as soon as the sa we created (https://github.com/kubeflow/community-infra/pull/22) has permission to edit the calendar.

**Comment by jlewi** [comment]
@karlschriek The calendar sync is fully automated now; So we just need to

1. Update calendar_import.py
1. Rebuild the docker image
1. Redeploy

**Comment by jtfogarty** [comment]
This is no longer needed since we are moving off the Kubeflow.org calendar onto individual SIG and WG calendars
If anyone needs help removing calendar items, please reach out to me.
Please close this issue.
