### ISSUE TITLE
Tuesday Community meeting isn't showing up in community calendar; calendar_import.py should not create a meeting if there is already a meeting with that id

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#430]
After the latest calendar sync's the tuesday meeting
https://github.com/kubeflow/community/blob/39e7498dd9c628bbb6dda25db55933171c5b0acf/calendar/calendar.yaml#L18

No longer shows up
https://calendar.google.com/calendar/u/0/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com&ctz=America/Los_Angeles

The script doesn't appear to be showing any errors

@jtfogarty and @karlschriek Can one of you take a look? 

P0 as we should try to get next week's meeting onto the books.

**Comment by jlewi** [comment]
@jtfogarty  @karlschriek  @nicholas-abad @yuzliu ping? This is P0 as we'd like to ensure the meeting is up to date before next week's meeting. Could someone try submitting a PR with a new meeting entry (i.e. same meeting details but new id).

**Comment by thesuperzapper** [comment]
Its almost certainly related to PR #412 

It caused two meetings to have the same id `kf029`, we should make it `kf002` again, and re-sync.

**Comment by jlewi** [comment]
Its showing up again. I'm not sure what happened.
I reran the script.

Looking at the logs. It looks on the last sync an error might have occurred while updating the calendar

```
 https://www.google.com/calendar/event?eid=a2YwMjlfMjAyMDA4MThUMTUwMDAwWiBrdWJlZmxvdy5vcmdfN2w1dm5ibjhzdWoyc2UxMHNlbjgxZDk0MjhAZw
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 34.82.252.86:8132: connect: connection refused"
```

I'm not sure why that would have caused the meeting to disappear though. It looks like one problem is that we don't periodically rerun the sync; we only rerun when a change is detected. So we won't correct for any drift.

**Comment by jtfogarty** [comment]
@jlewi I accepted the invite but now the meeting is gone

**Comment by jlewi** [comment]
The logs have a link to the event;
https://www.google.com/calendar/event?eid=a2YwMjlfMjAyMDA4MThUMTUwMDAwWiBrdWJlZmxvdy5vcmdfN2w1dm5ibjhzdWoyc2UxMHNlbjgxZDk0MjhAZw

When you navigate to it it says the event has been canceled and removed from the calendar.

**Comment by jlewi** [comment]
@thesuperzapper 's message just clicked for me. I believe he is on the money. We have two meetings with the same id; kf029.

@jtfogarty Can you please put together a PR to change the ID of the community meeting?

Can someone also update calendar_import.py to detect and avoid creating duplicate entries?

**Comment by jtfogarty** [comment]
@jlewi done

**Comment by jlewi** [comment]
Thanks @jtfogarty #432 should hopefully provide us a quick fix. But I think we need a longer term solution from the calendar admins to prevent this from reoccurring in the future.

**Comment by jlewi** [comment]
It looks like the meeting is now on the community calendar but I'm not getting an invite. Even though kubeflow-discuss is listed as an attendee. 

Unlike the 5:30 pm meeting, for the 8am meeting the group is listed as a single attendee.

My conjecture is that this  might be because the calendar invite was created by autobot@kubeflow.org which is not a manager of kubeflow-discuss@googlegroups

**Comment by jlewi** [comment]
I made autobot@kubeflow.org  as a manager of kubeflow-discuss@googlegroups
I deleted the calendar invite and kicked the bot. 

That doesn't appear to have fixed.

@jtfogarty @karlschriek Can one of the calendar admins investigate this further and figure out what we need to do? Would be great to get a separate issue filed.

**Comment by jlewi** [comment]
https://support.google.com/calendar/answer/172013?hl=en

https://support.google.com/a/answer/167094?hl=en

So I would expect manager permissions to be sufficient.

**Comment by jlewi** [comment]
Maybe try bumping the KF id so we create a new unique calendar invite?

**Comment by jlewi** [comment]
Filed #438 to deal with invites not getting sent.

**Comment by jlewi** [comment]
Lets use #438 and #439 to track follow on work.
