### ISSUE TITLE
Notebook WG leads need to take ownership of release infrastructure, processes, and artifacts

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#433]
Every work group needs to take ownership of its release process and artifacts.

This issue is tracking the work for notebooks

@kubeflow/wg-notebook-leads

**Comment by kimwnasptd** [comment]
This is a work in progress. We are tracking the use of the Optional-test infra in https://github.com/kubeflow/kubeflow/issues/5482.

**Comment by thesuperzapper** [comment]
This has been done.
/close
