### ISSUE TITLE
Create a GitHub group for the calendar admins

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#437]
@jtfogarty @karlschriek @nicholas-abad @yuzliu

You are currently listed as OWNERs of the calendar
https://github.com/kubeflow/community/blob/master/calendar/OWNERS

Could you please define a GitHub group in
https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml#L651

This way its easy to mention all of the calendar admins on groups

**Comment by Bobgy** [comment]
@jtfogarty @karlschriek @nicholas-abad @yuzliu
friendly ping

**Comment by jtfogarty** [comment]
@Bobgy It's my understanding that all working groups and SIGs will have their own calendar managed outside the Kubeflow Org. Is this github group still needed?

**Comment by thesuperzapper** [comment]
I think someone still needs to be admin for the kubeflow-discuss calendar?

**Comment by Bobgy** [comment]
It seems the existing calendar admins either prefers moving to separate calendars or didn't reply. I think we can close this only continue moving to individual calendars.

**Comment by Bobgy** [comment]
https://github.com/kubeflow/community/issues/445

**Comment by thesuperzapper** [comment]
@Bobgy I assume we still want the community meeting to be in `kubeflow-discuss` as its targeted at everyone?

If so, we still need an admin group for that.

**Comment by Bobgy** [comment]
@thesuperzapper you can still contact them via https://github.com/kubeflow/internal-acls/blob/bf392a1a643b36ac0285ee03530db26946579fad/google_groups/groups/calendar-admins.yaml#L3
