### ISSUE TITLE
calendar events are added but invites are not sent to kubeflow-discuss

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#438]
see: https://github.com/kubeflow/community/issues/430#issuecomment-717277759

The Tuesday 8am community meeting got added to the calendar but members of kubeflow-discuss@googlegroups.com are not getting invites.

These articles about permissions and groups seem relevant

https://support.google.com/calendar/answer/172013?hl=en

https://support.google.com/a/answer/167094?hl=en

Per: https://github.com/kubeflow/community/issues/430#issuecomment-717284396  autobot@kubeflow.org should be a group manager.

Calendar admins (@jtfogarty @karlschriek @nicholas-abad @yuzliu) does one of you want to investigate this?

**Comment by jlewi** [comment]
I tired bumping autobot@kubeflow.org from a manager to owner of kubeflow-discuss@ just to see if that would change things. I also deleted the existing calendar invite. 

I think we should try bumping the calendar ids as well to ensure we aren't updating an existing calendar invite.

**Comment by jlewi** [comment]
I conducted an experiment; I created two calendar invites manually one using the account autobot@kubeflow.org and one as jlewi@google.com.

Both show up on the community calendar but neither get invites on my calendar. So it doesn't look like this has anything to do with the automation.

Anyone want to do a bit of Googling to figure out if this is some permission setting?

**Comment by jlewi** [comment]
I take that back it looks like the manually added events by jlewi@kubeflow.org and autobot@kubeflow.org both eventually showed up they just took a while.

So looks like an issue with the automation.

**Comment by Bobgy** [comment]
Did you let autobot@kubeflow.org join kubeflow-disciss group?
I think it doesn't need to be manager or owner, just member is enough.

I used to see the same problem, but after I joined the Google group, it works.

And, to add to that, after joining the group I had to delete kubeflow-discuss from the invite and add it back again to properly invite.

**Comment by jlewi** [comment]
@Bobgy Yes autobot@kubeflow.org is a member of the Google group.

The problem appears to be specific to the automation because when I login as autobot@kubeflow.org and manually add calendar invites the invites are added to the individual calendars.

My conjecture is that this an OAuth scope issue. The docs don't list any other scopes
https://developers.google.com/calendar/auth

However, I'm going to try requesting Google Groups scope. My conjecture is that the bot might need the groups scope in order to  view members.

**Comment by jlewi** [comment]
I created a Google group kf-test-calendar@googlegroups.com to experiment with.

Looking at code commit history it doesn't look the scopes has changed.
https://github.com/kubeflow/community/commit/8df8fcf1f5a57887af61325d25feb78503331e57#diff-0e5a0a9fa5b75131386c0d5890ed3013c42519fbcaea40dbaf0915472673fce9L34

It also looks like when human users ran the sync manually the invites were added.

**Comment by jlewi** [comment]
I tried creating a fake calendar invite: #438 and it correctly shows up on my calendar. So my hypothesis is that this is an issue with updating existing calendar invites.

**Comment by jlewi** [comment]
That didn't work the new updated calendar invite doesn't show up my calendar. 

I wonder if there is some sort of protection in place to prevent spamming large groups.

I'm still puzzled by the fact that calendar_import.py appears to have worked correctly when run manually.  I wonder if there was a difference in the OAuth client secrets.

**Comment by jlewi** [comment]
It started showing up but then disappeared when I deleted the existing duplicate invite. So it looks like

1. We need to bump the IDs
1. Give it some time for the invites to be sent

We probably need to fix #429 as well

**Comment by jlewi** [comment]
I deleted the AutoML meeting and now after some delay it is showing up on my calendar. As are the community meeting.

Next step is probably to implement pruning per #429 so that its easy to bump the calendar id to force creation of a new event.

**Comment by andreyvelich** [comment]
Thank you for help with this @jlewi!
Should this meeting be visible for other `kubeflow-discuss` members?
I still can't see invitation/notification for this meeting on my calendar.

I see only one that created in [`Kubeflow community calendar`](https://calendar.google.com/calendar/u/0/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com).

**Comment by jlewi** [comment]
@andreyvelich What day are you looking at? Are you looking at 11/25? I wonder if there is some rate limiting that happens with really large groups. See also #445

**Comment by andreyvelich** [comment]
Oh, now I see it, it appears on my calendar on 11/25, thanks!
I was looking for the 11/11 (11am UTC, 3am PST). Does it have some restrictions ?

About https://github.com/kubeflow/community/issues/445, can we discuss about it on today's community meeting ?
/cc @gaocegege @johnugeorge @Jeffwan

**Comment by Bobgy** [comment]
I think all problems solved, current work around is bumping calendar id and removing the existing calendar item.
A PR example to update a calendar event: #444
