### ISSUE TITLE
Track P0/P1 backlog for each WG

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#439]
Now that we have WGs formed. It would be good to track the backlog of P0/P1 issues for each workgroup (based on area labels).

We'd like to make sure WGs are keeping.

@jtfogarty what is the current status of the [reports](https://groups.google.com/g/kubeflow-discuss/c/1o2ig0ZIzyg/m/47k_xpBEAAAJ) that you used to send out?

* Is it possible to break down issues by priority and area?
* Are the dashboards running publicly somewhere?
* Is the code public?

Thanks

**Comment by jlewi** [comment]
WG leads what are you currently doing if anything to track whether you are keeping up with your backlog?

@kubeflow/wg-automl-leads 
@kubeflow/wg-notebook-leads 
@kubeflow/wg-notebook-leads 
@kubeflow/wg-serving-leads 
@kubeflow/wg-training-leads

**Comment by jlewi** [comment]
@kubeflow/wg-pipeline-leads

**Comment by gaocegege** [comment]
Where should we keep our backlog for WGs?

**Comment by jlewi** [comment]
@gaocegege I'm not sure I understand the question. I assume people are filling GitHub issues in appropriate repos and labeling them. Issue labels should allow grouping issues by WG; e.g. area/jupyter maps to the notebook leads.

**Comment by jlewi** [comment]
In addition to @jtfogarty 's code we also have this notebook
https://github.com/kubeflow/community/blob/master/scripts/project_stats.ipynb

Which I believe is computing time series for each label have number of open and closed issues.

@GauravSarkar if you are interested in contributing I think some pointers are

* Update the notebook to generate plots (use Altair instead of PlotLy) to actually show the timeseries of open and closed issues
* Update the notebook to compute time series of groups of labels; e.g. a time series for issues that have the label "area/jupyter" and "priority/p0".
* Ideally automate the running of the notebook
   * An example would be: https://github.com/kubeflow/code-intelligence/blob/master/tekton/tasks/run-notebook-task.yaml

**Comment by jtfogarty** [comment]
@jlewi yes this link is to the public dashboard https://gitmetrix.007ba7.us/
The code is here https://github.com/docure/git-metrics
I will look into adding priority and area to the dashboard

**Comment by jlewi** [comment]
Thanks @jtfogarty It looks like the [backlog graphs] (https://gitmetrix.007ba7.us/#/backlog) are per repo. Could we generate back logs by label and aggregate across repos.

**Comment by jtfogarty** [comment]
we could, I'm not sure how well it would perform.  there is no backend database and it is all client side scripting so we would have to pull all issues from all repos and group.  We need to close all the issues for 0.7.0  and earlier.

**Comment by jlewi** [comment]
Would the notebook approach work better? That is pulling the data from BigQuery which should scale better.

**Comment by thesuperzapper** [comment]
This is related to https://github.com/kubeflow/community/issues/439
