### ISSUE TITLE
Make Each WG Responsible For Their Own Calendar

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#445]
Back in June we asked for additional volunteers to administer the Kubeflow Calendar; kubeflow/community#342

The goal here was to offload the work from Google. The expectation was the new admins would take responsibility for automating the calendar and performing any maintenance. 

While the admins were gracious in volunteering their time this has simply not achieved the desired outcome as Google continues to bear the brunt of maintaining the calendar. 

As #413, #438 & #274 illustrate when people run into problems they are still largely looking to the Google folks to fix them. This is not sustainable.

I think we need a better solution. As long as folks aren't incentivized to invest in the Calendar (or similar work) things likely won't change.

I think we should consider making each WG responsible for creating and maintaining its own calendar which it uses for any of its meetings.

/cc @kubeflow/wg-automl-leads 
/cc @kubeflow/wg-notebook-leads 
/cc @kubeflow/wg-pipeline-leads 
/cc @kubeflow/wg-serving-leads 
/cc @kubeflow/wg-training-leads 

/cc @jtfogarty @karlschriek @yuzliu @nicholas-abad @Bobgy

**Comment by karlschriek** [comment]
I would agree pretty strongly with this. Apologies, I am one of the volunteers, but have been mainly a bottleneck. It makes sense to put control of the calendar(s) directly with the working groups that need the

**Comment by thesuperzapper** [comment]
I have formalised this into proposal: https://github.com/kubeflow/community/issues/482
