### ISSUE TITLE
remove kubeflow-discuss from calendar invites

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#446]
Per #438 we put a lot of effort into making calendar invites show up by inviting the group  kubeflow-discuss@googlegroups.com

I'm not sure we actually want to do that. 

* kubeflow-discuss@ is probably not the right mailing list to invite folks to all the meetings
  * Most meetings will be specific to WGs and not of broader interest
  * We might want to have specific groups if people really wanted to get calendar invites

* It might just be better to share the [community calendar link](https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com&ctz=America%2FLos_Angeles) and tell interested parties to subscribe

**Comment by thesuperzapper** [comment]
/close 

This would be addressed by the proposal https://github.com/kubeflow/community/issues/482, lets discuss it more there.
