### ISSUE TITLE
[Proposal] Create Kubeflow Roadmap for feature requests

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/community#454]
As of now, I've noticed some end-users want to send feature request but posted in wrong repository, application, and didn't get enough attention / feedback from community side.

Creating Kubeflow Roadmap **centralized** github repository / project for Kubeflow feature requests, is helpful for end-users to find the right place for feature-requests and get enough attention from WGs. 

Here is an example from our side, https://github.com/aws/containers-roadmap/projects/1

For cloud-provider feature requests, we label / title them with [Amazon] / [Arrikto] / [Google] / [IBM] etc.
For application feature requests, we label / title them with [Pipelines] / [Kfserving] / [Katib] etc.
For common feature requests, we label / title them with [Manifests] / [Deployment] / [Common-Infra] etc.

/cc @kubeflow/wg-deployment-leads @kubeflow/wg-manifests-leads @kubeflow/wg-automl-leads @kubeflow/wg-notebook-leads @kubeflow/wg-pipeline-leads 
/cc @jlewi @jbottum @jtfogarty

**Comment by jlewi** [comment]
* Is the problem triaging and routing issues to appropriate wgs?
* Is the problem wgs aren't paying attention to their issues?

When an issue is filed it should get labeled with appropriate area/<area> labels which can be used to route issues to the appropriate WG. In principle we can transfer issues between repos but we haven't done much of that.

I suspect WGs are only monitoring certain repositories as opposed to their labels.

#439 is tracking adding metrics on the issue backlog for each area. I think metrics would go along way towards increasing accountability and responsiveness.

**Comment by PatrickXYS** [comment]
I think your words touched some of the pain points.

Imagine one scenario:

End-user created a Katib-related issue in `kubeflow/kubeflow` or `kubeflow/manifests` repository, labeling the issue with `/area AutoML` will be able to get attention from `WG-AutoML`, but what happened next is also a pain point. 

After `WG-AutoML` discussed and decide to develop/fix this issue, there might be no way for end-user to keep track of the development and delivery status unless they keep pinging `WG-AutoML` folks in the github issue. 

It's also not realistic for `WG-AutoML` to keep their eyes on several different repos including `kubeflow/kubeflow` and `kubeflow/manifests` etc. 

My proposal of creating a github centralized repository will also take advantage of bot-labelling as described  https://github.com/kubeflow/community/issues/439

Also we have slack channel #feature-request, which is also a good supplement to centralized github repository. 

/cc @jlewi @Jeffwan @jbottum

**Comment by Bobgy** [comment]
I think we should mechanisms that encourage users to directly create an issue on katib repo directly instead.

Can we disable issues on kubeflow/kubeflow and put a map there where people should create issues?

**Comment by PatrickXYS** [comment]
> I think we should target mechanisms that encourage users to directly create an issue on katib repo directly instead.

It's our infinite goal but as I can see, it's too difficult to achieve. Especially end-user might meet some problems like istio / notebook-controller, not all the end-users know where to create github issues.

> Can we disable issues on kubeflow/kubeflow and put a map there where people should create issues?

This is good idea, but question is how can we make sure end-user aware of where the map is? 

Besides training end-user to get familiar with our architecture / mapping, I'd like to train / inform WG folks to use kubeflow/roadmap as a centralized point for feature-request supplement to their own repo (Katib/Kfserving/KFP/...). 

At this point, end-users can go ahead to create issue in kubeflow/roadmap, and that's the only requirement.

But to achieve this goal, this requires some additional development work to correctly label issues / mentioning right WG. I'm pretty sure community will benefits from long-term given short-term large investment.

/cc @cvenets @Bobgy @yanniszark @animeshsingh @andreyvelich

**Comment by andreyvelich** [comment]
> Can we disable issues on kubeflow/kubeflow and put a map there where people should create issues?

I also like this approach if it is possible. That will simplify the tracking process for the WG leads.

**Comment by Jeffwan** [comment]
There won't be perfect solution. 


> WG folks to use kubeflow/roadmap as a centralized point 

`kubeflow/kubeflow` plays role of `kubeflow/roadmap`.  we don't need to create another one.

> Can we disable issues on kubeflow/kubeflow and put a map there where people should create issues?

That would not be a good experience on the user side. As I know, most of them are not familiar the sub-projects. Some users just like to raise issues there. At the same time, most control plane related components are still hosted in `kubeflow/kubeflow`

I would suggest to remain the same at this moment and ask product team to drive the work for long term.

**Comment by thesuperzapper** [comment]
As a partial solution, we could improve the GitHub issue template on `kubeflow/kubeflow` to include links to the sub projects.

But this still has the problem of users not necessarily knowing what version of each sub-app they are on, as each distribution will have different versions.

**Comment by Bobgy** [comment]
> > Can we disable issues on kubeflow/kubeflow and put a map there where people should create issues?
> 
> That would not be a good experience on the user side. As I know, most of them are not familiar the sub-projects. Some users just like to raise issues there. At the same time, most control plane related components are still hosted in `kubeflow/kubeflow`

I think we need to guide users from the most obvious option "raise an issue in kubeflow/kubeflow" to what will help WGs manage the community -- "raise an issue in the corresponding repo". This also helps the user because their questions/issues have a higher chance to get responded to and fixed faster.

People may make mistakes, that's totally fine. If they raised an issue against the wrong repo. That repo owner will be telling users that's not right.
 
> I would suggest to remain the same at this moment and ask product team to drive the work for long term.

Agree, I don't mean to push an immediate change, but rather discuss a direction where we target towards. I think the major blocker right now is notebooks WG need to have its own repo.

**Comment by Bobgy** [comment]
> As a partial solution, we could improve the GitHub issue template on `kubeflow/kubeflow` to include links to the sub projects.
> 
> But this still has the problem of users not necessarily knowing what version of each sub-app they are on, as each distribution will have different versions.

It's each application's responsibility to make it clear what version it is.

**Comment by cvenets** [comment]
> Agree, I don't mean to push an immediate change, but rather discuss a direction where we target towards. I think the major blocker right now is notebooks WG need to have its own repo and distributions need to have their own repos.

@Bobgy wrt Notebooks, the only solution I see, at least for the near future, is to either create a new repo under kubeflow/notebooks and treat it the same way we do for any other component (KFP, KFServing, Katib), or rename the current repo. I don't think we should rush to do any of the two right now, since we have bigger problems to solve.

I think these are too many changes to do at once. Let's finish with the 1.2 release, start the 1.3 release process that will (a) streamline testing/manifests and (b) start deprecating components (e.g., Profile Controller), and we can then try to figure the above out.

**Comment by PatrickXYS** [comment]
I agree with @cvenets , let's finish 1.2 release. And I think @kubeflow/wg-manifests-leads need to discuss and collaborate to bring up a proposal / plan for kubeflow community. 

> start the 1.3 release process that will (a) streamline testing/manifests and (b) start deprecating components (e.g., Profile Controller),

This is 1st priority, other breaking changes should wait / collaborate with us to be made.

**Comment by Jeffwan** [comment]
> Agree, I don't mean to push an immediate change, but rather discuss a direction where we target towards. I think the major blocker right now is notebooks WG need to have its own repo and distributions need to have their own repos.

@Bobgy  +1 

What's the kubeflow/kubeflow positioning? Should we deprecate it once notebook and control plane components move out of it?

**Comment by gaocegege** [comment]
> What's the kubeflow/kubeflow positioning? Should we deprecate it once notebook and control plane components move out of it?


Same question here.

**Comment by jlewi** [comment]
@PatrickXYS it looks like the problem you are trying to address is how can we do a better job of routing issues to WGs 

I agree this is a problem. Regarding your proposed solution

> Creating Kubeflow Roadmap centralized github repository 

In general Kubeflow is becoming more decentralized with each WG in charge of its own resources/destiny. Creating a centralized repo for ROADMAP doesn't seem aligned with that.

Here are some alternatives I can think of

1. Disable filing issues on kubeflow/kubeflow (e.g. archive the repo)
1. Update our triage process to include transferring issues out of kubeflow/kubeflow

I think 1. is blocked on kubeflow/kubeflow#5419. I don't think we want to archive kubeflow/kubeflow until we have whiddled it down to just the readme.

#2 seems like a good option. The issue I forsee with taking advantage of GitHub's issue transfer feature is
  
  * Potential permission issues
  * Users might be surprised to no longer find their issue in the kubeflow/kubeflow repo
    
These seem like interim problems until we can fix kubeflow/kubeflow#5419 and archive the repo; so I think we can live with them.

**Comment by terrytangyuan** [comment]
I'd suggest not to archive the kubeflow/kubeflow repo as it has gained quite a large number of stars which is one of the characteristics of popularity. Should we use it to feature and highlight all the WGs/projects within kubeflow and serve as an entry point for community?

**Comment by animeshsingh** [comment]
+1 on not archiving it. Beyond the popularity, stars are a means for of people to come back to the project.

**Comment by cvenets** [comment]
+1 on not archiving it. There needs to be an entry point for users.

**Comment by Bobgy** [comment]
Issues can be disabled (or limited to contributors independently from archiving the repo).
So I don't like archiving it either, same as reasons above.

**Comment by PatrickXYS** [comment]
/close

Close the issue, will re-open until we feel the pain
