### ISSUE TITLE
Working Group Status Check

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#459]
Hi all, 

As discussed in the latest community meeting, I want to check how the establishment of each Working Group is going. Most groups have had a month since they were formally established, so now is a good time for a check in.

### Questions for WG Leads:

1. Have you setup a regular meeting in the [kubeflow/community -- calander.yaml](https://github.com/kubeflow/community/blob/master/calendar/calendar.yaml)?
    * _NOTE: while there is discussion about moving away from the central calendar, this has not happened yet, so I expect people will put their events into this calendar for now._
1. Have you created a public place to track what you are working on (and planning)? 
    * For example, you might use a: `Google Doc`, `Github Project`, or `Slack Channel`
1. Have you added your leads to the `OWNERS` files of the repos/folders you control?

---

### I would greatly appreciate if a representative of each working group could respond in this thread.
* @kubeflow/wg-automl-leads 
* @kubeflow/wg-deployment-leads 
* @kubeflow/wg-manifests-leads 
* @kubeflow/wg-notebook-leads 
* @kubeflow/wg-pipeline-leads  
* @kubeflow/wg-serving-leads 
* @kubeflow/wg-training-leads

**Comment by Bobgy** [comment]
For `@kubeflow/wg-pipeline`, we've done 1. and 3, 2. is WIP and there are a few pieces not settled yet.

**Comment by Jeffwan** [comment]
for @kubeflow/wg-training-leads We have not scheduled the weekly meeting, I think we will have some conclusion end of this month. There're a few training repos in Github, 2 is not done yet. we will probably use kubeflow/common but need some discussion. 3 is done.

**Comment by yuzisun** [comment]
for @kubeflow/wg-serving
1) We have been doing biweekly regular meeting
2) We have slack channel `kfserving` for handling user issues, github project board to track the work. Currently we have two active projects [KFServing 0.5](https://github.com/kubeflow/kfserving/projects/2) and [Multi Model Serving](https://github.com/kubeflow/kfserving/projects/3).
3) OWNERS files are setup with @kubeflow/wg-serving-leads

**Comment by gaocegege** [comment]
for @kubeflow/wg-automl-leads 

1. We have it /cc @andreyvelich 
2. No, we can setup it in the next meeting
3. Yes

**Comment by yanniszark** [comment]
For @kubeflow/wg-manifests-leads:
1. Not yet, we are in the process of deciding the meeting times (https://kubeflow.slack.com/archives/C01EY3L525N/p1606879566011400)
2. We have a Slack channel. We will use a google doc for the meeting notes and track our work as issues in the manifests repo.
3. I believe we have:
https://github.com/kubeflow/manifests/commit/855d7e996238f22c9107d39e7d9b1089be3e408a#diff-c393dd2b18a8a597d895940893e574d6895122c4bf3ce6e2a78dbd9ca0cdd66f
https://github.com/kubeflow/manifests/commit/cdbcb2a2077a5928c003b35f3248d42957f23bfd#diff-c393dd2b18a8a597d895940893e574d6895122c4bf3ce6e2a78dbd9ca0cdd66f
@Jeffwan I see you're not in the OWNERS file, could you make a PR?

**Comment by andreyvelich** [comment]
Thanks @gaocegege.
In addition to 2)
AutoML slack channel: https://kubeflow.slack.com/archives/C018PMV53NW.
AutoML meeting notes: https://docs.google.com/document/d/1MChKfzrKAeFRtYqypFbMXL6ZIc_OgijjkvbqmwRV-64.

**Comment by terrytangyuan** [comment]
> for @kubeflow/wg-training-leads We have not scheduled the weekly meeting, I think we will have some conclusion end of this month. There're a few training repos in Github, 2 is not done yet. we will probably use kubeflow/common but need some discussion. 3 is done.

Thanks @Jeffwan. Yes we can use kubeflow/common but we'll probably need additional labels for different training operators. Let's discuss this together soon.

**Comment by thesuperzapper** [comment]
For @kubeflow/wg-notebook-leads:

1. We have setup a weekly meeting for now (will be made bi-weekly after a while):
   * Wednesday 11:00pm PT (https://github.com/kubeflow/community/pull/462)
2. We have created two places for people to see what the Notebook WG is doing:
   * Google Doc: https://bit.ly/kf-notebooks-wg-backlog 
   * Kanban: https://bit.ly/kf-notebooks-wg-kanban
3. Given there are so many components owned by the Notebook WG, we are planning to do a big cleanup of all the relvant OWNERS files soon. (Pending the first Notebook WG meeting)

**Comment by yanniszark** [comment]
For @kubeflow/wg-manifests-leads:

| Description | Link |
| - | - |
| Notes | https://arrik.to/kf-wg-manifests-notes |
| Calendar | https://arrik.to/kf-wg-manifests-cal |
| Meeting | https://arrik.to/kf-wg-manifests-meet |

For the @kubeflow/wg-notebook-leads:

| Description | Link |
| - | - |
| Notes | https://arrik.to/kf-wg-notebooks-notes |
| Calendar | https://arrik.to/kf-wg-notebooks-cal |
| Meeting | https://arrik.to/kf-wg-notebooks-meet |

**Comment by thesuperzapper** [comment]
Closing this issue at it was a one-time thing
