### ISSUE TITLE
Kubeflow Slack invitation requires email address from limited domains 

### ISSUE THREAD

**Issue by denis-angilella** [kubeflow/community#473]
Link [invitation to our Slack workspace](https://join.slack.com/t/kubeflow/shared_invite/zt-cpr020z4-PfcAue_2nw67~iIDy7maAQ) from https://www.kubeflow.org/docs/about/community/#slack-community-and-channels allows only email addresses from limited domains:
```
You can use any account with the domain:
google.com
caicloud.io
microsoft.com
Don’t have an email address from one of those domains?
Contact the workspace administrator at Kubeflow for an invitation.
```
Could you remove this restriction to allow open access from the community or as a workaround indicate how to contact the Slack workspace administrator to ask for an invitation?

**Comment by castrojo** [comment]
K8s uses https://github.com/rauchg/slackin to manage invites, might be worth investigating.

**Comment by mameshini** [comment]
@denis-angilella To join Kubeflow Slack, you are welcome to use and share the following link:
[https://join.slack.com/t/kubeflow/shared_invite/zt-lhkwrmkh-JPT2g9eva1oPkS00~VHZDQ](https://join.slack.com/t/kubeflow/shared_invite/zt-lhkwrmkh-JPT2g9eva1oPkS00~VHZDQ)

However, that link will expire in 22 days, therefore we do not publish the link in the slack guidelines to reduce administrative effort.  Kubeflow Slack guidelines are published [here](https://github.com/kubeflow/community/tree/master/slack)

Slack does not allow to auto-approve any user from any domain, therefore it is currently limited to just 3 domains and Google login.  Please comment here in this issue if you have suggestions about improving the Slack signup workflow or would like to implement it.  One option is to publish my email in Slack guidelines.  However we can also continue to resolve Slack signup issues here via Github issues.

**Comment by thesuperzapper** [comment]
The Kubernetes Slack has some kind of bot to automate the invites: https://slack.k8s.io/

This seems to the be bot they are using https://github.com/rauchg/slackin, we should consider setting it up.

**Comment by thesuperzapper** [comment]
I think @mameshini is the admin of slack, he would have to setup the bot token.

**Comment by mameshini** [comment]
I also updated the documentation site with a new `Join Slack` link: https://github.com/kubeflow/website/pull/2480

**Comment by denis-angilella** [comment]
Thanks @mameshini, I was able to join the Kubeflow Slack using the new link and approved your kubeflow/website#2480 PR.
Note that the [invitation link in Slack guidelines](https://github.com/kubeflow/community/blob/master/slack/README.md#slack-guidelines) needs update too.


> However, that link will expire in 22 days, therefore we do not publish the link in the slack guidelines to reduce administrative effort.

As @castrojo and @thesuperzapper suggested, setting up a bot to automate the invites would save time and avoid confusion.

> One option is to publish my email in Slack guidelines. However we can also continue to resolve Slack signup issues here via Github issues.

I tried to join Kubeflow Slack via this page https://www.kubeflow.org/docs/about/community/#slack-community-and-channels which do not refer to Slack guidelines. It would be better to update this page to indicate how to contact Slack admin or to create a GitHub issue to ask for access

**Comment by knkski** [comment]
I recently created the #microk8s room on matrix.org, and bridged it to the #microk8s channel on the Kubeflow Slack. This made it very easy for people to join the #microk8s channel on Slack without having to go through the Slack signup process. Is it worth doing that with other channels in the Kubeflow Slack?

It might also be worth maintaining Kubeflow rooms on matrix.org in general; there's already a general Kubernetes presence at #kubernetes:matrix.org.

**Comment by thesuperzapper** [comment]
Can someone please confirm if this issue is permanently resolved? 

It still seems like [the invite on kubeflow.org](https://www.kubeflow.org/docs/about/community/#slack-community-and-channels) requires an `@google.com` domain.

Should I create an issue tracking the setup of an invite bot?

**Comment by denis-angilella** [comment]
@thesuperzapper from the discussion above, the issue was fixed for 22 days

> Should I create an issue tracking the setup of an invite bot?

**Comment by thesuperzapper** [comment]
/reopen

Users cannot currently join the slack.

I can verify the "invite" link under https://www.kubeflow.org/docs/about/community/#slack-community-and-channels still requires an @google.com email:
![Screen Shot 2021-03-03 at 17 27 22](https://user-images.githubusercontent.com/5735406/109763141-c71baf00-7c45-11eb-9d49-563d4b924c0e.png)
![Screen Shot 2021-03-03 at 17 28 15](https://user-images.githubusercontent.com/5735406/109763195-d7cc2500-7c45-11eb-93f6-537f870c99d3.png)

Also someone raised an issue on `kubeflow/kubeflow`: https://github.com/kubeflow/kubeflow/issues/5654

**Comment by thesuperzapper** [comment]
@mameshini kind of funny question, can we just add @gmail.com as one of the options?

**Comment by mameshini** [comment]
Yes adding @gmail.com is an easy change.  I will implement it and update
Slack signup to the fresh link.

**Comment by thesuperzapper** [comment]
@mameshini please can you make that change to add @gmail.com !!!

**Comment by mameshini** [comment]
Still working on it.   I raised a support issue with Slack support.  For some reason they don't allow white-listing of `gmail.com` domain.
![slackerr](https://user-images.githubusercontent.com/6588364/110424105-1eab8780-8057-11eb-9ba1-0b53170f260a.png)

**Comment by thesuperzapper** [comment]
@mameshini then can we please just remove the domain limit, lol

**Comment by cspavlou** [comment]
I don't know if this helps, but we had faced the same issue in the past, here is a relevant issue: https://github.com/kubeflow/website/issues/1793

 Note that @sarahmaddox mentions that 
> The new link is permanent, according to the GitHub "invitations" UI.

**Comment by mameshini** [comment]
Yes the issue is that Slack invite links expire after 30 days.  Here is a new link:
https://join.slack.com/t/kubeflow/shared_invite/zt-n73pfj05-l206djXlXk5qdQKs4o1Zkg

The message about limited list of domains appears when Slack link has expired.  Sorry it's a misleading message but that's how Slack works.  

I have updated the community website with a new link (PR #2534) - please approve it.

**Comment by thesuperzapper** [comment]
The invite link was updated with https://github.com/kubeflow/website/pull/2534, and will never expire.

However, only 2000 users can join with any given invite, so we should consider setting up an invite bot.

**Comment by thesuperzapper** [comment]
### If anyone comes across this issue from google, the link you want to join the Kubeflow Slack is:

- https://www.kubeflow.org/docs/about/community/#kubeflow-slack
