### ISSUE TITLE
Centralize working group boards/status in wgs.yaml

### ISSUE THREAD

**Issue by castrojo** [kubeflow/community#474]
It's difficult to find the kanban boards for different working groups, we should consider a field in wgs.yaml so that we can track and then generate appropriate READMEs. Something like `tracking_document:` or `planning_document:` perhaps?

**Comment by thesuperzapper** [comment]
This is related to: https://github.com/kubeflow/community/issues/439

**Comment by thesuperzapper** [comment]
We need to ensure `wgs.yaml` is updated for each working group:
- to include a kanban link
- to include the correct calendar times (and meeting notes)
- to include the correct members
- to remove random links like "Open Community Issues/PRs", "Mailing list" 

Note, these pages are now linked to from the [README.md of kubeflow/kubeflow](https://github.com/kubeflow/kubeflow/blob/master/README.md), so are viewed by lots of people:
- @kubeflow/wg-automl-leads https://github.com/kubeflow/community/tree/master/wg-automl
- @kubeflow/wg-deployment-leads https://github.com/kubeflow/community/tree/master/wg-deployment
- @kubeflow/wg-manifests-leads https://github.com/kubeflow/community/tree/master/wg-manifests
- @kubeflow/wg-notebooks-leads https://github.com/kubeflow/community/tree/master/wg-notebooks
- @kubeflow/wg-pipeline-leads https://github.com/kubeflow/community/tree/master/wg-pipelines
- @kubeflow/wg-serving-leads https://github.com/kubeflow/community/tree/master/wg-serving
- @kubeflow/wg-training-leads https://github.com/kubeflow/community/tree/master/wg-training

**Comment by Bobgy** [comment]
I'd be happy to help with review and approval.

Any volunteers on updating the generator script to support this new field?

**Comment by thesuperzapper** [comment]
You interested @castrojo?

**Comment by castrojo** [comment]
Updating the script for the new field is outside my skill tree, however I'd be happy to update the wgs.yaml.

**Comment by thesuperzapper** [comment]
/reopen

We should still discuss this.
