### ISSUE TITLE
Create dashboard of ksonnet registry clones

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#48]
Every time someone creates a ksonnet app that uses our GitHub registry they issue a GitHub request to pull down our components.

This would be a great metric to collect since it would provide a number of the ksonnet apps using our registry.

Does GitHub expose these metrics?

/cc @chrisheecho

**Comment by jlewi** [comment]
Looks like this data is available here
https://github.com/kubeflow/kubeflow/graphs/traffic

Which has a bunch of useful information.

**Comment by jlewi** [comment]
@chrisheecho Did you have a chance to look into this? Do you think we will get this done this week?

**Comment by jlewi** [comment]
@chrisheecho Any progress on this?

**Comment by chrisheecho** [comment]
have not had a chance to look at this please leave it with me for next sprint.

On a separate note do you need to be an owner to review this link? https://github.com/kubeflow/kubeflow/graphs/traffic I just get routed to the regular list of repo page. Perhaps I have permission issues here?

**Comment by jlewi** [comment]
Not sure what the permission model is. Is the traffic data accessible via API? The dashboard only shows me a couple ~2 weeks of data.

**Comment by jlewi** [comment]
https://developer.github.com/v3/repos/traffic/

Looks like it only provides last 14 days. Might be good to sync it to a database (BigQuery) so we can preserve longer times. I wonder if someone has already written such a sync.

**Comment by jlewi** [comment]
I thought about this more the fact that the number of unique cloners is approximately 30 per day seems suspiciously high to me.

I think most of this is coming from our test infrastructure via [checkoust.sh](https://github.com/kubeflow/testing/blob/master/images/checkout.sh#L25)

i.e. our CI system clones the source via https. I thought we were using GITHUB_ID which would have dedupped the clones.

I wonder if we can switch to using ssh and using a bot so that all of our test clones will be counted as one user.

We should also double check that whatever ksonnet does to pull the data counts as a clone.

**Comment by jlewi** [comment]
The bootstrapper will also undercut these metrics since we plan on baking in the repo into the bootstraper. 
Of course we should be able to measure bootstraper image pulls.
