### ISSUE TITLE
Proposal: Calendar Refactor

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#482]
__I have two goals with this proposal:__
1. prevent random event invites reaching members of `kubeflow-discuss`
2. have all invites except the official community meeting be opt-in after joining `kubeflow-discuss`

__My proposal:__
I have found that all we need to prevent random events being auto added to your calendar through `kubeflow-discuss` is to restrict non-admins from seeing the members of the Google Group.

Actions:
1. restrict non group-managers seeing members of `kubeflow-discuss`
2. remove all existing events from `./calander/calander.yaml` except the official community meeting
3. have all current invite owners who directly invited `kubeflow-dicsuss@googlegroups.com` retract their invite
4. have each WG setup a custom Google Calendar which they control
4. setup a new page on https://kubeflow.org which lists all these calendars (so members can opt-in)
5. regularly talk about this page in the official meeting and on `kubeflow-discuss` (to ensure visibility of the meetings)

__Additionally:__
- we might want to restrict non group-managers from attaching files to `kubeflow-discuss` threads, this will prevent `.ical` attachments being spammed (which still happens, even if auto-adding to your calendar is not possible without seeing members)

__CC:__
- @kubeflow/wg-automl-leads 
- @kubeflow/wg-deployment-leads 
- @kubeflow/wg-manifests-leads 
- @kubeflow/wg-notebooks-leads 
- @kubeflow/wg-pipeline-leads 
- @kubeflow/wg-serving-leads 
- @kubeflow/wg-training-leads

**Comment by theadactyl** [comment]
Thanks for this proposal. This looks overall good, with a couple of caveats:

1) It prevents us from having a viewable calendar with all community meetings displayed. I suppose this could be managed by the list you mentioned with updated date & times with links to individual WG calendars. 
2) Seems like this might work better as a wiki page on kubeflow/community that is linked to from docs for easier updates & accuracy? Open to thoughts here.

I'd like to hear from wg chairs about how this would impact them.

**Comment by gaocegege** [comment]
Will we maintain the community calendar like this https://calendar.google.com/calendar/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428%40group.calendar.google.com&ctz=America%2FLos_Angeles ?

**Comment by thesuperzapper** [comment]
I think there is something seriously wrong with the current calendar, the US time community meeting has dropped off both of my Google accounts (which are members of kubeflow-discuss). Possibly we should just delete the existing calendar and make a new one during the refactor.

**Comment by thesuperzapper** [comment]
Does anyone know a reason why specific events might disappear from a google group calendar (but only for some invitees)?

For example, is there some limit of users in google group calendars, and we just hit it?

**Comment by theadactyl** [comment]
These calendars have been notoriously challenging to administer (in other
communities as well). Do we have examples from other communities about how
to do this the right way?

**Comment by thesuperzapper** [comment]
@geekygirldawn do you have any thoughts or idea for this?

**Comment by geekygirldawn** [comment]
I'll think about this a bit more, but every other project I'm involved in has issues keeping calendars /  invites up to date and in sync, so I'm not sure there is a great solution to this.

I do have one question ... With the existing solution, I can't find any integration between the list of meetings in [calendar/calendar.yaml](https://github.com/kubeflow/community/blob/master/calendar/calendar.yaml) with the ones in [wgs.yaml](https://github.com/kubeflow/community/blob/master/wgs.yaml). Am I missing something or do these sources get out of sync?

But in answer to @theadactyl's question about examples: 
- Kubernetes has a long and detailed document with [calendar guidelines](https://github.com/kubernetes/community/blob/master/communication/calendar-guidelines.md), but k8s is a whole different scale and having a calendar per SIG/WG is probably overkill for Kubeflow. 
- [Knative has a calendar](https://knative.dev/community/calendar/) that a few trusted people, [including WG leads](https://knative.dev/community/contributing/working-groups/working-groups/), can update, but they still have the problem of spamming the list for every single meeting, which can be annoying for those of us that participate in a few targeted areas and rarely attend meetings.
- Istio has a separate [Google Group for calendar invites](https://github.com/istio/community/blob/master/WORKING-GROUPS.md#working-group-meetings) that you can join if you want to get all of the WG invites. 

I still like the idea of having a single Google calendar where I can view all of the meetings in one place and add them to my calendar if I want to attend, so maybe we should focus on figuring out the problem of spamming the list with invites for WG meetings that only a subset of people care about?

**Comment by geekygirldawn** [comment]
It sounds like people want to:
* keep a single Google calendar with all of the meetings in one place 
* stop posting all of the WG meetings to the mailing list.

I think that to do this, we would need to remove or re-write some of the automation currently found here: https://github.com/kubeflow/community/tree/master/calendar

@jtfogarty @nicholas-abad @yuzliu - As OWNERS of the calendar folder, you're probably more familiar with this automation - what do you think?

**Comment by thesuperzapper** [comment]
@RFMVasconcelos I think the easiest way to move forwards, is to make a new section on the website for calendars (to link to the WG calendars)

**Comment by thesuperzapper** [comment]
We are working on this change for the website, see issue: https://github.com/kubeflow/website/issues/2807

We are planning to create pages under `about` called `Kubeflow Working Groups` and `Kubeflow Community Meeting` which provide information about the calendars and link to the WG folders in `kubeflow/community` (like [wg-pipelines](https://github.com/kubeflow/community/tree/master/wg-pipelines)).
