### ISSUE TITLE
Proposal: Improve blog contribution process

### ISSUE THREAD

**Issue by theadactyl** [kubeflow/community#488]
Similar to what we're working on for Twitter: https://github.com/kubeflow/community/issues/487, but more around documenting the process and adding a layer of community reviewers.

## Context
Though the [blog contribution flow](https://github.com/kubeflow/blog) is now based on GH and Fast pages, we need a more robust set of reviewers and clearer review process. 

## Proposal 
To unblock blog contributions, I propose the following: 
- create a community blog reviewer role
- require lgtm from (non-author) community blog reviewer, who will verify blog follows guidelines & styleguide (needed)
- require lgtm from (non-author) WG Lead, who will check for technical accuracy as a Subject Matter Expert (SME)
- approval from (non-author) blog OWNER

Bonus: 
- since the blog automation right now presents a barrier to entry for non-technical contributors, I'd love it if we could add to this workflow for those authors to pair with a community blog reviewer for submission (eg, submit your blog to blog@kubeflow.org & find a sponsor who can submit on your behalf) 

## Needed
- community blog reviewer role & volunteers
- guidelines and styleguide (similar to [k8s](https://kubernetes.io/docs/contribute/new-content/blogs-case-studies/))
- document outlining process

WDYT? @animeshsingh @castrojo @karthikv2k

**Comment by castrojo** [comment]
Similar to the twitter guidelines I'd be happy to to adapt the k8s guidelines and styleguide for this and submit them as a PR.

**Comment by theadactyl** [comment]
Another framework for consideration: https://github.com/knative/docs/tree/master/blog

**Comment by animeshsingh** [comment]
makes sense to me.

**Comment by jbottum** [comment]
I like the direction of the proposals. We might look at current state and work on desire future state.    Some comments on Current State: 1) If you are not a GitHub user, creating and formatting a blog in FastPages can be a learning event (that does not improve content). 2) Shorter blogs are better..I am the long post king!.  3) Approvals often go in a circle (technical correction, to final approver...then another technical correction, back to final approver, etc)...is this best in GitHub?  4) People are excited to post, and get tired when the process slows down, but our process is best effort. 5) Blog Posts will likely come in bursts (around KF 1.3), which will overtax approvers...is it best to have 5 posts in 1 week or 1 post a week over 5 weeks?

**Comment by castrojo** [comment]
I've taken an initial stab at this: 

https://github.com/kubeflow/community/pull/492

Josh, one thing I've seen done in the past is you can have a submission via something more friendly to non-technical users, say a google doc submission or a form or something. The only problem with that someone in the project would have to volunteer to work with the author to translate that to github/markdown/hugo/netflify, etc. 

It would really lower the bar to entry though, and it's probably in the group's collective interest to help people do this as we probably want to see user-stories told by the people doing the top level work and not have to worry about the blog minutia.

**Comment by theadactyl** [comment]
> Approvals often go in a circle (technical correction, to final approver...then another technical correction, back to final approver)

I think this can be pretty easily done in GitHub through assignments in a way that makes it transparent who's court the ball is in. A GitHub project with some automation could make it easier to visualize blog states. 

>4) People are excited to post, and get tired when the process slows down, but our process is best effort. 5) Blog Posts will likely come in bursts (around KF 1.3), which will overtax approvers...is it best to have 5 posts in 1 week or 1 post a week over 5 weeks?

I'd definitely prefer to have things more spaced out -- it improves blog readership overall to have a more consistent publishing rate. I think it's also important to validate the quality and accuracy of posts that go out. Fewer, more high quality posts > more posts. We've tried to do this before, but having a monthly "roundup" blog with links out to posts in other places would allow us to highlight more content without having to scale the review efforts.
