### ISSUE TITLE
Go Program to manage membership in Google Groups base don YAML file

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#49]
A lot of our test/release infrastructure uses GCP in the kubeflow.org domain.

Right now we use a variety of Google groups to maintain ACLs. This doesn't provide a lot of visibility or auditability into who has what permissions.

It might be nice if ACLs could be maintained in GitHub and then sync'd to Google Cloud Directory sync
https://support.google.com/a/answer/106368

to assign various permissions (e.g. access to test infrastructure).

One concern would be protecting the GitHub repository to make sure compromising the repository couldn't compromise our release infrastructure. 

We could potentially build safe guards into the sync; e.g. only ids corresponding to certain trusted orgs could be granted certain permissions.

**Comment by jlewi** [comment]
@fejta FYI

**Comment by jlewi** [comment]
Managing everyone's membership in the corresponding Google Groups is becoming a real blocker.

It would be great to make progress on this by having a simple go program that does the following

1. Read a YAML file that lists google groups and for each group a list of members
1. Use the [Google Groups API](https://developers.google.com/admin-sdk/directory/v1/reference/members/insert) to add/remove members

This would allow us to manage members via code review.

**Comment by kkasravi** [comment]
@jlewi could this be in scope for a delegation phase in bootstrapper? After the cluster roles are defined and the auth provider is configured then the org/group/members are bound. When creating kubeflow.org we would define a yaml that would be part of the org/group/member phase. Thoughts? I could pick this up and do the simple implementation - but also integrate into the delegation pipeline. Thoughts?

**Comment by jlewi** [comment]
@kkasravi This isn't for use by Kubeflow users. This is solely for use by us to manage our test and release infrastructure; so it shouldn't be part of the bootstrapper.

**Comment by jlewi** [comment]
Created repository internal-acls; because I want to start reducing the toil of managing different Kubeflow google groups and we can use the **gam** command line tool to start improving things.

**Comment by jlewi** [comment]
Duplicate of #55
