### ISSUE TITLE
Kubeflow Community User Survey Blog Post for Kubeflow Release 1.3

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#493]
**Kubeflow Community User Survey Blog Post for Kubeflow Release 1.3**

The Kubeflow Community conducts a User Survey every 6 to 12 months.   We would like to provide the results to the Community in conjunction with the Kubeflow 1.3 Release (the RC is due March 15).    We have 167 responses.   Our target ~180 responses (which would be a ~50% increase year over year).     

We are working on a blog post that presents the results.   This blog post should be available as Kubeflow 1.3 becomes available.   We will open a Pull Request and post the blog on Kubeflow, https://blog.kubeflow.org/, using the Fast AI process.

The Kubeflow Community User Survey is available here: https://forms.gle/5LfCuEPdKFfJo3e2A

We would appreciate the Community's support in capturing input from a few more users (as we plan to close the Survey soon so that we can finish the Blog Post and get the necessary approvals).

**Comment by jbottum** [comment]
@theadactyl Hey Thea - Would the Kubeflow twitter team please consider issuing a tweet on the "last call" for responses to the annual Kubeflow Community User Survey ?   We have 167 responses in need 12 more to make our goal (showing 50% yr/yr growth).

**Comment by theadactyl** [comment]
Can you draft tweet?

**Comment by jbottum** [comment]
@theadactyl proposed tweet....The Kubeflow Community User Survey is closing soon. This is your last chance to help the Kubeflow open source contributors.  Please take a few minutes tonight to answer the Survey.  Your input keeps the Community strong.   Thanks!  https://forms.gle/5LfCuEPdKFfJo3e2A

**Comment by theadactyl** [comment]
Done: https://twitter.com/kubeflow/status/1366801231113457666

**Comment by theadactyl** [comment]
@jbottum is this good to close?

**Comment by jbottum** [comment]
@theadactyl  Not yet :) I wanted to use this issue to track the progression of the blog post itself.  David Aronchick and I have completed a draft but we are blocked from finishing by 2 things.   1) We want to have a 50% yr/yr increase ...now at 172 responses...only need 7 more.   2) we will need to update the charts in the blog post (to show the new numbers) and fix any of the commentary to match the charts.     Once that draft is ready, we will post here in google doc as that will be easier for pre-Public posting edits ( expect timeframe...next week).   After that review, we would like to post on blog.kubeflow.org via a GitHub Pull Request.   Does that sound okay with you?
