### ISSUE TITLE
Proposal: have CHANGELOG and ROADMAP on kubeflow.org

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#494]
__Goals:__
* Create a place where users can see changes between Kubeflow releases (1.3, 1.4, ...)
* Create a a place where users can see the roadmap of future Kubeflow feature milestones
* Remove the need for `kubeflow/kubeflow` root OWNERS to aprove updates to the ROADMAP/CHANGELOG

__Background:__
* Our current [CHANGELOG.md](https://github.com/kubeflow/kubeflow/blob/master/CHANGELOG.md) and [ROADMAP.md](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md) files are massively out of date (e.g. Kubeflow 0.5).

__Proposal:__
1. Create a new section of https://kubeflow.org for CHANGELOG, and ROADMAP
2. Let all working group leads update these new pages in `kubeflow/website`, giving them OWNERS
3. Replace the existing [CHANGELOG.md](https://github.com/kubeflow/kubeflow/blob/master/CHANGELOG.md) and  [ROADMAP.md](https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md) files with links to this new pages on https://kubeflow.org

**Comment by thesuperzapper** [comment]
Would the working group leads appreciate this CHANGELOG on https://kubeflow.org as a place to list new/upcoming features?

@kubeflow/wg-automl-leads
@kubeflow/wg-deployment-leads
@kubeflow/wg-manifests-leads
@kubeflow/wg-notebooks-leads
@kubeflow/wg-pipeline-leads
@kubeflow/wg-serving-leads
@kubeflow/wg-training-leads

**Comment by thesuperzapper** [comment]
Also CC for @RFMVasconcelos as he is effectively the lead of docs these days.

**Comment by RFMVasconcelos** [comment]
Thank you @thesuperzapper for this and for looping me in!

**Comment by theadactyl** [comment]
Interesting idea! To play devil's advocate, I think we should first work to ensure we're updating these regularly before we publish them to the website. It's my experience that website typically lags behind GitHub SOT, not the other way around, so wouldn't want stale docs to be exposed to the average website user. WDYT?

**Comment by terrytangyuan** [comment]
My only concern is that a combined change log or roadmap doc would get really big. I am uncertain others would keep them up to date. In addition, the release cycles are totally different for each working group and for each project. I think it's a good idea to have a centralized place that provides links to roadmap/change log for all the projects, but probably not the content itself though.

**Comment by thesuperzapper** [comment]
The current [CHANGLOG.md](https://github.com/kubeflow/kubeflow/blob/master/CHANGELOG.md) hasn't been updated in over 2 years, so I can't see a way we could make the situation worse.

@theadactyl the issue is that the CHANGELOG/ROADMAP are very unlikley to be updated in thier curren location, because:
* The `kubeflow/kubeflow` repo no longer hosts most Kubeflow components (except the Notebooks & UI stuff)
* No-one other than @Bobgy @jlewi @pdmack can update those files (as they sit in the root of the repo)

@terrytangyuan I agree it makes sense to have an over-arching roadmap for Kubeflow, __in addition__ to specific technical roadmaps for each working group, I believe the best way to start, is to move the CHANGELOG/ROADMAP to https://kubeflow.org (`kubeflow/website`) to enable regular contributions from WG leads (by setting appropriate OWNERS).

**Comment by thesuperzapper** [comment]
I see that there is a small section for ROADMAP (not CHANGELOG) already on kubeflow.org, but it can definitely be improved:
https://www.kubeflow.org/docs/about/kubeflow/#roadmaps

**Comment by castrojo** [comment]
I've been investigating tools in this space and `release-notes` is what k8s and knative use, here's an example of their setup: 

https://github.com/knative/serving/blob/main/.github/workflows/knative-release-notes.yaml

And here's the homepage: https://github.com/kubernetes/release/tree/master/cmd/release-notes

**Comment by castrojo** [comment]
Looks like they have it set up with just an action, one of them pointed me to this: https://github.com/knative/serving/actions/runs/572125726

Then it spits out a release-notes.md and then they use that as the basis for their release notes.

**Comment by Bobgy** [comment]
@thesuperzapper what do you propose should be the content of the overarching CHANGELOG?

Should it be manually maintained? Because I think no repo's commit history can represent kubeflow project.

Given the project organization of moving development into WGs, I think it's best to add an application version matrix of what version was included in what kubeflow release and then a link to the project's changelog referring to changes between the releases. The structure will allow minimal maintenance while providing the major information to everyone.

Probably some hand written changelog for dependency version assumption (like istio) is needed, but that seems can be a bonus point.

**Comment by thesuperzapper** [comment]
@Bobgy I agree a version matrix is needed (assuming each component of kubeflow has a version independent of kubeflow itself, which is not the case for notebooks right now).

I think we can do something similar to kubernetes for the over-arching release notes, with "major themes" etc.

For reference: https://kubernetes.io/docs/setup/release/notes/

**Comment by thesuperzapper** [comment]
Bump, I think this idea is still relevant, and will help users understand our goals.
