### ISSUE TITLE
Create label kind/tweet-request

### ISSUE THREAD

**Issue by theadactyl** [kubeflow/community#496]
In advance of us making progress on https://github.com/kubeflow/community/issues/487, can we create label for tweet requests for easier tracking? cc@bobgy 

I haven't added labels before, and not being a prow expert don't want to bash around without help.

**Comment by DavidSpek** [comment]
/cc @Bobgy 
I'm not sure if this is setup with prow, or created in each repository separately. Somewhat related, does anybody know where the prow config lives that is setup with the Google OSS Prow Robot? I'd like to view this config while I'm exploring some things related to the release.

**Comment by DavidSpek** [comment]
I believe the label should be added in this prow config: https://github.com/google-oss-robot/test-infra/blob/3ac644aa4271af7c8c2e19646fd8e625ba8309f6/config/prow/plugins.yaml#L101

**Comment by Bobgy** [comment]
https://github.com/GoogleCloudPlatform/oss-test-infra
This is the actual repo for google oss prow.

Besides that, I can create the label manually too

**Comment by Bobgy** [comment]
Created the label
