### ISSUE TITLE
calendar: Remove obsolete entries

### ISSUE THREAD

**Issue by yanniszark** [kubeflow/community#504]
### Problem Statement

Starting with 1.3, WGs are responsible for their own calendar. Serving and AutoML WGs have already removed their calendar from the calendars YAML. However, the calendar hasn't been synced, so the old meetings still show up in peoples' calendars, ALONG with the new ones, making for a confusing experience.

### Proposed Solution

Sync the calendar.

cc @kubeflow/wg-automl-leads 
cc @kubeflow/wg-serving-leads 
cc @Bobgy @castrojo

**Comment by thesuperzapper** [comment]
Please review my proposal for a calendar refactor: https://github.com/kubeflow/community/issues/482

**Comment by Bobgy** [comment]
/assign
I will remove them from central calendar.

**Comment by Bobgy** [comment]
Btw, there is an existing issue -- kubeflow calendar sync doesn't support prune semantics

**Comment by Bobgy** [comment]
I deleted automl events, but I cannot find kfserving ones. Can you point to where they are?

**Comment by andreyvelich** [comment]
Thank you for your help @Bobgy!
Did you delete US and Asia friendly meeting for the AutoML?
I still can see US friendly meetings on the calendar: https://calendar.google.com/calendar/u/0/embed?src=kubeflow.org_7l5vnbn8suj2se10sen81d9428@group.calendar.google.com

**Comment by Bobgy** [comment]
I tried to delete a few more I found, thanks for the link. Can you confirm?

**Comment by andreyvelich** [comment]
No I can't see the KFServing and AutoML on the calendar. Thank you @Bobgy!

**Comment by Bobgy** [comment]
Happy to help!
