### ISSUE TITLE
Working Group list - duplicated list and empty lists

### ISSUE THREAD

**Issue by geekygirldawn** [kubeflow/community#508]
The [wg-list.md](https://github.com/kubeflow/community/blob/master/wg-list.md) file has a few issues that I think are related to it being copied over from Kubernetes, which has SIGs, WGs, UGs, and Committees.

Here are the specific issues:
* Title is currently "SIGs and Working Groups" but should probably just be "Working Groups"
* The first sentence mentions SIGs.
* The WGs are listed twice - under the heading "Master WG List" and "Master Working Group List"
* There are empty tables for "Master User Group List" and "Master Committee List"

I dug into this a little bit, since I'm familiar with how k8s did this, and I think all of these issues can probably be fixed in this template file: https://github.com/kubeflow/community/blob/master/generator/list.tmpl 

One other issue is that 
* There is a comment in [wg-list.md](https://github.com/kubeflow/community/blob/master/wg-list.md) file that reads "To understand how this file is generated, see https://github.com/kubeflow/community/generator/README.md", but that link 404s. I think it should be "https://github.com/kubeflow/community/blob/master/generator/README.md"

I think this can be fixed in the header file here: https://github.com/kubeflow/community/blob/master/generator/header.tmpl

I'm happy to fix these if someone can confirm that these are the correct places for those fixes. But also haven't used my local Go env in ages and would need to update it, so if someone else wanted to do it, that would be fab :) 

Tagging @castrojo since he's familiar with this from k8s and it looks like @swiftdiaries ported this over and might know more.

**Comment by geekygirldawn** [comment]
One more thing while we're fixing stuff ... in light of all of the recent inclusive naming conversations floating around, I think we can remove the word "master" from the headings and just say "Working Group List"

**Comment by swiftdiaries** [comment]
This is exactly what I followed. You're right and that sounds like a good plan to me

**Comment by thesuperzapper** [comment]
@geekygirldawn I am not super familiar with these files, but perhaps @jlewi can clarify if your barking up the right tree?

**Comment by geekygirldawn** [comment]
This turned out to be a pretty easy fix, so I went ahead and opened a PR for it. Everything seemed to work as expected when I ran make generate, and I ended up with markdown files that look correct.

However, I uncovered a related issue that is probably worth thinking about after this first PR gets merged. It looks like there are 2 SIGs - SIG Feature Store and SIG On-Prem that are not currently in wg-list. I'm not sure if it makes sense to put them in wg-list.md or elsewhere, but this one will require a bit more work and help from those 2 SIGs to make sure that the yaml files are up to date, so I'm unlikely to tackle this one :)

**Comment by geekygirldawn** [comment]
I did notice that there is a related issue #481, and since the sigs are in wgs.yaml, it probably makes sense to update the templates to pull them into wg-list.md. However, there does need to be some cleanup because at least for sig-onprem, the README for that SIG isn't being properly generated because the yaml file defines the dir as "sig-on-premises", but PR #475 created the dir as 'sig-onprem' - @castrojo - this is your PR :) To avoid breaking existing links, it probably makes more sense to fix this in the yaml file to point to the existing dir 'sig-onprem'.

I think we should be fine for SIG Feature Store without any additional work.

**Comment by geekygirldawn** [comment]
I went ahead and fixed the SIG issues described above in PR #509, so we can close this issue when the PR merges.
