### ISSUE TITLE
Create Slide Presentation for Kubeflow 1.3

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#510]
The Community should create a slide presentation for the Kubeflow 1.3 release.

/assign @jbottum

**Comment by jbottum** [comment]
draft slide deck, https://docs.google.com/presentation/d/15fsCJ4Q57n61UrYexFcouS0jkZT7OZCXfjg79nmsrC8/edit#slide=id.gcdbf7ac38a_0_16

**Comment by jbottum** [comment]
@yanniszark please review the installation slide, (slide 9)

**Comment by jbottum** [comment]
@kimwnasptd please review notebooks and tensorboard/volume manager slides (slides 11, 12)

**Comment by jbottum** [comment]
@andreyvelich please review operator and training slides (slides 13, 14), thanks!

**Comment by jbottum** [comment]
@animeshsingh would you please review slide 16 on KFServing ?

**Comment by jbottum** [comment]
@james-jwu James, would you please review slide 15 on KFP ?

**Comment by james-jwu** [comment]
@Bobgy to take a look as well.

**Comment by jbottum** [comment]
**Request to WG contributors**- We would like to validate the KF 1.3 slide deck by Thu, May 6 and need your help... @Bobgy @james-jwu Would you please review the Kubeflow PIpeline slide 15?   @RFMVasconcelos Would you please provide your edits on the documentation slide  (slide 10) ? @gaocegege @Jeffwan @terrytangyuan @andreyvelich Would you please review slide 13  (training operators) ? @animeshsingh Animesh would you please review the KFServing slide (slide 16) ?   Thanks!

**Comment by Jeffwan** [comment]
I can help take a look.

**Comment by james-jwu** [comment]
I added @zijianjoy to review KFP slide 15. It looks good from my end.

**Comment by jbottum** [comment]
@pvaneck Hey Paul, if you could help approved the KFServing slide in this presentation, I would appreciate it.    (slide 16)

**Comment by jbottum** [comment]
@RFMVasconcelos Hey Rui, if you could review / improve slide 10 on 1.3 docs, I would appreciate it.   Thanks. https://docs.google.com/presentation/d/15fsCJ4Q57n61UrYexFcouS0jkZT7OZCXfjg79nmsrC8/edit#slide=id.gcdbf7ac38a_0_541

**Comment by jbottum** [comment]
@yuzisun Hey Dan - would you please look at the KFServing slide (slide 16) of this kubeflow 1.3 presentation ?   Thanks.  https://docs.google.com/presentation/d/15fsCJ4Q57n61UrYexFcouS0jkZT7OZCXfjg79nmsrC8/edit#slide=id.gcdbf7ac38a_0_541

**Comment by RFMVasconcelos** [comment]
@jbottum done!
