### ISSUE TITLE
Kubeflow vector file application

### ISSUE THREAD

**Issue by GT-ZhangAcer** [kubeflow/community#513]
Dear,

In order to enhance the communication between PaddlePaddle and KubeFlow, and catch the eyes of developer on the open source projects, we kindly apply your authorization to display your community Logo at the official site on PaddlePaddle.（https://www.paddlepaddle.org.cn/）

Display format: There will be a KubeFlow Logo displayed in the “Cooperate community” block in our new landing page called “Developer community”. We apply for your authorization to do that.  
Authorize information:  KubeFlow vector file

**Comment by thesuperzapper** [comment]
@GT-ZhangAcer Review if your usage meets the requirements set out in https://github.com/kubeflow/community/blob/master/KUBEFLOW_BRAND_GUIDELINES.pdf

**Comment by GT-ZhangAcer** [comment]
Thank you very much.
