### ISSUE TITLE
Kubeflow 1.4 Release Team

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#517]
As discussed in the community meeting, we have taken nominations for the Kubeflow 1.4 release team in a [kubeflow-discuss thread](https://groups.google.com/g/kubeflow-discuss/c/qIMNsJDqF2Q).

There have been 3 nominations:
* Kimonas Sotirchos (@kimwnasptd)
* David van der Spek (@DavidSpek)
* Rui Vasconcelos (@RFMVasconcelos)

---

To formally establish all the above members as the "Kubeflow 1.4 Release Team", we need representatives for the following groups indicate if they `endorse` or `object` to this group (as a whole).

__Governence Groups:__
* @kubeflow/project-steering-group 

__Working Groups:__
* @kubeflow/wg-automl-leads 
* @kubeflow/wg-deployment-leads 
* @kubeflow/wg-manifests-leads 
* @kubeflow/wg-notebooks-leads 
* @kubeflow/wg-pipeline-leads 
* @kubeflow/wg-serving-leads 
* @kubeflow/wg-training-leads

**Comment by Bobgy** [comment]
All the three members have strong contribution history, I look forward to working with them for 1.4 release!
: )

/lgtm
for both @kubeflow/wg-pipeline-leads @kubeflow/project-steering-group

**Comment by animeshsingh** [comment]
Congrats guys

/lgtm

**Comment by mkbhanda** [comment]
Having problems on Google Groups to respond. Thank you @Diana for the nomination and @kimwnasptd and @rui for the warm seconds. It would be an honor to serve the KF community.

Some valuable points were brought uo.
voting ties:  some alternatives might be one vote per company, bring in a tie breaker vote by having the largest sub-project lead also vote, one of us having no vote, could be me. 
multiple geographies: @johnugeorge, having folks across multiple GEOS aligns with what the KF community is doing so admirably by alternating meeting times to acknowledge its global community base.  It is to try and avoid burn out during coordination efforts by being up at all times, to be able to hand-off to someone in another geo. 
two year experience requirement: The KF community is a few years old, so a 2 year period of experience is a luxury it can afford. However, on new projects, one leverages the experience people bring from their studies and other jobs, be it development/documentation/consensus building/release etc and a curiosity to learn and deliver. By weakening that requirement a project can be more inclusive and have a larger talent pool to pull from.

**Comment by thesuperzapper** [comment]
@mkbhanda what are you responding to in your comment?

This issue is just about getting lazy consensus for the 1.4 release team.

**Comment by kimwnasptd** [comment]
/reopen

@thesuperzapper her comment was in continuation to the mailing-list discussion about adding @mkbhanda to the release team https://groups.google.com/g/kubeflow-discuss/c/vLCxh01t_WM.

**Comment by DavidSpek** [comment]
@jtfogarty Mentioned he was available to shadow. I thought it is probably a good idea to have this stated here as well.

**Comment by thesuperzapper** [comment]
Kubeflow 1.4 has been released.

/close
