### ISSUE TITLE
Restructure of Kubeflow Slack Channels

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/community#518]
Hey all, I believe the Slack would be much easier for new (and existing) users if we instituted a standard set of "prefixes" for the channel names. 

Prefixes are very standard practice on Slack and allow you to effectively "group" channels into sections.

__Channels Layout:__
* `#announcements`
   * CHANNEL - for community announcements
   * DEFAULT - yes
   * NOTE - must be the original `#general` (due to free slack limitations)
* `#general`
   * CHANNEL - for all general discussions.
   * DEFAULT - yes 
* `#feature-requests`
   * CHANNEL - for people to suggest/discuss new ideas for Kubeflow
   * DEFAULT - yes 
* `#job-postings`
   * CHANNEL - for people to post Kubeflow related jobs
   * DEFAULT - no 
* `#release`
   * CHANNEL - for people to discuss the next release of Kubeflow
   * DEFAULT - no 
* `#distro-*`
   * PREFIX - for Kubeflow distributions
* `#external-*`
   * PREFIX - for software/things NOT owned by a Kubeflow WG
* `#kubeflow-*`
   * PREFIX - for software/things owned by a Kubeflow WG
* `#platform-*`
    * PREFIX - for cloud/hosting platforms (not distributions)
* `#users-*`
    * PREFIX - for specific groups of users (e.g countries, regions)
* `#sig-*`
   * PREFIX -  for official Kubeflow Special Interest Groups
* `#wg-*`
   * PREFIX - for official Kubeflow Working Groups

**Comment by johnugeorge** [comment]
Adding Kubeflow prefix looks redundant to me. 
Also, it is confusing to have Kubeflow-operator-tensorflow mapped to tf-operator, Is there real need for this change at this point?

**Comment by thesuperzapper** [comment]
@johnugeorge thanks for your comments!

### Re: the `kubeflow-*` prefix

Adding this prefix has a few main benefits:
* Allows us to distinguish things are "officially part of Kubeflow"  (that is, maintained" by a Kubeflow WG) 
* It groups all the component discussions together on the side menu
* `#kubeflow-pipelines` has stronger brand recognition than `#pipelines` (as does `#kubeflow-notebooks` vs `#notebooks`)

### Re: the `kubeflow-operator-*` prefix

There are many training operators, so if they have different prefixes, they appear all over the side-menu, making it hard for users to understand how they relate to each-other and Kubeflow.

The reason for the strange phrasing of `kubeflow-operator-...` is to ensure that they are sorted correctly when viewed alphabetically.

### Re: the docs referencing slack channels

Firstly, slack links are permalinks, (meaning that renaming the channel shouldn't change the link).

There actually aren't that many in our docs, I will list them all here:
* About/Community: 
   * https://github.com/kubeflow/website/blame/master/content/en/docs/about/community.md#L68-L80
* About/Contributing:
   * https://github.com/kubeflow/website/blame/master/content/en/docs/about/contributing.md#L75
   * (This one can probably be redirected to `#general`, as `#community` is quite redundant)
* About/GSOC:
   * https://github.com/kubeflow/website/blame/master/content/en/docs/about/gsoc.md#L71
   * (This web-page should probably archived anyway, as the Google Summer of Code ended a long time ago)
* Distributions/MiniKF: 
   * https://github.com/kubeflow/website/blame/master/content/en/docs/distributions/minikf/minikf-vagrant.md#L26
* Distributions/MicroK8S:
   * https://github.com/kubeflow/website/blame/master/content/en/docs/distributions/microk8s/kubeflow-on-microk8s.md#L108
* External Addons/Feature Stores:
   * https://github.com/kubeflow/website/blame/master/content/en/docs/external-add-ons/feature-store/getting-started.md#L44

**Comment by kimwnasptd** [comment]
> #kubeflow-*
>   PREFIX - for software/things owned by a Kubeflow WG

Why would we need to have both `wg-*` channels as well as `kubeflow-*` channels since both of these are owned by WGs?

I think this is very confusing and would propose we do the opposite. Lets only have one channel for software owned by a WG, so that people know that they can discuss software with the corresponding WGs.

**Comment by thesuperzapper** [comment]
@kimwnasptd I think I might not have described the distinction between `wg-*` and `kubeflow-*` very well.

* `wg-*`:  for __the working group itself__ to discuss WG related stuff, like meetings and discussions of new features/issues
* `kubeflow-*`: for __users of Kubeflow__ to discuss and ask questions

I believe the distinction is important, as it prevents users getting confused by the working group chatter, and allows the WGs to not miss important messages related to issues.

_PS: both of these have always existed on the slack, all the restructure did was ensure there were consistent prefixes_
