### ISSUE TITLE
Process to adopt paddle/operator

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/community#520]
Because we accepted https://github.com/kubeflow/community/pull/502 paddle operator proposal.

Now we can start the process to adopt the external repo.

**Comment by Bobgy** [comment]
Plan:
1. Stage current https://github.com/PaddleFlow/paddle-operator repo into google internal git.
2. Google internal release process (there might be back and forths on repo requirements, I'll sync with @tizhou86 to resolve them).
3. Once the repo is public, I can add OWNERS for @tizhou86 and @kubeflow/wg-training-leads.

Note, I cannot rename the existing github repo directly

**Comment by Bobgy** [comment]
That's my rough plan. Any concerns?

**Comment by Bobgy** [comment]
@tizhou86 May I confirm, is all the code in https://github.com/PaddleFlow/paddle-operator currently wrote by your company? Are there snippets or files copied from other projects?

If yes, it's not a big problem, but you'll need to move them into a "third_party" folder at the root of the repo and mention original copyright and license.

**Comment by Bobgy** [comment]
The copyright headers do not reference a company name. @tizhou86 do you want to update? 
example:
https://github.com/PaddleFlow/paddle-operator/blob/0f1bab781dcd45059fd3e336a3aa7ecab9eaf601/controllers/paddlejob_controller.go#L2

**Comment by Bobgy** [comment]
For new open source projects, we will be enforcing inclusive language policies.
I found that there are several occurrences of "master" in the repo: https://github.com/PaddleFlow/paddle-operator/search?q=master.

reference: https://developers.google.com/style/word-list#master

Can you investigate whether it's possible to avoid using "master" in code and API?

**Comment by Bobgy** [comment]
These are problems I found for the initial pass.

**Comment by tizhou86** [comment]
Hi @Bobgy , All mentioned problems above are resolved in PRs: https://github.com/PaddleFlow/paddle-operator/pull/48 and https://github.com/PaddleFlow/paddle-operator/pull/49 , please let us know if anything is needed from our side, thanks!

**Comment by Bobgy** [comment]
@tizhou86 thanks!
LGTM except  some minor problems:
* See two comments in https://github.com/PaddleFlow/paddle-operator/pull/49

**Comment by Bobgy** [comment]
Another Q: did anyone file any patents around paddle-operator?

**Comment by kuizhiqing** [comment]
Hi @Bobgy , No, no patent is filed for paddle-operator now.

**Comment by kuizhiqing** [comment]
Hi @Bobgy , I've add license for the yaml files with https://github.com/PaddleFlow/paddle-operator/pull/53 . 
BTW, can you also add me as OWNERS in third step of your Plan.

**Comment by tizhou86** [comment]
> Hi @Bobgy , I've add license for the yaml files with [PaddleFlow/paddle-operator#53](https://github.com/PaddleFlow/paddle-operator/pull/53) .
> BTW, can you also add me as OWNERS in third step of your Plan.

Hi Bobgy, please also add kuizhiqing as the owner of this project, thanks! :-）

**Comment by Bobgy** [comment]
Sure, updated plan

**Comment by Bobgy** [comment]
A required process after paddle-operator is migrated to Kubeflow org:
All released images should comply with open source licenses of its dependencies: https://github.com/kubeflow/community/blob/master/guidelines/application_requirements.md#docker-images.

There were some documentation for how this can be done for go binaries in https://github.com/kubeflow/testing/tree/master/py/kubeflow/testing/go-license-tools. However, I wrote that tool a while back, now I'd recommend a new license tool I just built, refer to https://github.com/Bobgy/go-licenses/tree/main/v2.

I'm not opinionated on the choice, you can decide. Feel free to ask me if anything is not clear.

**Comment by Jeffwan** [comment]
@Bobgy Thanks for the update. Is it project owner's responsibility or WG's responsibility to make sure license files are included in all the images? Do you know if there's way we can scan images just like vulnerability scanner for docker images?

**Comment by Bobgy** [comment]
Hi @Jeffwan, I'd say it's primarily project owners' responsibilities.

**Comment by Bobgy** [comment]
I am not aware of such tools like vulnerability scanning, because it's a little hard understanding how each binary was built.

So far existing tools are around integrating license compliance process in dev/release process.

**Comment by kuizhiqing** [comment]
Hi @Bobgy @Jeffwan , thanks for your clarification. We are working on it now.

**Comment by kuizhiqing** [comment]
Hi @Bobgy , I've add licenses file in the repo and copy it into image, cf pr https://github.com/PaddleFlow/paddle-operator/pull/73.

For the image issue, kubebuilder provide us with base image *gcr.io/distroless* which we are replacing with *bitnami/minideb:stretch* due to the accessibility.

Is it ok or maybe we should use *registry.access.redhat.com/ubi8/ubi* as base image just like pytorch-operator did ?

**Comment by Jeffwan** [comment]
@kuizhiqing What's your plan on kubeflow/paddle-operator? Seems you still use PaddleFlow/paddle-operator as main dev repo?

**Comment by terrytangyuan** [comment]
Should we aim to migrate the paddle-operator code base to the unified operator instead of standalone new repo?

**Comment by kuizhiqing** [comment]
Hi all, we are aware of your advance in working on unified operator, we would like to making paddle work under unified operator, though, we are now working on repo paddle-operator and it's on the process of adoption. I'm considering that shall we possibly continue the process and plan to work with unified operator later ?

**Comment by Jeffwan** [comment]
@kuizhiqing Please have a look at tf-operator code base and see if that's possible to make it easily. We heavily reuse codes from kubeflow/common

**Comment by kuizhiqing** [comment]
Hi @Jeffwan ,  I've read your recent code in tf-operator, it make sense for paddlepaddle to take a place in it but I am afraid maybe we can do it later since it is not straight forward to make it right away.

**Comment by Bobgy** [comment]
I'm not opinionated on whether @kuizhiqing wants to merge paddle operator into the unified operator directly. We can start with a standalone repo and consider the merge too.

For the PR that adds license info to the image, I just did a quick review.
> For the image issue, kubebuilder provide us with base image gcr.io/distroless which we are replacing with bitnami/minideb:stretch due to the accessibility.

What do you mean by accessibility? Is it because gcr.io is not accessible from China?

**Comment by Bobgy** [comment]
@kubeflow/wg-training-leads as you may understand, Training WG should be responsible for security of paddle-operator.
Can we take one of the options below?
1. @tizhou86 @kuizhiqing give admin permission to paddle-operator container image repo to some representatives from @kubeflow/wg-training-leads 
2. host paddle-operator images on the same container registry as other Training WG images.

**Comment by kuizhiqing** [comment]
Hi @Bobgy , yes gcr.io is not always reachable from China.

So for base image, is bitnami/minideb:stretc is just ok or we should use
gcr.io/distroless  or registry.access.redhat.com/ubi8/ubi instead ?

For container registry, we can push our images in the same registry as other images, please help with the permission.

**Comment by Bobgy** [comment]
Understood, I don't think we have a strong opinion on the base image. At the end, users will only care about whether there can be vulnerabilities in the base image, I think you can decide by yourself based on this.

**Comment by Bobgy** [comment]
Hi @Jeffwan @gaocegege, what's your opinion on https://github.com/kubeflow/community/issues/520#issuecomment-915209894?
This is the remaining blocker.

**Comment by gaocegege** [comment]
I think we could give admin permission. The security issues can be guaranteed by code reviews. WDYT @Jeffwan @johnugeorge

**Comment by Jeffwan** [comment]
@gaocegege Just to double confirm. Do you mean you prefer second option and would like to grant permission to paddle maintainers? Our training operator image is hosted in AWS ECR and we use our own CI pipeline to build images. 

We also own kubeflow dockerhub but that's a free account with rated limited issue

**Comment by gaocegege** [comment]
> We also own kubeflow dockerhub but that's a free account with rated limited issue

I mean that we can grant docker hub permission. 

@kuizhiqing WDYT

**Comment by kuizhiqing** [comment]
> > We also own kubeflow dockerhub but that's a free account with rated limited issue
> 
> I mean that we can grant docker hub permission.
> 
> @kuizhiqing WDYT

OK, it works for us.

**Comment by terrytangyuan** [comment]
I don't have a strong opinion on the registry as long as Training WG has permission and can take actions when necessary. Any objections from others?

**Comment by terrytangyuan** [comment]
Ping @kubeflow/project-steering-group. Let's move forward with this. Please provide instructions on the next steps.

**Comment by terrytangyuan** [comment]
Also cc @zijianjoy

**Comment by terrytangyuan** [comment]
Since @Bobgy is no longer in the team, @zijianjoy would you be able to take over from here?

**Comment by Bobgy** [comment]
Thanks for the reminder!
@theadactyl and @kramachandran in @kubeflow/project-steering-group will be the main POCs for this.

**Comment by Windfarer** [comment]
Any update about the paddle operator?

**Comment by johnugeorge** [comment]
This can be closed as #1675 is merged into training operator
