### ISSUE TITLE
[Repository Reuqest] Create kubeflow/hyperparameter-tuning

### ISSUE THREAD

**Issue by YujiOshima** [kubeflow/community#53]
We have been discussing hyperparameter tuning https://github.com/kubeflow/tf-operator/issues/112 .
I have developed a parameter tuning system integrated with kubernetes [here](https://github.com/mlkube/katib).
To improve it and more integrate with kubeflow with the community, I would like to host this code under kubeflow.
/cc @jlewi @gaocegege

**Comment by jlewi** [comment]
How about we shorten the repo name to hp-tuning?

**Comment by YujiOshima** [comment]
@jlewi Great! Thank you so much.
And thank you for the information.
I will set up the repository.

**Comment by YujiOshima** [comment]
And I will close this issue when the setup is completed.

**Comment by jlewi** [comment]
Great thank you.

**Comment by ddysher** [comment]
The repository is named "hp-tunning" but the system is named "katib", should we rename the system to katib?

@YujiOshima @jlewi

**Comment by gaocegege** [comment]
I think katib is a good name for the repo. And we could add hyperparameter tuning as a label for the repo.

**Comment by jlewi** [comment]
SGTM. Should we consider it decided?

**Comment by jlewi** [comment]
@YujiOshima You're the leading developer of katib and its your contribution; so I suggest you make the final decision.

**Comment by YujiOshima** [comment]
Thank you @jlewi . 
Ofcource, I like the name. Let's rename the repo to katib.

**Comment by jlewi** [comment]
Done.

Is there any more work to be done for the issue or can we close it?

**Comment by YujiOshima** [comment]
Thank you!
I think setting up repository has been completed.
We can close this issue.
