### ISSUE TITLE
Add Kubeflow release related documentation to the community repo

### ISSUE THREAD

**Issue by annajung** [kubeflow/community#531]
Based on the [1.4 release retrospective discussion](https://docs.google.com/document/d/119PCr2h3Wwm7XA_qHqtda017Q--yWPF9u7nuUWo0ZnY/edit#), the 1.4 release team would like to propose that all release-related documentation be moved to the community repo and be managed by the release team members.

Currently, release-related documentations are located in the [manifest/docs](https://github.com/kubeflow/manifests/tree/master/docs). During the 1.4 retro, the release team discussed that location of the docs are not very transparent to the community and that release related docs should be part of the community repo in addition to instructions for [release blog posts and slide presentation](https://github.com/kubeflow/community/issues/529)

On behalf of the release team, I like to propose the following structure to be added to the community repo.
```
community
- releases
  - handbook.md
  - OWNERS
  - README.md
  - release-1.4
    - README.md
    - release-team.md
  - release-1.5
    - README.md
    - release-team.md
  - release-x.x
    - README.md
    - release-team.md
  - retrospectives
    - release-1.3.md
    - release-1.4.md
    - release-x.x.md
```

- For every release, a new directory `release-x.x` will be created under the `releases` directory.

- Each `release-x.x` will contain the [release timeline](https://github.com/kubeflow/manifests/tree/master/docs/releases/release-1.4#kubeflow-14) and [the release team member information](https://github.com/kubeflow/manifests/blob/master/docs/releases/release-1.4/release-team.md#kubeflow-14-release-team).

- I propose 1.5 release members to be included in the `OWNERS` file as reviewers and approvers to allow quick iteration of the release related documentation by the release team. For every future release, `OWNERS` file gets updated to reflect the current member of the release team while allowing approver status for the previous release manager.

**Comment by annajung** [comment]
cc @Bobgy @james-jwu @theadactyl @kimwnasptd

**Comment by thesuperzapper** [comment]
@annajung are you planning to make a PR?

**Comment by annajung** [comment]
Thanks for the reminder @thesuperzapper 
Since there is no opposition to the proposal, I went ahead and created a pull request https://github.com/kubeflow/community/pull/536 to move the release-related docs to the community repo. Please review when you can. Thanks!

**Comment by shannonbradshaw** [comment]
Thanks, @annajung !

**Comment by annajung** [comment]
PR merged https://github.com/kubeflow/community/pull/536, closing the issue! thanks everyone
