### ISSUE TITLE
Kubeflow Pipelines Roadmap Review on Nov 23, 30 or Dec 7 Community Meeting

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#532]
@james-jwu Per the discussion in the Nov 16 Community call, I would like to request that a Kubeflow Pipelines Working Group representative would please present the KFP roadmap to the Community during one of these Community calls - Nov 23, 30, or Dec 7.   As discussed, this can be a short presentation ~15 minutes and does not need to be limited to the features that align to KF 1.5 (Jan/Feb).  As our normal process for Community meetings, this meeting should be recorded so that others can listen to it later.    If this request is acceptable and actionable by the KFP WG, would you please reply/accept here and then add the KFP Review as an item on to the Community notes for an upcoming meeting.  Thanks.    Josh

**Comment by james-jwu** [comment]
I'd be happy to present KFP roadmap on Nov 30. I added an agenda item to the community notes.

**Comment by jbottum** [comment]
@james-jwu thank you for presenting the KFP roadmap to the community!

**Comment by james-jwu** [comment]
It's a pleasure!
