### ISSUE TITLE
Kubeflow Notebook and Manifest Roadmap Review at Community Meeting on Nov 23, 30 or Dec 7

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#533]
@kimwnasptd Per the discussion in the Nov 16 Community call, I would like to request that a Kubeflow Notebooks and Manifests Working Group representative would please present their roadmaps to the Community during one of these Community calls - Nov 23, 30, or Dec 7.   As discussed, this can be a short presentation ~15 minutes and does not need to be limited to the features that align to KF 1.5 (Jan/Feb).  As our normal process for Community meetings, this meeting should be recorded so that others can listen to it later.    If this request is acceptable and actionable by the Notebook and Manifest WG, would you please reply/accept here and then add the Notebook and Manifest Review as an item on to the Community notes for an upcoming meeting.  Thanks.    Josh

**Comment by kimwnasptd** [comment]
Awesome! I'm going over and creating the issues, which will help organize this.

I'll present this to the Community Meeting

**Comment by jbottum** [comment]
@kimwnasptd Please let me know if you can present on Dec 7 or 21.   Thanks!
