### ISSUE TITLE
AutoML roadmap presentation to Community on Nov 23, 30 and Dec 7

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#534]
@andreyvelich Per the discussion in the Nov 16 Community call, I would like to request that an AutoML Working Group representative would please present the AutoML roadmap to the Community during one of these Community calls - Nov 23, 30, or Dec 7.   As discussed, this can be a short presentation ~15 minutes and does not need to be limited to the features that align to KF 1.5 (Jan/Feb).  As our normal process for Community meetings, this meeting should be recorded so that others can listen to it later.    If this request is acceptable and actionable by the AutoML WG, would you please reply/accept here and then add the AutoML Review as an item on to the Community notes for an upcoming meeting.  Thanks.    Josh

**Comment by johnugeorge** [comment]
In the last AutoML meeting, we have planned to create a priority list of issues targeted for 1.5.  Once we create that, we can present it in the community meeting.
/cc @andreyvelich

**Comment by andreyvelich** [comment]
Thank you for driving this @jbottum!
Let's target December 7th to present the ROADMAP for the community, since we are going to finalise our list on December 1st in the next AutoML community meeting.

**Comment by jbottum** [comment]
@andreyvelich I have added you to the agenda for Dec 7.

**Comment by andreyvelich** [comment]
Thank you @jbottum, I will present our updates.
