### ISSUE TITLE
Training Operator Roadmap presentation at Kubeflow Community meeting on Nov 23, 30 or Dec 7

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#535]
@johnugeorge @Jeffwan Per the discussion in the Nov 16 Community call, I would like to request that a Kubeflow Training Operator Working Group representative would please present the Training Operator roadmap to the Community during one of these Community calls - Nov 23, 30, or Dec 7.   As discussed, this can be a short presentation ~15 minutes and does not need to be limited to the features that align to KF 1.5 (Jan/Feb).  As our normal process for Community meetings, this meeting should be recorded so that others can listen to it later.    If this request is acceptable and actionable by the Training Operator WG, would you please reply/accept here and then add the Training Operator Review as an item on to the Community notes for an upcoming meeting.  Thanks.    Josh

**Comment by Jeffwan** [comment]
Sounds good. I think let's discuss it internally and reply the thread with proposed date. /cc @kubeflow/wg-training-leads

**Comment by johnugeorge** [comment]
Sounds good

**Comment by Jeffwan** [comment]
Sorry for late response. Can we make it on Dec 7?  @jbottum.

**Comment by Jeffwan** [comment]
I am kind of busy with internal stuff and didn't get chance to attend community meeting. Is the date finalized?

**Comment by terrytangyuan** [comment]
Actually, I will be available on Dec 7 (originally thought it conflicts with my two other talks on Dec 8th) so can present on Dec 7.

**Comment by jbottum** [comment]
@terrytangyuan Dec 7 sounds good.

**Comment by jbottum** [comment]
@terrytangyuan @Jeffwan @johnugeorge You three are on the agenda of the Kubeflow Community call for Dec 7. See you there: https://docs.google.com/document/d/1Wdxt1xedAj7qF_Rjmxy1R0NRdfv7UWs-r2PItewxHpE/edit#

**Comment by terrytangyuan** [comment]
This can be closed. The slides to today's presentation can be found here: https://docs.google.com/presentation/d/17VDIjzlnqByR3bpnYeSeZ3mre32Z825cuu_Uh584eio/edit?usp=sharing

/close
