### ISSUE TITLE
KServe roadmap presentation to KF Community

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#542]
@animeshsingh @yuzisun Per the discussion in the Nov 16 Community call, I would like to request that a KServe representative would please present the KServe roadmap to the Kubeflow Community during one of these Community calls - i.e. Dec 7, 14 or 21. As discussed, this can be a short presentation ~15 minutes and does not need to be limited to the features that align to KF 1.5 (Jan/Feb). As our normal process for Community meetings, this meeting should be recorded (so that others can listen to it later). 

If this request is acceptable and actionable by the KServe team, would you please reply/accept here with a time/date. I will then add to the Community Meeting Agenda.  Thanks. Josh

**Comment by jbottum** [comment]
@pvaneck fyi, here is the request for KServe to present their roadmap to the Kubeflow Community.     If you can pick a Tuesday that works, we will get you on the agenda.

**Comment by pvaneck** [comment]
Possible to this early January? 4th or the week after?
