### ISSUE TITLE
Create a slide deck for Kubeflow 1.5

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#556]
Per the Community process, we need to create a slide deck for Kubeflow 1.5.   Please find a draft of that slide deck here:

https://docs.google.com/presentation/d/1Kd_z8Fzb7xuzIcAhIbGs7sndT1gghGALVi7T_3C_9Gc/edit#slide=id.g1146361f768_0_5

**Comment by jbottum** [comment]
@kubeflow/release-managers. please note that this is a 1st draft.   The information is not validated and it is not for distribution.

**Comment by yhwang** [comment]
@jbottum per your request, I created the tracing issue for IBM IKS here: https://github.com/IBM/manifests/issues/37 
it could be put into your slide 10. thanks. I will update the documentation later

**Comment by jbottum** [comment]
@kubeflow/release-team @johnugeorge @pvaneck @zijianjoy @kubeflow/wg-pipeline-leads    

@kimwnasptd Hi Kimonas - Below please find the link to the raw Kubeflow 1.5 presentation recording.    Could you please ask your team to review and edit appropriately ?    We would like to post this on Tuesday (March 15) and need to provide the final version to @theadactyl.    Please note that Thea needs a few days to review and approve before posting to Kubeflow YouTube so if your team can provide update fairly quickly, it would help.

https://us02web.zoom.us/rec/share/LAME7mLkHr_4Z3zc545CVCdLlJpiz6A7sU2fMptJSwMvO8SOQfMdJho6qXJDKMX-.25VJDPBroyZ-IRl_?startTime=1646928862000 (Passcode: b6@MD&6c)

**Comment by jbottum** [comment]
Note - I am provided the file here as well: 

https://user-images.githubusercontent.com/10553232/157716387-61fbacae-0f4a-4e48-a442-2f93dbacac75.mp4

**Comment by kimwnasptd** [comment]
@jbottum the updated video and thumbnail can be found in

https://drive.google.com/drive/folders/143mOsDt4TgMuYUsUBtVBHiYOv9g2Jroi?usp=sharing

credits to Ben Reutter for the editing work.

**Comment by jbottum** [comment]
@kimwnasptd thanks to you and Ben! 

@theadactyl Hi Thea - Would you please review and post this video to Kubeflow Youtube ?   Thanks.

**Comment by jbottum** [comment]
this has been delivered
