### ISSUE TITLE
Create CSV/Yaml directory in kubeflow/community

### ISSUE THREAD

**Issue by jlewi** [kubeflow/community#57]
I propose we use a csv file in kubeflow/community to list 
  - First Name
  - Last Name
  - GitHub id
  - Slack Id
  - Email (preferably corporate)

This would be entirely opt-in and users could provide a subset of information.

I think this would serve two benefits
  - Short term help folks map user ids across different systems
  - Eventually be used to manage other permissions (e.g. membership in the GitHub org) e.g #49 and access to our release/test infrastructure (#55).

This would  ultimately allow us to use the normal code review process to manage permissions. I think this will be necessary as we continue to grow as a community.

**Comment by ewilderj** [comment]
Maybe company name as well?

**Comment by aronchick** [comment]
WFM!
