### ISSUE TITLE
[RELEASE] Assemble the 1.7 Release Team

### ISSUE THREAD

**Issue by annajung** [kubeflow/community#571]
With Kubeflow 1.6 wrapping up, it's time to **assemble the Kubeflow 1.7 release team**!

It was a great pleasure working with everyone as the release manager for 1.6, and I'm excited to nominate **@DomFleischmann as the next release manager to lead the 1.7 Kubeflow release** 🎉. Dominik has been part of the release team for the last 2-3 releases and has contributed various ways to improve the release process for the community! I am grateful for all his help and am confident he'll be an excellent release manager!

With that, we'd also like to **welcome everyone to participate in the 1.7 release team**! The release team welcomes both new and existing members of the Kubeflow community and is a great way to get started with the project.

Release team members are responsible for working with various WGs, and as part of the release team, you'll be assigned to a specific WG to help with the communications and collection of requirements throughout the release. Note that more than one member can be assigned to the same WG. You can learn more about the Kubeflow release process and the release team in the [release handbook](https://github.com/kubeflow/community/blob/master/releases/handbook.md).

To be part of the release team, **please leave a comment with which working group you like to be assigned to**. We look forward to your involvement!

**The call of participation will close on September 28th at 11:59 pm US Pacific time!**

cc @DomFleischmann @kubeflow/release-team @kubeflow/wg-pipeline-leads @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-automl-leads @kubeflow/wg-training-leads @yuzisun @Tomcli @zijianjoy @jbottum

**Comment by jbottum** [comment]
@annajung thanks for kicking this off.   I am +1 on Dominik's nomination for the 1.7 Release Manager.

**Comment by Rishit-dagli** [comment]
I'd love to shadow under a Docs Lead or a Working Group Liaison

**Comment by annajung** [comment]
Hey @Rishit-dagli, the release handbook is a bit outdated and we no longer have a concept of "shadows". I am working on updating the release handbook and should have a PR open soon.

Instead of shadows, each release team member becomes a WG liaison (list of WG: pipelines, notebook, manifests, katib, training-operator, and kserve) and helps the release team by working closely with the WGs.

If you like to help with docs instead of a specific WG liaison, that would also be helpful as well!

**Comment by Rishit-dagli** [comment]
Thanks for the information @annajung , is there an application for the RT I would;d need to fill after this comment?

I'd love to be a Release Team Member for 1.7 as of the specific WG: I'd like to work with pipelines or training-operator

**Comment by annajung** [comment]
A comment is sufficient and no additional application is needed. Thanks!

**Comment by shivaylamba** [comment]
Hi @annajung I would love to be a Release Team Member for 1.7 within the notebook Working group

**Comment by anencore94** [comment]
If @kubeflow/wg-automl-leads are ok, I'd like to take part of 1.7 release team within the automl(katib) WG. Is there any  opportunity to me?

**Comment by DomFleischmann** [comment]
Thank you for the nomination @annajung ! If there are no objections from the community, I'm more than happy to accept and work with all of you on the 1.7 release.

**Comment by yubozhao** [comment]
Hello everyone. I want to join the next release team and help out wherever possible.

**Comment by DnPlas** [comment]
Hi folks, I would like to continue as a member of the release team.

**Comment by bradleykcardwell** [comment]
I'm interested in contributing as Distribution Liaison for 1.7 please.  
Brad

**Comment by kimwnasptd** [comment]
Hi everyone! I'd like to be involved with this release as well. I can be a liaison for Notebooks WG, but would be more than happy to mentor/help people to handle that alongside me as well.

And of course +1 and happy to see @DomFleischmann being the release manager for KF 1.7!

**Comment by annajung** [comment]
Hi everyone, I also like to continue my involvement to finish up any remaining 1.6-related work and if needed, help with manifest WG

**Comment by surajkota** [comment]
Hi, I would like to continue to be part of release team. I can help out as KServe liaison and happy to share this with anyone since I might be taking a few days off during the cycle.

Will also continue my role as AWS distribution representative.

+1 All the best @DomFleischmann for the upcoming release.

**Comment by gokhancetinkaya** [comment]
I would like to contribute.

**Comment by DomFleischmann** [comment]
Thank you to all the volunteers, given that we have now reached the deadline we will now move ahead with assigning roles to all the volunteers. This will happen on Monday's Release Team Meeting which happens weekly at 18.00 CEST.

If you haven't yet, please follow the [Kubeflow Release Team Calendar](https://calendar.google.com/calendar/u/0/embed?src=c_c5i4tlc61oq2kehbhv9h3gveuo@group.calendar.google.com) which will provide you with meeting details and other important dates around the release. For general communication we will use the [#release channel](https://kubeflow.slack.com/archives/C9V2WT2KV), please make sure you join it. 

Additionally I would also like to ask everyone to join the [kubeflow-discuss google group](https://groups.google.com/g/kubeflow-discuss) it is used to give certain acces permission to community members so it is important for you to join it.

Finally I will tag all the people that I have identified as volunteers, if you are not tagged or you would like to step down from the team please let me know:
@jbottum @annajung @kimwnasptd @DnPlas @surajkota @charlesa101 @bradleykcardwell @yubozhao @anencore94 @shivaylamba @Rishit-dagli 

Again thank you everyone, I'm looking forward to work with all of you! :tada:

**Comment by annajung** [comment]
As discussed in the release team meeting, with the deadline passed and 1.7 formed, I am closing out the issue.
