### ISSUE TITLE
Create an initial Project Board for Kubeflow's transition to the CNCF

### ISSUE THREAD

**Issue by jbottum** [kubeflow/community#584]
The transition of Kubeflow to the CNCF will result in many action items that need to be tracked.   We have discussed created GitHub issues, PRs and a Project Board for this.   We might end up with more than one board over time.  Questions

1) Which Project Board template should be used (classic with automation might be a good choice, but others might have better options).    There is an option with reviewers but I am not sure we need that detail, especially if each item is individually reviewed before progressing to the next state.

2) Which location for the Project Board.   Per Anna Jung's note to us... as Kubeflow members, we all have access to create a [org project board](https://github.com/orgs/kubeflow/projects) like the release board. However, if we want to create a [board in the community repo](https://github.com/kubeflow/community/projects?query=is%3Aopen), we’ll need to request access from James Wu and/or Thea.

3) Reviewers.   So depending on how the Board is set-up, there will be reviewers.   I suspect reviewers will be needed in some cases to set-up the board.    Reviewers will be needed for each item.   I am hoping we can minimize the overhead and just assign appropriate reviewers as needed.

We would like to get this set-up (by Wed, Nov 23 or before) and interested in comments.

**Comment by jbottum** [comment]
@annajung @akgraner @theadactyl

**Comment by annajung** [comment]
I suggest we move forward with the org project board w/ a backlog template. Automated workflows and project views can be modified afterward if we don't find them sufficient. 

As for reviewers, we can assign appropriate people and/or ask the community to review. Once it's reviewed, approvers will depend on which repo the PR is open at.

**Comment by james-jwu** [comment]
Org project board with backlog template sounds good to me.

I already created a project for conformance tests. Do we want to merge that into the master project board? There haven't been much updates some merging them should be lightweight.

**Comment by jbottum** [comment]
@james-jwu do we need to have two boards ?  could we potentially rename the conformance project board?

**Comment by jbottum** [comment]
For reference, I believe this is the conformance board.  I thought that seeing it might help the discussion, https://github.com/orgs/kubeflow/projects/52

**Comment by james-jwu** [comment]
Having 1 board sounds good to me! Sure we could rename the conformance board.

**Comment by annajung** [comment]
Updated the board name - anyone can edit the name so feel free to modify if there's a better name for the board. If we're okay with the board, we can close out this issue and start adding topics from the transition meeting into the board
