### ISSUE TITLE
Add a doc for Kubeflow versioning policy

### ISSUE THREAD

**Issue by annajung** [kubeflow/community#594]
Currently, there is no documentation on the versioning policy for each Kubeflow component and the Kubeflow release. Add a document consolidating all versioning policies from the WG to provide an overview of the versioning scheme used in the project.

cc @jbottum @james-jwu @theadactyl

**Comment by james-jwu** [comment]
PR for creating cncf-transition folder: https://github.com/kubeflow/community/pull/595
