### ISSUE TITLE
Slack channels not being archived

### ISSUE THREAD

**Issue by ewilderj** [kubeflow/community#60]
Until we're in a foundation, paying for Slack is too expensive, so we're currently losing the ability to search all of our history.

All the public archiving options (slackarchive.io, Slark) are not maintained any more.

Solutions include: transition to a FOSS solution such as Rocket Chat, write a bot to archive and provide search facilities (there are some ones that exist, but we'd need a volunteer to operate it.)

**Comment by gaocegege** [comment]
Do we have a plan to be in a foundation?

**Comment by ewilderj** [comment]
Yes, the project intends to be hosted in a foundation. However, two things are not yet clear: the timing, and which foundation. If you go too soon, the bureaucracy can slow progress down. The "which" is a bit clearer: many people favor the CNCF, but there ought to be community consensus about what makes sense. Feel free to talk to Aronchick or Jeremy to get more detail.

To the topic of this bug: For now, we just decided to live with this problem. The archives are not lost, just in accessible. They will be available if we move to a paid Slack plan, or if we decide to export our history into something like Rocket.Chat.
