### ISSUE TITLE
The Invitation to Kubeflow workspace in the Readme is no longer available

### ISSUE THREAD

**Issue by Syulin7** [kubeflow/community#602]
Can someone help update it?

https://github.com/kubeflow/community/blob/13d18b3f8d84267f225edf1af2e4743a16a94caf/slack/README.md?plain=1#L15

**Comment by thesuperzapper** [comment]
I recommend we update it with a link to the kubeflow website, which will always have a working link.

https://www.kubeflow.org/docs/about/community/#kubeflow-slack

**Comment by thesuperzapper** [comment]
@Syulin7 I recommend we update it with a link to the kubeflow website, which will always have a working link.

https://www.kubeflow.org/docs/about/community/#kubeflow-slack

**Comment by thesuperzapper** [comment]
@james-jwu will need to approve since its in the root of the repo.
