### ISSUE TITLE
[RELEASE] Assemble the 1.8 Release Team

### ISSUE THREAD

**Issue by DomFleischmann** [kubeflow/community#620]
With Kubeflow 1.7 being released it is time to assemble the Kubeflow 1.8 Release Team!

I really enjoyed my time working as a Release Manager and I would like to nominate @DnPlas as the next Release Manager to lead the 1.8 Kubeflow Release :partying_face:. Daniela has been part of the Release Team for the last 3 releases and has always been a vocal and proactive member who has helped us deliver these last excellent releases.  I'm grateful for all her help and I believe she will do an excellet job as the next Release Manager!

With that, I would also like to encourage everyone to participate in the 1.8 Release Team! The Release Team welcomes both new and existing members of the Kubeflow community and is a great way to get started with the project.

Release team members are responsible for working with various WGs, and as part of the release team, you'll be assigned to a specific WG to help with the communications and collection of requirements throughout the release. Note that more than one member can be assigned to the same WG. You can learn more about the Kubeflow release process and the release team in the [release handbook](https://github.com/kubeflow/community/blob/master/releases/handbook.md).

To be part of the release team, please leave a comment with which working group you like to be assigned to. We look forward to your involvement!

The call of participation will close  by **end of April**!

cc @DnPlas  @kubeflow/release-team @kubeflow/wg-pipeline-leads @kubeflow/wg-manifests-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-automl-leads @kubeflow/wg-training-leads @jbottum

**Comment by annajung** [comment]
+1 for @DnPlas! 🎉

**Comment by DnPlas** [comment]
I'd be happy to be part of the release team as Release Manager, if the community agrees :)

**Comment by NohaIhab** [comment]
Hi eveyone! I'd like to join the release team for 1.8

**Comment by jbottum** [comment]
+1 for DnPlas

**Comment by nagar-ajay** [comment]
Hello all, I'd like to join the release team for 1.8 as a `Working Group Liaison`.

**Comment by ryansteakley** [comment]
Hello everyone, I'd like to join the release team for 1.8 :)

**Comment by Davidnet** [comment]
"Ahoy, me hearties! 🏴‍☠️ I be seekin' to join ye crew of code-wranglers for the grand voyage of release version 1.8! Permission to come aboard, Cap'n? I promise to keep the bugs walkin' the plank and the features shinin' like doubloons! Arrr! ⚓️"

In all seriousness +1 for @DnPlas and I'd like to join WG Platform - GCP or Pipelines.

**Comment by deepk2u** [comment]
I would like to be part of release team

**Comment by jsitu777** [comment]
hello, SDE from AWS. I'll like to join the Kserve working group for 1.8

**Comment by juliusvonkohout** [comment]
Hello, i would like to join the release team for 1.8

**Comment by shivaylamba** [comment]
Hello I would like to join the release team for 1.8

**Comment by Aditya-171** [comment]
Hi, I would also like to join the release team for 1.8

**Comment by padrian2s** [comment]
Hi all, I'd like to join the release team member for 1.8 for KServe.

**Comment by mobin102** [comment]
Hello, I  like to join the release team for 1.8.

**Comment by SaraSaffari** [comment]
Hi, I would be honored to join for next release. Count me in as a new member :)

**Comment by mostafabayat** [comment]
Hello :)
I would also like to join the release team for 1.8.

**Comment by FullDataAlchemist** [comment]
Greetings,

It is with the utmost respect and reverence that I express my sincere interest in joining the Release Team for version 1.8.

**Comment by PouriaNikvand** [comment]
Hi, It would be a great privilege and honor to be considered as a member of the distinguished Release Team for version 1.8.

**Comment by juliusvonkohout** [comment]
Can anyone see the calendar event for the Release meeting tomorrow?

**Comment by DnPlas** [comment]
Hi everyone, thanks for your interest, this is a great response! Just a reminder, please join us on Monday for an introduction to the release team. The calendar is not available yet, we are sharing the [meeting link](https://meet.google.com/ezk-fmxo-fvu) directly. We should soon have a calendar.

**Comment by juliusvonkohout** [comment]
@DnPlas i have created https://github.com/kubeflow/internal-acls/pull/601

**Comment by DnPlas** [comment]
Thanks everyone for joining last Monday, I will close this issue as we now have assembled the new release team. For more information, please check out the [1.8 Tracking Issue](https://github.com/kubeflow/manifests/issues/2442).

**Comment by Davidnet** [comment]
Hi Daniela I might have lost the invitation but it is right now? Where I could find the link for the calendar?
