### ISSUE TITLE
Archive repository fairing and kfctl

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/community#640]
Hello everyone, the following repositories are not being maintained for two years. I will archive them if there is no objection in two weeks. Refer to the deprecation notices below:

- https://github.com/kubeflow/fairing/issues/573
- https://github.com/kubeflow/kfctl/issues/504

**Comment by thesuperzapper** [comment]
@zijianjoy thanks for this, also, there are a few others:

- the “kfp-tekton-backend” repo: https://github.com/kubeflow/kfp-tekton-backend/issues/76 
- the “chainer-operator” repo: https://github.com/kubeflow/chainer-operator/issues/33 
- the “kubebench” repo: https://github.com/kubeflow/kubebench/issues/232 
- the “fate-operator” repo: https://github.com/kubeflow/fate-operator/issues/37 
- the “kfserving-lts” repo: https://github.com/kubeflow/kfserving-lts/issues/2 
- the “crd-validation” repo: https://github.com/kubeflow/crd-validation/issues/11 
- the “marketing-materials” repo: https://github.com/kubeflow/marketing-materials/issues/5 
- the “community-infra” repo: https://github.com/kubeflow/community-infra/issues/35

**Comment by thesuperzapper** [comment]
Personally, I think those ones are so inactive, we can just archive them if we both agree.

**Comment by zijianjoy** [comment]
Hello @thesuperzapper , appreciate that you raising the question to other repos. We can discuss about them after we have archived the two repos in the title of this issue.

**Comment by johnugeorge** [comment]
@zijianjoy  Can you archive https://github.com/kubeflow/common as well ?  
Ref: https://github.com/kubeflow/common/issues/218

/cc @terrytangyuan  @gaocegege @tenzen-y

**Comment by terrytangyuan** [comment]
Sounds good to me regarding common repo

**Comment by zijianjoy** [comment]
Thank you everyone for the input.

fairing and kfctl have been archived. I created a new issue regarding archiving another two repos: https://github.com/kubeflow/community/issues/644. Please comment there.

Closing this issue since the original intent is fulfilled.
