### ISSUE TITLE
Archive repository common and kfp-tekton-backend

### ISSUE THREAD

**Issue by zijianjoy** [kubeflow/community#644]
Hello everyone, the following repos are requested to be archived. I will archive them if there is no objection in two weeks. Refer to the deprecation notices below:

- https://github.com/kubeflow/kfp-tekton-backend/issues/78
- https://github.com/kubeflow/common/issues/219

**Comment by tenzen-y** [comment]
+1 to `Deprecation notice: kubeflow/common repo will be archived in two weeks.  common#219`.

cc: @johnugeorge @terrytangyuan

**Comment by terrytangyuan** [comment]
+1
