### ISSUE TITLE
Wrong security WG links provided in the community callendar

### ISSUE THREAD

**Issue by difince** [kubeflow/community#649]
Wrong Security group links provided in the community calendar:

https://github.com/kubeflow/community/blob/de7e370d09b5e744e72c7ae678242d40438ba5d4/calendar/calendar.yaml#L365-L367

In my understanding, the new meeting notes link is: [https://docs.google.com/document/d/1xGkg9GuO2OjvYhdONJFbSrpF66UKhtYonczttJoTv3s/edit?usp=sharing](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1xGkg9GuO2OjvYhdONJFbSrpF66UKhtYonczttJoTv3s%2Fedit%3Fusp%3Dsharing&data=05%7C01%7Cdianaa%40vmware.com%7C059a3d2af5064f45a21c08db560ddf2b%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C638198389841133265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=uR%2FdvvwxsL4vALFnkpANTj2rHgMB0rgWwEeqnkELYIY%3D&reserved=0)  

and the Zoom link: 
```
Join Zoom Meeting
[https://us06web.zoom.us/j/87118537300?pwd=NG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Furl%3Fq%3Dhttps%253A%252F%252Fus06web.zoom.us%252Fj%252F87118537300%253Fpwd%253DNG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09%26sa%3DD%26ust%3D1684674120000000%26usg%3DAOvVaw3rCCWlG6xPMPkX4yXwV0eX&data=05%7C01%7Cdianaa%40vmware.com%7C059a3d2af5064f45a21c08db560ddf2b%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C638198389841133265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=Cx%2BhxkwzkkyhO4Jo3yFX69%2BMBX%2BEFKVlkarXcOqj9tI%3D&reserved=0)

Meeting ID: 871 1853 7300
Passcode: 273734
```
cc: @akgraner

**Comment by thesuperzapper** [comment]
@difince The link you made is to a very old version of the calendar yaml, for reference, here is the security meeting on the new structure:

https://github.com/kubeflow/community/blob/76e1ed4b7b8d3fbe952056143d6d8e66f91c1234/calendar/calendar.yaml#L91-L100

Is this one correct?

**Comment by difince** [comment]
Hi @thesuperzapper 
My bad, the link provided by me is to an old commit, yes- apologies about that.  But still, the content is the same as what is in the current version of `calendar.yaml` file. 

IMO the correct links are: 

> In my understanding, the new meeting notes link is: [https://docs.google.com/document/d/1xGkg9GuO2OjvYhdONJFbSrpF66UKhtYonczttJoTv3s/edit?usp=sharing](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1xGkg9GuO2OjvYhdONJFbSrpF66UKhtYonczttJoTv3s%2Fedit%3Fusp%3Dsharing&data=05%7C01%7Cdianaa%40vmware.com%7C059a3d2af5064f45a21c08db560ddf2b%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C638198389841133265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=uR%2FdvvwxsL4vALFnkpANTj2rHgMB0rgWwEeqnkELYIY%3D&reserved=0)

> and the Zoom link:
> 
> Join Zoom Meeting
> [https://us06web.zoom.us/j/87118537300?pwd=NG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.google.com%2Furl%3Fq%3Dhttps%253A%252F%252Fus06web.zoom.us%252Fj%252F87118537300%253Fpwd%253DNG5ibWN0N2YxUGR5Y2NXSXRiN0FGZz09%26sa%3DD%26ust%3D1684674120000000%26usg%3DAOvVaw3rCCWlG6xPMPkX4yXwV0eX&data=05%7C01%7Cdianaa%40vmware.com%7C059a3d2af5064f45a21c08db560ddf2b%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C1%7C638198389841133265%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=Cx%2BhxkwzkkyhO4Jo3yFX69%2BMBX%2BEFKVlkarXcOqj9tI%3D&reserved=0)
> 
> Meeting ID: 871 1853 7300
> Passcode: 273734

**Comment by thesuperzapper** [comment]
Resolved by https://github.com/kubeflow/community/pull/651

/close
