### ISSUE TITLE
[kubeflow 1.8] Documentation changes for 1.8 release

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/community#654]
This issue is for tracking the required changes in public documentation for the upcoming release.

These are the items we have to work on:
* https://www.kubeflow.org/docs/releases/kubeflow-1.7/ - we need to create the same entry for 1.8
* https://blog.kubeflow.org/kubeflow-1.7-release/ - this is the blog post that we publish on the release day. We should work closely with the WGs to get accurate information about features and improvements.
* Additionally we want to make sure this information is still relevant and accurate: https://github.com/kubeflow/kubeflow/blob/master/ROADMAP.md#kubeflow-18-release-planned-for-release-oct-2023
* Presentation for 1.8 release

**Comment by Davidnet** [comment]
Small draft with the updated announcements given in the kubeflow summit:

https://docs.google.com/document/d/1CWJ1gV9H7s8xfyQ1JAhUw2ackOpjKs23WAfSgIzttw4/edit?usp=sharing

**Comment by Davidnet** [comment]
Docs for component version:
https://docs.google.com/document/d/1VQsHkUcUJpqRwv4Sx_dhe-sl4kMq1WHGCN8R2e5IYTk/edit?usp=sharing

Docs for draft v2:
https://docs.google.com/document/d/1SiXI_LMuUscZTG7H17Wdf3ctkygex3pKLNO5jjwf_a4/edit?usp=sharing

**Comment by Davidnet** [comment]
PR in here: https://github.com/kubeflow/blog/pull/138

@kubeflow/release-team 
@jbottum

**Comment by DnPlas** [comment]
Closing this issue as all the documentation has been published. Thanks @Davidnet !
