### ISSUE TITLE
Understand CNCF guidelines

### ISSUE THREAD

**Issue by annajung** [kubeflow/community#656]
Part of https://github.com/cncf/toc/issues/1139

As part of the onboarding to CNCF, Kubeflow community must fulfill the following requirements.
- Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
- Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
- Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
- Understand the trademark guidelines: https://www.linuxfoundation.org/legal/trademark-usage
- Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist

To cross this requirement off the list, the ask is for WG leads and interim steering committees to read the following guidelines and docs provided by CNCF and **provide a comment on this issue to indicate completion of the requirements above**.

The list below will be used to keep track of each WG and the steering committee's progress. Each steering committee should review the doc and provide an update on their completion. As for WGs, it would be ideal to have 2 reps from each WG to participate, 1 being the absolute minimum.

- [x] Interim Steering Committee
  - [x] @jbottum 
  - [x] @james-jwu 
  - [x] @theadactyl 
- [x] Katib
  - [x] @tenzen-y 
  - [x] @johnugeorge  
  - [x] @andreyvelich 
- [x] Manifests
  - [x] @kimwnasptd 
  - [x] @elikatsis 
  - [x] @juliusvonkohout  
- [x] MPI Operator
  - [x] @terrytangyuan
  - [x] @alculquicondor  
- [x] Notebooks
  - [x] @kimwnasptd 
  - [x] @elikatsis 
  - [x] @thesuperzapper   
- [x] Pipelines
  - [x] @chensun  
  - [x] @zijianjoy 
  - [x] @james-jwu
- [x] Pipelines on Tekton
  - [x] @yhwang 
  - [x] @Tomcli 
  - [x] @ScrapCodes 
- [x] Training Operators
  - [x] @terrytangyuan
  - [x] @tenzen-y 
  - [x] @johnugeorge 
  - [x] @andreyvelich  

cc
Interim Steering Committee @james-jwu @theadactyl @jbottum 
[Katib](https://github.com/kubeflow/katib/blob/master/OWNERS): @andreyvelich @gaocegege @johnugeorge @tenzen-y
[Manifests](https://github.com/kubeflow/manifests/blob/master/OWNERS): @elikatsis @kimwnasptd @PatrickXYS @StefanoFioravanzo @yanniszark
[MPI Operator](https://github.com/kubeflow/mpi-operator/blob/master/OWNERS): @alculquicondor @rongou @terrytangyuan
[Notebooks](https://github.com/kubeflow/kubeflow/blob/master/components/OWNERS): @elikatsis @kimwnasptd @thesuperzapper @StefanoFioravanzo @yanniszark
[Pipelines](https://github.com/kubeflow/pipelines/blob/master/OWNERS): @chensun @zijianjoy @james-jwu @IronPan
[Pipelines on Tekton](https://github.com/kubeflow/kfp-tekton/blob/master/OWNERS): @animeshsingh @ckadner @fenglixa @pugangxa @ScrapCodes @Tomcli @yhwang
[Training Operators](https://github.com/kubeflow/training-operator/blob/master/OWNERS): @gaocegege @Jeffwan @johnugeorge @zw0610 @terrytangyuan @tenzen-y @andreyvelich

Any members are encouraged to participate to familiarize themselves with the CNCF guidelines!

**Comment by terrytangyuan** [comment]
Thanks for opening this issue to track! I have read all the listed guidelines.

**Comment by zijianjoy** [comment]
Thank you so much @annajung ! I have read the list of guidelines.

**Comment by yhwang** [comment]
@annajung Thanks for the list. I have read the guidelines and docs.

**Comment by Tomcli** [comment]
I have read the list of guidelines. Thank you @annajung.

**Comment by james-jwu** [comment]
I have read the list of guidelines. Thank you @annajung

**Comment by chensun** [comment]
I have read the list of guidelines. Thank you @annajung

**Comment by tenzen-y** [comment]
I have read the guidelines. Thank you. @annajung

**Comment by johnugeorge** [comment]
I have read the guidelines. Thank you

**Comment by annajung** [comment]
As discussed during the community call today, tagging the security team and release team to encourage participation (optional)

cc @kubeflow/release-team @juliusvonkohout @kimwnasptd @akgraner

**Comment by jbottum** [comment]
I have read the guidelines

**Comment by Davidnet** [comment]
I have read the guidelines

**Comment by juliusvonkohout** [comment]
I have also taken a look at the guidelines. Interesting is the AGPL absence.

**Comment by ScrapCodes** [comment]
I have also taken a look at the guidelines and understood it.

**Comment by andreyvelich** [comment]
I have read the guidelines, thank you for providing this @annajung!

**Comment by alculquicondor** [comment]
I read the guidelines, thanks!

**Comment by kimwnasptd** [comment]
Thank you so much @annajung ! I have also read the list of guidelines.

**Comment by elikatsis** [comment]
I have read and understood the guidelines. Thank you!

**Comment by thesuperzapper** [comment]
I read the guidelines, thanks!

**Comment by juliusvonkohout** [comment]
@annajung can you add me to the manifests list given https://github.com/kubeflow/manifests/commit/a684c723a1aba78dee5eca96276a7ee281563f77

**Comment by annajung** [comment]
Hi @theadactyl, could you please acknowledge completing the requirements above as part of the steering committee?

**Comment by zijianjoy** [comment]
Internally pinged @theadactyl and will review this requirement soon.

**Comment by theadactyl** [comment]
I have read and understood the guidelines!

**Comment by annajung** [comment]
Yes! Thanks everyone, will close this and mark this task as completed. 

/close
