### ISSUE TITLE
[RELEASE] Assemble the 1.9 release team

### ISSUE THREAD

**Issue by DnPlas** [kubeflow/community#660]
With Kubeflow 1.8 being released it is time to assemble the Kubeflow 1.9 Release Team!

I really enjoyed my time working as a Release Manager and I would like to nominate @Davidnet as the next Release Manager to lead the 1.9 Kubeflow Release 🥳. David was a key member of the Release Team for the last release and has always been a vocal and proactive member who has helped us deliver these last excellent releases. I'm confident David will execute a great job to continue driving an excellent project!

> Please note the release manager role hasn't been decided, and it's still open for anyone in the community.

With that, I would also like to encourage everyone to participate in the 1.9 Release Team! The Release Team welcomes both new and existing members of the Kubeflow community and is a great way to get started with the project.

You can learn more about the Kubeflow release process and the release team in the [release handbook](https://github.com/kubeflow/community/blob/master/releases/handbook.md).

To be part of the release team, please leave a comment with which working group you like to be assigned to. We look forward to your involvement!

cc @Davidnet  @kubeflow/wg-automl-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @kubeflow/wg-manifests-leads @jbottum

**Comment by annajung** [comment]
Thank you @DnPlas for all your great work with the 1.8 release! 

+1 for @Davidnet as 1.9 release manager!

**Comment by diegolovison** [comment]
Could we have a goal for 1.9? 
Example: be able to deploy KubeFlow in Minikube ( or something else ) in a machine with a CPU with 20 cores, 64GB of memory.

**Comment by thesuperzapper** [comment]
> Could we have a goal for 1.9? Example: be able to deploy KubeFlow in Minikube ( or something else ) in a machine with a CPU with 20 cores, 64GB of memory.

I don't know if this is a serious comment, but if it is, you can already deploy Kubeflow in Minikube.

If you want the fastest way, try out [deployKF](https://www.deploykf.org/), which has a [local quickstart](https://www.deploykf.org/guides/local-quickstart/) guide.

**Comment by thesuperzapper** [comment]
> Could we have a goal for 1.9? Example: be able to deploy KubeFlow in Minikube ( or something else ) in a machine with a CPU with 20 cores, 64GB of memory.

@diegolovison I don't know if this is a serious comment, but if it is, you can already deploy Kubeflow in Minikube.

If you want the fastest way, try out [deployKF](https://www.deploykf.org/), which has a [local quickstart](https://www.deploykf.org/guides/local-quickstart/) guide.

**Comment by diegolovison** [comment]
Yeah! :)
I tried from the raw manifests https://github.com/kubeflow/manifests/tree/v1.8-branch and wasn't able to make it working.
I would like to have it working with "plain" KubeFlow

**Comment by johnugeorge** [comment]
@diegolovison There should not be any issues with Minikube. What issues are you seeing? Please create an issue with kubeflow/manifests repo

**Comment by diegolovison** [comment]
Good to hear @johnugeorge 
I created a thread in #general in Slack a few weeks ago.
Nothing to worry about.

For 1.9, I can work closer with @rimolive and be responsible for testing with Minikube.

**Comment by ca-scribner** [comment]
I'll join the release team.  I'm flexible, but would prefer assignment to the AutoML WG

**Comment by stevei101** [comment]
Hello, would liek to be part of the release team.  Flexible!

**Comment by juliusvonkohout** [comment]
I can be the security liaison again.

**Comment by nagar-ajay** [comment]
I would like to join the release team. I can be the Training Operator WG liaison again. Open for other roles as well.

**Comment by rimolive** [comment]
@stevei101 Are you on Kubeflow slack? I'd like to invite you in the release meetings as well the release team Slack channel.
