### ISSUE TITLE
Nominations Phase for the 2023 Kubeflow Project Steering Committee Elections - Now Open

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#670]
### The Nominations Phase for the 2023 Kubeflow Project Steering Committee Elections are now open. 

The nominations phase will be open starting at **9:00am Pacific Time on 11 December 2023**  and will remain open until **12:00pm Pacific Time on 24 December 2023.** 

If you would like to nominate yourself or someone from the community and are [listed on the eligible candidates list](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2023-KSC.md), please add your name or the person you are nominating's name in a comment on this issue.   

**Please note:** _Names added before the start time or after the ending time will not be considered.  Only add names during the time the Nominations Phase is open._  If a name is added and they are not on the [eligible candidates list](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2023-KSC.md) they will not be considered. 

**ONLY ADD THE NAME TO THE COMMENT.** - All those nominated will work with the elections officers to create a file that lists supporting information on why this nominee should be considered. 

More information: 
- [Kubeflow Project Steering Committee Elections 2023](https://github.com/kubeflow/community/blob/master/elections/kubeflow-steering-committee-elections-2023.md)
- [List of Eligible Voters and Candidates](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2023-KSC.md)

**Comment by rimolive** [comment]
I would like to nominate @terrytangyuan for the Kubeflow Steering Committee

**Comment by akshaychitneni** [comment]
I would like to nominate @andreyvelich for the Kubeflow Steering Committee

**Comment by nsingl00** [comment]
I would like to nominate @andreyvelich for the Kubeflow Steering Committee

**Comment by TobiasGoerke** [comment]
I'll nominate @juliusvonkohout

**Comment by juliusvonkohout** [comment]
I think this is the list from where the voters and candidates were gathered https://kubeflow.devstats.cncf.io/d/48/users-statistics-by-repository-group?orgId=1&var-period=y&var-metric=activity&var-repogroup_name=All&var-users=All&from=now-1y&to=now

**Comment by thesuperzapper** [comment]
Hey all, nominations must come from people who are [themselves eligible to vote](https://github.com/kubeflow/community/blob/master/proposals/kubeflow-steering-committee-election-proposal.md#candidate-eligibility), either through contribution or exception granted by the election officials: 

- ![Screenshot 2023-12-12 at 16 07 46](https://github.com/kubeflow/community/assets/5735406/f7b2b394-dbd6-40c6-b6eb-d8ff98b208a0)

So for the sake of argument (given that some of the above nominations come from people who are not eligible), I am happy to nominate @terrytangyuan and @andreyvelich (because I also think they would be great).
(Assuming they were being nominated willingly).

_NOTE: @TobiasGoerke was eligible, so his nomination for @juliusvonkohout was already valid._

---

### For context, the people who can nominate (or be nominated) are [__listed here__](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2023-KSC.md).

**Comment by andreyvelich** [comment]
Thank you for pointing to this @thesuperzapper!
Due to this discussion, I was thinking anyone can nominate folks from the eligible list: https://kubeflow.slack.com/archives/C068Y499C3A/p1702316137925719?thread_ts=1702313980.848019&cid=C068Y499C3A

**Comment by akgraner** [comment]
I'd like to stress, people can **SELF NOMINATE** if they are an eligible candidate.  **If you are eligible** and **believe you would be a good leader** and member of the KSC, then don't wait for someone else to nominate you, **nominate yourself**.

**Comment by thesuperzapper** [comment]
I would like to nominate myself, @thesuperzapper.

**Comment by kimwnasptd** [comment]
Super happy with all the nominations I see, and great to see everyone!

I'd also like to nominate myself, @kimwnasptd

**Comment by SachinVarghese** [comment]
I would like to nominate @johnugeorge for the KSC.

**Comment by difince** [comment]
Hi everyone. It's great to see all the nominations! I also plan to vote but I have a question - Can I nominate more than one person?

**Comment by thesuperzapper** [comment]
@difince there is no rule which says you can't, but obviously confirm with the people you are nominating that they want to stand.

**Comment by difince** [comment]
I would like to nominate @juliusvonkohout , @kimwnasptd and @andreyvelich

**Comment by akgraner** [comment]
@thesuperzapper @kimwnasptd @juliusvonkohout @andreyvelich @johnugeorge @terrytangyuan  - you all have been added to the #ksc-nominees private slack channel.  Please fill out the form that is shared in that channel. 

@Davidnet @jbottum @james-jwu  - I've also added you all to that channel as well.

If anyone else is nominated before the deadline I'll also add those individuals.

**Comment by akgraner** [comment]
The nominations phase is now closed.
