### ISSUE TITLE
Kubeflow Steering Committee Elections - Testimonial Phase - Andrey Velichkevich

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#674]
**Andrey Velichkevich**

**LinkedIn:** [https://www.linkedin.com/in/andrey-velichkevich/](https://www.linkedin.com/in/andrey-velichkevich/)

**Github:** [https://github.com/andreyvelich](https://github.com/andreyvelich)

Q: **Why do you think you would be a good candidate for the Kubeflow Steering Committee?**

Over the past 5.5 years, I have actively and consistently engaged with the Kubeflow community which demonstrates long-term commitment to this open-source project. I contributed to nearly all Kubeflow components, CI/CD, documentation, and releases. I played a leadership role in introducing new features and enhancement proposals for Kubeflow, e.g. adding Neural Architecture Search and Early Stopping support into Katib and creating the unify Training Operator.

My commitment extends to enhance the Kubeflow user experience through the development of improved Python SDKs, working on LLM APIs, and participating in technical proposal reviews and community meetings. As the co-chair of the AutoML and Training WGs, I regularly conduct WG community meetings and contribute to the success of Kubeflow summits. During the critical issues, I played a pivotal role, exemplified by leading the migration of Kubeflow’s CI/CD infrastructure from GCP to AWS, ensuring stability of Kubeflow development and releases.

My proactive approach to grow the Kubeflow community represents in various initiatives. For instance, I found folks from different companies willing to maintain Spark Operator under Kubeflow components, leading the proposal to donate Spark Operator to Kubeflow. This integration aims to bridge the gap between Big Data and ML Ecosystem, which is extremely important for Kubeflow users and ML industry. Additionally, I initiated the Data WG proposal for Model Registry and Spark Operator, demonstrating my commitment to enhance Kubeflow functionalities and expanding its scope.

In addition to that, I constantly talk about Kubeflow at many conferences like KubeCon, ArgoCon, Kubernetes AI Day, RE:WORK, etc., organised virtual Kubeflow AutoML and Training WG summit, collaborated with other open-source communities (e.g. Jupyter, Optuna, Spark), and authored a few Kubeflow blog posts. My interactions with Kubeflow users have provided valuable insights into their use-cases, allowing us to continue improving Kubeflow usability. Furthermore, I successfully onboarded and mentored numerous new contributors, helping them to understand the Kubeflow ecosystem.

I worked on the due diligence document, facilitating the successful donation of Kubeflow project to the CNCF foundation. Currently, I am actively engaged in a new CNCF AI WG initiative, articulating to the CNCF community why Kubeflow should play a key role in this new WG, considering Kubeflow’s experience and widespread adoption in the cloud-native AI/ML space.

In summary, my extensive experience and passion for the Kubeflow project position me as a valuable candidate for the Kubeflow Steering Committee. I am confident that being part of Kubeflow Steering Committee allows me to drive Kubeflow project forward and play a crucial role in its evolution as the outstanding open-source platform for AI/ML on Kubernetes.

Q: **How long have you been involved in the Kubeflow Community?  What projects have you been actively involved with?**

I’ve been involved in the Kubeflow community for 5.5 years since July 2018.

I was involved in many Kubeflow components such as Katib, Training Operator, Kubebench, Tensorflow and PyTorch Operator, Pipelines. Also, I helped community with Kubeflow CI/CD infrastructure, documentation, and releases.

Q: **How long have you been involved in open-source?**  

6 years

Q:  **Is there anything else you would like the community to know about you that you believe would help eligible voters make there decision?**

After engaging in conversations with many Kubeflow customers, I've identified the following key items that I would like to address working with Steering Committee and Kubeflow community:

1. Helping bridge the big data & ML ecosystems given enterprise use-cases while maintaining extensibility and a pluggable open architecture.

2. Making a great Jupyter based experience help increase and improve Kubeflow adoption for ML purposes.

3. Having a keen eye towards stitching the components together to create a turnkey solution for ML to improve productivity of ML practitioners with a focus on creating a great integrated Kubeflow product experience

I believe working on those items allows us to make Kubeflow more robust, user-friendly, and cohesive AI/ML platform on Kubernetes.

Q: **Links to any external sites (projects, hobbies, etc) that you would like to share that would help people make a decision about.**

Presentation where I talked about Kubeflow:
1. KubeCon 2023 NA - The Future of Interactive Data Science at Scale with Jupyter and Kubeflow - https://youtu.be/sn2qe225E1o

2. RE:WORK 2023 - Hiding Kubernetes Complexity for ML Engineers Using Kubeflow - https://youtu.be/Cj5NTTL000k

3. ArgoCon 2022 - Managing Thousands of Automatic Machine Learning Experiments with Argo and Katib - https://youtu.be/0jBNXZjQ01I

4. Kubernetes AI Day 2021 EU - Case Study: Developing and Scaling Kubeflow’s Web Apps - https://youtu.be/1EUvVu41uhE

5. MLREPA 2021 - MLOps and AutoML in Cloud-Native Way with Kubeflow and Katib - https://youtu.be/33VJ6KNBBvU

AutoML and Training WG Summit 2021 that I initiated:
https://youtu.be/Hblh9HvVlxg?list=PL2gwy7BdKoGd9HQBCz1iC7vyFVN7Wa9N2

Blog posts and papers:
1. Kubeflow Katib: Scalable, Portable and Cloud Native System for AutoML - https://blog.kubeflow.org/katib/

2. Katib: A Distributed General AutoML Platform on Kubernetes - https://www.usenix.org/system/files/opml19papers-zhou.pdf

**Comment by jbottum** [comment]
Andrey stands as a distinguished multi-year contributor to the Kubeflow community, leaving a lasting impact through critical contributions. As a dedicated code contributor in two essential working groups, Andrey’s expertise extends to comprehensive documentation efforts. Displaying leadership qualities, Andrey has taken on the role of working group lead for two separate teams, showcasing a profound commitment to the success of Kubeflow. Additionally, as a Working Group Lead, Andrey exemplifies organizational and coordination skills, while actively mentoring to nurture talent within the community. Andrey has shared valuable insights as a Kubeflow speaker at a variety of conferences and venues, contributing significantly to the dissemination of knowledge. Notably, Andrey's unwavering commitment to the Kubeflow community persists through changes in employment. Based in Europe, Andrey brings a crucial international perspective to the collaborative and global efforts of the Kubeflow ecosystem.  These qualifications make Andrey a great candidate for the Kubeflow Steering Committee.

**Comment by kimwnasptd** [comment]
Josh and Andrey have expressed almost everything perfectly!

Aside from all the above I have to comment Andrey on his great ability to drive efforts and contributors efforts. He is excellent both in the technical aspect, making sure all the details have been discussed, as well as how he handles all the conversations.

Always having in mind the end final result and encouraging contributors along the way!
