### ISSUE TITLE
Kubeflow Steering Committee Elections - Testimonial Phase - Julius von Kohout

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#676]
**Julius von Kohout**

**LinkedIn:** [https://www.linkedin.com/in/juliusvonkohout/](https://www.linkedin.com/in/juliusvonkohout/)

**Github:** [https://github.com/juliusvonkohout](https://github.com/juliusvonkohout)

Q: **Why do you think you would be a good candidate for the Kubeflow Steering Committee?**

1. I worked across most working groups for almost 4 years and I am leading the manifests and security working group. 
2. Quite often i also play the stalebot for github issues and PRs and I brought at least a handful of new contributors to the project. 
3. Furthermore I do a lot of architectural and security stuff which is essential for enterprise adoption and therefore funding of existing and new developers. 
4. Last but not least I manage the Kubeflow Platforms at DHL, but DHL is not selling a Kubeflow distribution externally. So I can be unbiased but still bring in enterprise experience.

Q: **How long have you been involved in the Kubeflow Community?  What projects have you been actively involved with?**

Around 4 years. I also worked on Argo, Jupyter, Sparkmagic and Ray

Q: **How long have you been involved in open-source?**  

Probably more than a decade

Q:  **Is there anything else you would like the community to know about you that you believe would help eligible voters make there decision?**

I want to keep political and ideological issues out of the project and strongly support meritocracy.

Q: **Links to any external sites (projects, hobbies, etc) that you would like to share that would help people make a decision about.**

**Comment by jbottum** [comment]
Julius stands as a distinguished multi-year contributor to the Kubeflow community, leaving a lasting impact through critical contributions. As a dedicated code contributor, his expertise extends to comprehensive documentation efforts. Displaying leadership qualities, Julius has taken on the role of Security Team Lead and has lead our integration with Ray, showcasing a profound commitment to the success of Kubeflow. Additionally, while leading these projects Julius has exemplified organizational and coordination skills, while actively mentoring to nurture talent within the community. Julius has shared valuable insights as a Kubeflow speaker at a variety of conferences and venues, contributing significantly to the dissemination of knowledge. Notably, his unwavering commitment to the Kubeflow community persists through changes in employment. Based in Europe, Julius brings a crucial international perspective to the collaborative and global efforts of the Kubeflow ecosystem.  These qualifications make Julius a great candidate for the Kubeflow Steering Committee.

**Comment by kromanow94** [comment]
Julius has the patience, approach, expertise and skills that make him a great lead. He helped me to join the Manifests WG, still helps on my contributions and is always helpful and kind when I'm in doubt.

**Comment by TobiasGoerke** [comment]
Julius is a standout candidate for the Kubeflow Steering Committee. His dedication to steering Kubeflow toward success is evident in his persistent and rigorous work. He's fostering a welcoming environment for newcomers and focuses on driving Kubeflow's alignment with enterprise needs, demonstrating a deep understanding of innovation. Julius's proactive approach, inclusive mindset, and commitment to Kubeflow's enterprise relevance mark him as an invaluable asset for the Steering Committee.

**Comment by kimwnasptd** [comment]
Fully agree with all the above comments! 

Julius strikes a very good balance on enabling new efforts, while adhering and improving Kubeflow's (technical and non) standards, and at the same time not becoming pedantic and staying focused on integrating the efforts.

At the same time he is always invested in helping contributors to both get more involved and also extend Kubeflow, like with Ray.

**Comment by akgraner** [comment]
closing this issue
