### ISSUE TITLE
Kubeflow Steering Committee Elections - Testimonial Phase - Kimonas Sotirchos

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#677]
**Kimonas Sotirchos**

**LinkedIn:** [https://www.linkedin.com/in/kimonas-sotirchos-1ba45b155/](https://www.linkedin.com/in/kimonas-sotirchos-1ba45b155/)

**Github:** [https://github.com/kimwnasptd](https://github.com/kimwnasptd)

Q: **Why do you think you would be a good candidate for the Kubeflow Steering Committee?**

I've been around during both community and governance shaping decisions of the project and have been involved to almost all Working Groups of the project. Aside from my personal ambitions on how to improve the project I'm proud of my ability to enable fruitful conversations and drive them to actionable decisions.

The past 5 years I've 
1. been a lead in 2 Working Groups of Kubeflow (Notebooks and Manifests)
2. have founded the [release process](https://github.com/kubeflow/manifests/pull/1907) of Kubeflow
3. have been a release manager for 2 releases
4. have been a [GSoC mentor](https://summerofcode.withgoogle.com/archive/2020/projects/6613367730470912) for the project

Lastly, the last 5 years I've worked at companies (Arrikto and Canonical) that have been contributing and distributing Kubeflow. This has given me both 
* the privilege of knowing the project from the inside out
* the drive to keep on pushing for the growth of Kubeflow and its vibrant community

Q: **How long have you been involved in the Kubeflow Community?  What projects have you been actively involved with?**

5 years. My initial contributions were around the web apps and K8s Controllers for managing Notebooks, but soon expanded to other core components like user management, service mesh architecture and security as well as the installation process and the manifests of the project.

I've also been involved with the AutoML Working Group and KServe, to ensure they have web apps integrated with Kubeflow. Have lead team of engineers that worked on the different parts of the Working Groups, and have also been a GSoC mentor for Kubeflow.

On the manifests side, one of the notable efforts I've worked on was the founding of the release process and cleaning up Kubeflow's [addons](https://github.com/kubeflow/manifests/tree/master/contrib) and setting up expectations around them.

Q: **How long have you been involved in open-source?**  

6 years

Q:  **Is there anything else you would like the community to know about you that you believe would help eligible voters make there decision?**

The biggest areas I'd like to focus on are around enabling new efforts for the project, and making the answer to the question "what is Kubeflow" more clear. 

This will enable us, as a community, to:
1. Have a common understanding on the areas we need to improve
2. Have a process on how new efforts should be organized and scoped
3. Have a clear direction on how to better improve parts of the docs
4. Focus on exposing the core Kubeflow decisions and architecture, so that end-users can better know how to further modularize different pieces

Q: **Links to any external sites (projects, hobbies, etc) that you would like to share that would help people make a decision about.**

**Comment by jbottum** [comment]
Kimonas stands as a distinguished multi-year contributor to the Kubeflow community, leaving a lasting impact through critical contributions. As a dedicated code contributor in two essential working groups, Kimonas' expertise extends to comprehensive documentation efforts. Displaying leadership qualities, Kimonas has taken on the role of working group lead for two separate teams, showcasing a profound commitment to the success of Kubeflow. Additionally, as a Release Team Manager, Kimonas exemplifies organizational and coordination skills, while actively mentoring within the Release team to nurture talent within the community. Kimonas has shared valuable insights as a speaker at Kubeflow conferences, contributing significantly to the dissemination of knowledge. Notably, Kimonas' unwavering commitment to the Kubeflow community persists through changes in employment. Based in Europe, Kimonas brings a crucial international perspective to the collaborative and global efforts of the Kubeflow ecosystem.   These qualifications make Kimonas a great candidate for the Kubeflow Steering Committee.

**Comment by thesuperzapper** [comment]
I have worked with Kimonas over the past few years as co-leads of the Notebooks Working Group and as part of numerous releases. I share and admire his dedication to the Kubeflow project and believe that he would be a great addition to the Kubeflow steering committee.

**Comment by TobiasGoerke** [comment]
Kimonas is a pivotal figure in the development of Kubeflow's core components. He has vitally guided my contributions on multiple occasions and shown great leadership as well as a clear vision to guide and shape the platform's evolution. Kimonas possesses an open-minded approach, welcoming new ideas and fostering an environment ripe for innovation. His approachability coupled with an impressive depth of knowledge about Kubeflow makes him an invaluable asset to the community.

**Comment by andreyvelich** [comment]
While collaborating with Kimonas on various Kubeflow components, he demonstrated leadership and a deep understanding of the Kubeflow project. He played a crucial role in Kubeflow releases, UIs, and Notebooks. His contributions to the release process had a significant impact on the project future. For instance, we achieved five successful releases since establishing the Kubeflow release handbook.

Kimonas did an excellent job of revamping the Kubeflow UIs (e.g. for Katib, Notebooks, KServe, etc) to provide Kubeflow users a simple and unified experience across various Kubeflow components.

Furthermore, Kimonas consistently assists new contributors and growing our community which shows his long-term commitment to the Kubeflow project.

**Comment by juliusvonkohout** [comment]
Fully agree with all the above comments :-)

I am working with Kimonas for a really long time now hope that he continues pushing the boundaries of Kubeflow.
