### ISSUE TITLE
Kubeflow Steering Committee Elections - Testimonial Phase - Mathew Wicks

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#678]
**Mathew Wicks**

**LinkedIn:** [https://www.linkedin.com/in/mathewwicks/](https://www.linkedin.com/in/mathewwicks/)

**Github:** [https://github.com/thesuperzapper](https://github.com/thesuperzapper)

Q: **Why do you think you would be a good candidate for the Kubeflow Steering Committee?**

I am a neutral voice who will always put the community's needs and ideas first. I strongly believe the best ML Platform can be open-source and developed by everyone. I have been involved in Kubeflow for a number of years, and have made significant amounts of technical and non-code contributions.

Q: **How long have you been involved in the Kubeflow Community?  What projects have you been actively involved with?**

I have been involved heavily since early 2020. I have made significant contributions to Kubeflow Notebooks (current lead), Kubeflow Pipelines, the website/docs, and leading community efforts. I also contribute to the other components from time to time.

Q: **How long have you been involved in open-source?**  

My first open source contribution was to TensorFlow in Feburary 2017 (https://github.com/tensorflow/tensorflow/pull/7206), and I have been hooked ever since.

Q:  **Is there anything else you would like the community to know about you that you believe would help eligible voters make there decision?**

If elected, my intention is to be a neutral voice that represents the combined interests of users and contributors.

Q: **Links to any external sites (projects, hobbies, etc) that you would like to share that would help people make a decision about.**

I have been the long term maintainer of the Apache Airflow Helm Chart (https://github.com/airflow-helm/charts), and have recently released a similar project for Kubeflow called deployKF (https://www.deploykf.org/).

**Comment by jbottum** [comment]
Mathew stands as a distinguished multi-year contributor to the Kubeflow community, leaving a lasting impact through critical contributions. As a dedicated code contributor, Mathew’s expertise extends to comprehensive documentation efforts. Displaying leadership qualities, Mathew has taken on the role of working group lead for the Notebooks teams, showcasing a profound commitment to the success of Kubeflow. Mathew has shared valuable insights as a Kubeflow speaker at a variety of conferences and venues, contributing significantly to the dissemination of knowledge. Now based in the Bay Area, Mathew brings a crucial perspective to the collaborative and global efforts of the Kubeflow ecosystem. These qualifications make Mathew a great candidate for the Kubeflow Steering Committee.

**Comment by Talador12** [comment]
Mathew has been a consistent and active voice in the community. He pushes each project forward with new innovation and has a full understanding of the context of each project. He has gone above and beyond working on every project he has worked on. He listens to feedback and reason, and iterates to achieve the best outcome for the community. I recommend Mathew as a candidate for the Kubeflow Steering Committee.

**Comment by kimwnasptd** [comment]
Mathew is for sure one of the integral people throughout Kubeflow's history. He had always been a voice in the community that pushes for neutrality of Kubeflow, at making it generic and configurable so that it can be easily adopted and extended. 

This extends to all moving pieces of Kubeflow, across WGs and through the docs as well, where his technical expertise is shown.

He has been involved in the community meetings and hosting them for more than 2 years, which also proves that he has been really invested in the project.

**Comment by chensun** [comment]
> and have recently released a similar project for Kubeflow called deployKF (https://www.deploykf.org/).

I would like to assume it was for good intent to promote Kubeflow usage. But I found the language such as "migrating from Kubeflow to deployKF" and the comparison of "deployKF vs. Kubeflow" somewhat confusing and possibly misleading IMHO.
![image](https://github.com/kubeflow/community/assets/2043310/621a9970-0155-456e-9200-c601dae9b770)

Other than that, a possibly more serious issue that **deployKF's name itself and its use of Kubeflow logo with an altered color theme seems to be a trademark infringement unless there was communication and agreement with Google that I'm not aware of.** @thesuperzapper, please let me know if that's the case.

Specifically, from https://github.com/kubeflow/community/blob/master/KUBEFLOW_BRAND_GUIDELINES.pdf:
>
> Don't remove, distort or alter any element of the Kubeflow Trademarks without
permission:
> -  Do not shorten, abbreviate, or change the spelling of the Kubeflow name, for
example in mass communication, product names, social media profiles, domain
names or event names).
> - Do not change the color or design elements of the Kubeflow logo, or combine the
logo with any other text.

**Comment by akgraner** [comment]
Closing this issue.
