### ISSUE TITLE
Elections Phase for the 2023 Kubeflow Project Steering Committee Elections - Now Open

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#686]
The Elections phase for the Kubeflow Steering Committee Election (KSC) is now open as of 9:00am PT on 8 January 2024. 

Below is a list of the nominees listed in alphabetical order by first name.

Andrey Velichkevich - https://github.com/kubeflow/community/issues/674
Johnu George - https://github.com/kubeflow/community/issues/675
Julius von Kohout - https://github.com/kubeflow/community/issues/676
Kimonas Sotirchos - https://github.com/kubeflow/community/issues/677
Mathew Wicks - https://github.com/kubeflow/community/issues/678
Yuan (Terry) Tang - https://github.com/kubeflow/community/issues/679

The Elections Phase will be open for 3 weeks until 12:00pm PT on 29 January 2024.  [All eligible voters](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2023-KSC.md) will be sent voting keys starting today.  

Please note we are missing email address for some eligible voters.  I will list those in a comment on this issue with instructions for sending me your email address so I can send you your voting key.

**Comment by thesuperzapper** [comment]
@akgraner you may want to make those into @ tags, in a new comment so they get notified.

**Comment by akgraner** [comment]
> @akgraner you may want to make those into @ tags, in a new comment so they get notified.

Done - thanks!

**Comment by akgraner** [comment]
As of 9 January 2024, we still emails from the following people:

@chensun 
@gkcalat 
@zijianjoy 
@jlyaoyuli 
@alculquicondor 
@annajung
@droctothorpe 
@surajkota 
@TobiasGoerke
@lowang-bh 
@DomFleischmann 
@ryansteakley
@nagar-ajay 
@mimowo 
@JOCSTAA 
@AlexandreBrown 
@vikas-saxena02 
@HeGaoYuan 
@rd-pong 
@votti 
@sheevy 
@sen-sam 
@xhejtman 
@mChowdhury-91 

If your name is on this list please ping me, **akgraner**, on slack or email me at akgraner@gmail.com with your email address.

**Comment by akgraner** [comment]
If your GitHub ID is listed below we still need your email address so we can get your voter key to you.  Thanks! 

@chensun
@jlyaoyuli
@annajung
@lowang-bh
@mimowo
@JOCSTAA
@HeGaoYuan
@rd-pong
@sheevy
@sen-sam
@xhejtman
@mChowdhury-91

If your name is on this list please ping me, akgraner, on slack or email me at [akgraner@gmail.com](mailto:akgraner@gmail.com) with your email address.

**Comment by akgraner** [comment]
If your GitHub ID is listed below we still need your email address so we can get your voter key to you. Thanks!

@jlyaoyuli
@lowang-bh
@mimowo
@JOCSTAA
@HeGaoYuan
@rd-pong
@sen-sam
@xhejtman
@mChowdhury-91

If your name is on this list please ping me, akgraner, on slack or email me at [akgraner@gmail.com](mailto:akgraner@gmail.com) with your email address.

**Comment by akgraner** [comment]
If your GitHub ID is listed below we still need your email address so we can get your voter key to you. Thanks!

@JOCSTAA
@HeGaoYuan
@rd-pong
@sen-sam
@xhejtman
@mChowdhury-91

If your name is on this list please ping me, akgraner, on slack or email me at [akgraner@gmail.com](mailto:akgraner@gmail.com) with your email address.

**Comment by akgraner** [comment]
If your GitHub ID is listed below we still need your email address so we can get your voter key to you. Thanks!

@HeGaoYuan
@sen-sam - emailed for confirmation since the email was provided by someone other than this person. 
@mChowdhury-91

If your GitHub ID is listed below we still need your email address so we can get your voter key to you. Thanks!

**Comment by akgraner** [comment]
As of 26 January we still haven't heard from the following eligible voters.  Please note voting closes on Monday, 29 January 2024 at 12:00pm PT. 

If your GitHub ID is listed below we still need your email address so we can get your voter key to you. Thanks!

@HeGaoYuan
@sen-sam - emailed for confirmation since the email was provided by someone other than this person.
@mChowdhury-91

If your name is on this list please ping me, akgraner, on slack or email me at [akgraner@gmail.com](mailto:akgraner@gmail.com) with your email address.Thanks!

**Comment by akgraner** [comment]
Thanks everyone! The election phase has now ended.  The new Steering committee will be announced on 30 January 2024.
