### ISSUE TITLE
Kubeflow logo usage

### ISSUE THREAD

**Issue by jeremyeder** [kubeflow/community#710]
Hello, Red Hat would like to use the Kubeflow logo in a social media campaign next week.

We wanted to confirm whether there any concerns with this? 

@jbottum @terrytangyuan

**Comment by thesuperzapper** [comment]
@kubeflow/kubeflow-steering-committee technically has final say on this now.

But it is also possible that you might be allowed to use it without express consent, see the trademark guidelines on the website.

https://www.kubeflow.org/docs/about/community/#kubeflow-trademark

**Comment by terrytangyuan** [comment]
+1

**Comment by james-jwu** [comment]
I would ask for a preview of how Kubeflow trademark is going to be used, so that we can evaluate whether the usage is compliant with the trademark guideline.

**Comment by marianpierson** [comment]
![Kubeflow Community Quote_LI_TW](https://github.com/kubeflow/community/assets/163449001/5da5f109-ae61-46fe-9d32-cfef75b00c37)
![Kubeflow Community Quote_IG](https://github.com/kubeflow/community/assets/163449001/8254d343-7bf6-40c8-8747-db38e0269323)

I attached the files that show how the Kubeflow logo would be used. Please let me know if these are approved.

**Comment by james-jwu** [comment]
The usage of Kubflow logo is LGTM.

**Comment by jeremyeder** [comment]
Thanks folks! Closing.
