### ISSUE TITLE
[RELEASE] Assemble the 1.10 Release Team

### ISSUE THREAD

**Issue by rimolive** [kubeflow/community#740]
With Kubeflow 1.9 being released it is time to assemble the Kubeflow 1.10 Release Team!

I would like to say thank you for the opportunity to work on a release and I really enjoyed being part of a brilliant team. Right now I don't have any nominations for the next Release Manager to lead the 1.10 Kubeflow Release. I would like to introduce one more role in this next Release Team to prepare the next 1.11 Release Team: The Release Manager shadowing. As for now, I'd like to nominate @tarilabs for the Release Manager shadowing. @tarilabs as the Model Registry lead proved that he has all the leadership skills to handle the future Kubeflow releases, but it's important for him to work along with someone with more experience to prepare himself for future releases.

The release manager role hasn't been decided, and it's still open for anyone in the community.

With that, I would also like to encourage everyone to participate in the 1.10 Release Team! The Release Team welcomes both new and existing members of the Kubeflow community and is a great way to get started with the project.

You can learn more about the Kubeflow release process and the release team in the [release handbook](https://github.com/kubeflow/community/blob/master/releases/handbook.md).

To be part of the release team, please leave a comment with which working group you like to be assigned to. We look forward to your involvement!

cc @kubeflow/wg-automl-leads @kubeflow/wg-data-leads @kubeflow/wg-notebooks-leads @kubeflow/wg-pipeline-leads @kubeflow/wg-training-leads @kubeflow/wg-manifests-leads @kubeflow/kubeflow-steering-committee @StefanoFioravanzo

**Comment by tarilabs** [comment]
I volunteer as liaison for the Model Registry WG,
and I candidate/volunteer as 1 of the Release mgr shadows.

**Comment by juliusvonkohout** [comment]
I volunteer for platform.

**Comment by milosjava** [comment]
I volunteer for MR liaison if Mateo wants to focus only on release manager shadow position

**Comment by juliusvonkohout** [comment]
Since you asked @rimolive, I can be co-releasemanager with more or less the same effort that i spent in the 1.9 cycle.

**Comment by Tob-iee** [comment]
I would like to volunteer for docs as well

**Comment by SiverJohn** [comment]
I volunteer to fulfill any position where I can be of most use.

**Comment by juliusvonkohout** [comment]
> I would like to volunteer for docs as well

As many documentation writers and testers as we can get :-)

**Comment by tarekabouzeid** [comment]
I would like to volunteer for Platform WG liaison

**Comment by tombuuz** [comment]
I can contribute in documentation and testing.

**Comment by lizvladi-ds** [comment]
I would like to join as a release team member. My current position is MLOps at a company that has KubeFlow-based ML-platform.

**Comment by thesuperzapper** [comment]
Hey everyone, please remember you have to be an active [member of kubeflow](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) to be on the release team.

If you're not already a member, feel free to share what areas you're able to contribute (in terms of code), and we can connect you you with a working group in need.

For example, if you have experience with Go programming (or React JS), I have a big need in the Notebooks WG. We are currently working on Notebooks 2.0 (https://github.com/kubeflow/kubeflow/issues/7156).

**Comment by mcruzdev** [comment]
I'd like to contribute to the release team. If that's not possible, I'd be happy to help with GoLang and ReactJS @thesuperzapper

**Comment by thesuperzapper** [comment]
@mcruzdev Kubeflow 1.10 is still a while away, so there is time to get your org membership and join the release team!

Let's connect on the [CNCF Slack](https://www.kubeflow.org/docs/about/community/#kubeflow-slack-channels) (slack name: `Mathew Wicks`), and we can you find some critical tasks to help get Notebooks 2.0 shipped, which will absolutely count towards the [contribution requirements](https://www.kubeflow.org/docs/about/contributing/#joining-the-kubeflow-github-org) of membership.

For example we still need someone to pick up this issue (requires KubeBuilder/Golang experience):
- https://github.com/kubeflow/notebooks/issues/37

___PS:__ other people watching this thread with Go/React experience are encouraged to message me on Slack too._

**Comment by andreyvelich** [comment]
Thanks @Tob-iee @SiverJohn @tarekabouzeid @tombuuz @lizvladi-ds @mcruzdev for volunteering to be on the Kubeflow 1.10 release team!

In addition to the @thesuperzapper's comments, you can start contributing to Kubeflow ecosystem by looking into issues with `good-first-issue` label. 
Usually, those issues are relatively easy to solve and you can start your contributions for the Kubeflow projects.

For example:

- Training Operator [good first issues](https://github.com/kubeflow/training-operator/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
- Katib [good first issues](https://github.com/kubeflow/katib/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).
- Pipelines [good first issue](https://github.com/kubeflow/pipelines/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22).

Additionally, I would suggest you to join [the Kubeflow community calls and the Kubeflow release team](https://www.kubeflow.org/docs/about/community/#kubeflow-community-calendars) calls to show your interest being on the Kubeflow release team.

**Comment by saileshd1402** [comment]
I would like to join the release team. I can be the Training Operator and Katib WG liaison.

**Comment by rimolive** [comment]
@saileshd1402 @mcruzdev @lizvladi-ds @tombuuz @tarekabouzeid @SiverJohn @Tob-iee Please join the next Release Team meeting on September 9th. You can find details in https://www.kubeflow.org/docs/about/community/#kubeflow-community-calendars

**Comment by varodrig** [comment]
Hi, I'm interested in the  Release Manager role please let me know next steps. I'll be joining Monday's meeting.

**Comment by anencore94** [comment]
Hi, Unless I'm not late, I'd like to join as a training or notebooks or automl WG. @rimolive

**Comment by biswassri** [comment]
@rimolive I'm interested in joining too. Unfortunately I missed the meeting but any chance there is more position availabile?

**Comment by omarsumadi** [comment]
Hey folks. I'd be happy to take up the Release Product Manager role. cc @StefanoFioravanzo

**Comment by mvlassis** [comment]
Hello everyone! I'd like to participate as a liaison for the Notebooks WG, and as a point of contact for the Charmed Kubeflow distribution.

**Comment by omarsumadi** [comment]
Hey folks. I'd be happy to take up the Release Product Manager role. cc @StefanoFioravanzo. I'll attend the Release Team Meeting on Monday.

**Comment by rimolive** [comment]
Thank you for all the volunteers for the Kubeflow 1.10 Release Team. For now, we already formed the team but for everyone that didn't join for this release we'll keep working on new volunteers for upcoming releases.

Let me know (ping me on Slack) if you want to contribute to the project and work in the next Release teams.
