### ISSUE TITLE
[Kubeflow 1.10] Docs: create 1.10 roadmap

### ISSUE THREAD

**Issue by rimolive** [kubeflow/community#766]
Roadmap highlights:

* Model Registry UI
* Spark Operator as a core KF component
* Training Operator v2
* Notebooks 2.0
* Kubeflow Pipelines 2.4.0
* Switch from Istio to Istio-cni and enable Pod Security standards

**Comment by varodrig** [comment]
@diegolovison to link issues here.
cc @rimolive

**Comment by varodrig** [comment]
https://github.com/kubeflow/community/issues/763

**Comment by rimolive** [comment]
https://github.com/kubeflow/kubeflow/pull/7657
