### ISSUE TITLE
Elections - Nominations Phase - Reminder - Eligible Nominees for the KSC 2024 KSC Elections

### ISSUE THREAD

**Issue by akgraner** [kubeflow/community#794]
If you are listed below you are eligible to run for a seat on the KSC (Kubeflow Steering Committee) in the upcoming election.  We are currently in the Nominations Phase.  

If you would like to nominate yourself or someone on the list you can do so by following the instructions on the the following issue - [https://github.com/kubeflow/community/issues/791](https://github.com/kubeflow/community/issues/791) 

**DO NOT** use this issue to nominate anyone.  If you would like to nominate yourself or some you can do so [here](https://github.com/kubeflow/community/issues/791).

This issue is just to make all those [who are eligible to be nominated](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2024-ksc.md) aware that they have until **8 December 2024 at 12:00pm Pacific Time** to be nominated. 

Below is the list of those who are eligible to be nominated.

@tenzen-y
@juliusvonkohout
@thesuperzapper
@rimolive
@tarilabs
@hbelmiro
@chenyi015
@chensun
@ederign
@connor-mccarthy
@electronic-waste
@humairak
@tomcli
@dharmitd
@droctothorpe
@helenxie-bit
@franciscojavierarceo
@deepanker13
@diegolovison
@isinyaaa
@jacobsalway
@gregsheremeta
@stefanofioravanzo
@zijianjoy
@vara-bonthu
@griffin-sullivan
@rareddy
@kevingrantlee
@alexcreasy
@tariq-hasan
@yuchaoran2011
@alculquicondor
@hansinikarunarathne
@lucferbux
@kimwnasptd
@syulin7
@lampajr
@jbottum
@james-jwu
@kromanow94
@biswajit-9776
@mimowo
@vikas-saxena02
@anishasthana
@kuizhiqing
@gmfrasca
@jiridanek
@kannon92
@shashank-iitbhu
@dhirajsb
@andersbennedsgaard
@vsoch
@cheyang
@mszadkow
@al-pragliola
@impsy
@varodrig
@sandipanpanda
@elayaharoni
@peter-mcclonski
@akshaychitneni
@tzabbi

To nominate yourself or someone on the list above please use [The Nominations Phase for the 2024 Kubeflow Project Steering Committee Elections are now open issue](https://github.com/kubeflow/community/issues/791).

More information on the KSC Elections: [Timeline and Guidelines](https://github.com/kubeflow/community/blob/master/elections/kubeflow-steering-committee-elections-2024.md); [Eligible Voters and Nominees](https://github.com/kubeflow/community/blob/master/elections/eligible-candidates-and-voters-2024-ksc.md)

**Comment by andreyvelich** [comment]
Thanks for creating this @akgraner!
I added the rest of the folks since GitHub limits number of users you can ping in the single comment

@andersbennedsgaard
@vsoch
@cheyang
@mszadkow
@al-pragliola
@impsy
@varodrig
@sandipanpanda
@elayaharoni
@peter-mcclonski
@akshaychitneni
@tzabbi

**Comment by akgraner** [comment]
@andreyvelich  - the nominations phase is now closed and the testimonial phase issues will be opened later by 9am PT today.
