### ISSUE TITLE
WeChat communication group

### ISSUE THREAD

**Issue by yanghangcnc** [kubeflow/community#799]
Does kubeflow have an official WeChat official account or WeChat communication group？

**Comment by akgraner** [comment]
Not that I am aware of.  Do we need to see about setting one up?  Will slack not work for your communications needs with other community members?

**Comment by yanghangcnc** [comment]
I just joined Slack and I will explore it. Thank you.

**Comment by terrytangyuan** [comment]
We do have a group on WeChat for Chinese-speaking community only. Feel free to add my WeChat (same ID as my GitHub handle) and I'll add you there.
