### ISSUE TITLE
Do we have a interest in LF Deep Learning Foundation

### ISSUE THREAD

**Issue by DjangoPeng** [kubeflow/community#89]
As we all know, *Kubeflow is an open, community driven project to make it easy to deploy and manage an ML stack on Kubernetes.*

Actually, it's an organic combination of ML and Cloud-native community. Recently [the Linux Foundation launches a Deep Learning Foundation](https://techcrunch.com/2018/03/26/the-linux-foundation-launches-a-deep-learning-foundation/).

I think it's open to discuss do we have a plan or interest in LF DLF? 

WDYT @jlewi @gaocegege @ddysher

**Comment by gaocegege** [comment]
I think it is a good place for kubeflow, but I am not sure if the community wants to be a member of one foundation.

**Comment by ddysher** [comment]
I thought the original plan is to work with CNCF?

/cc @aronchick

**Comment by jlewi** [comment]
I don't think we've put much thought into the particular organization we should join. I think its TBD by the community.

**Comment by bhack** [comment]
In CNCF FAQ i read:
> The Linux Foundation is the parent of CNCF. We are one of the LF’s largest sub-foundations

So LF is also the parent of DLF.

As ML/DL and K8s project we could be the grandchildren of LF :wink:

**Comment by bhack** [comment]
https://www.linuxfoundation.org/blog/lf-deep-learning-foundation-announces-project-contribution-process/

**Comment by bhack** [comment]
Can we re-evaluate this? Now also ONNX joined in LF AI https://lfai.foundation/press-release/2019/11/14/lf-ai-welcomes-onnx/I 
/cc ibrahimhaddad

**Comment by ibrahimhaddad** [comment]
Hey Kubeflow Community, 

LF Deep Learning (LF DL) was rebranded to LF AI early 2019 to reflect the growing scope of our organization and the increasing number of technologies being built in our community. 

We would love to have Kubeflow become an LF AI Foundation Project. 

Here are some references:
1)  LF AI Projects: https://lfai.foundation/projects/   (we have 2 projects joining in Dec and 1 in Jan)
2) Project stages and lifecycle:  https://lfai.foundation/project-stages-and-lifecycle/
3) Project proposal process:  https://lfai.foundation/proposal-and-hosting-process/
4) Services offered to projects: https://lfai.foundation/services-for-projects/


I am very happy to meet with the community members (open Zoom call) to do a general short overview of how a project can join LF AI and to address any questions you may have.

Also, I'd like to share the LF AI landscape  (https://l.lfai.foundation) for your reference.

Thank you.
Ibrahim

**Comment by ibrahimhaddad** [comment]
@gaocegege 
> I think it is a good place for kubeflow, but I am not sure if the community wants to be a member of one foundation.

When a project move to a Foundation, the community members don't become corporate members of the Foundation. This is not a requirement. The project will benefit from being hosted in a neutral environment that will host its IP assets and make it available to the wider community. The Foundation will support the project with a large number of services ranging from legal, program management, marketing, events, PR, dedicated support staff, infrastructure support, collaboration/integration opportunities with other hosted projects, etc. The project retains its license and governance; there is no disruption to the developers, and there is a clear separation between the running of the Foundation and the project itself. 

I am available to detail more on the specifics and address any questions. 

@bhack mentioned earlier that ONNX joined LF AI. From an ONNX perspective, I think the ONNX community saw value in:
- A foundation that will not only give ONNX an independent home but also help boost its profile as a vendor-neutral standard. 
- We can provide major help marketing and community events. 
- We don't require a particular OSS license.
- You can keep your governance and long open and documented. 
- We host a growing set of complementary and well run relevant projects.
- We have proven to be a good host for diverse organizations.
- The project will retain its development practices. 
- Moving to the Foundation will not to cause disruption to developers.

**Comment by jimspohrer** [comment]
ONNX is now part of Linux Foundation Artificial Intelligence Foundation (LF AI) - see: https://dunia-it.com/lf-ai-welcomes-onnx-ecosystem-for-interoperable-ai-models-as-graduate-project/

Would be great for the community if Kubeflow IP could be in a foundation, a vendor-neutral hom.

**Comment by terrytangyuan** [comment]
+1 It would be great if we could join a foundation. Many Kubeflow developers are from companies with various cloud vendors so we could benefit a lot from moving towards vendor-neutral.

**Comment by ryan-nervana** [comment]
ONNX moving to LF AI was a great decision that made it possible for our teams at Intel to contribute under a vendor-neutral CLA. 

Currently, the CLA for KubeFlow requires any person or entity to have a Contributor License Agreement (CLA) on file that has been signed by each Contributor. The IP is owned by Google (see https://cla.developers.google.com/clas/new?domain=DOMAIN_GOOGLE&kind=KIND_CORPORATE) 

Moving KubeFlow under LF AI would presumably create a legal entity that is not controlled by a single corporation (Google). This would be likely be appealing to cloud providers and vendors who are not Google.

**Comment by wenjing** [comment]
+1 

Moving kubeflow to a foundation will broaden contributor base as @ryan-nervana noted, and a clear vendor neutral IP ownership can also encourage adoption by wider user base outside of Google and other primary contributors of today. Both would be healthy developments for kubeflow. ONNX community's recent move to LF AI is success and good example.

**Comment by yuzisun** [comment]
+1
Moving kubeflow to a foundation definitely can help grow the community and companies adopt Kubeflow,  with vendor neutral CLA it also helps scale up the contributors from various companies and vendors.

**Comment by bhack** [comment]
Is this need to be scheduled for a weekly meeting agenda?

**Comment by gaocegege** [comment]
+1 for that.

vendor neutral CLA means a lot for us.

**Comment by alka-roy** [comment]
+1
Would be great to see Kubeflow be a part of LF AI and expand the community.

**Comment by ddysher** [comment]
+1

kubeflow works like "an umbrella project" which has many projects with different maturity level, how do we evaluate a project like this?

can we loop in appropriate folks from Google and make a decision on community meeting?
> Is this need to be scheduled for a weekly meeting agenda?

**Comment by ibrahimhaddad** [comment]
@ddysher I am happy to join a call with community representatives (including Google) or even flying to a community event and presenting on the process of hosting a project, the benefits and how we've done it with other projects including ONNX. 

Thank you.

**Comment by bhack** [comment]
@jlewi @ewilderj what is the next step on this topic?

**Comment by ewilderj** [comment]
cc/ @theadactyl

**Comment by ibrahimhaddad** [comment]
@ewilderj @theadactyl @jlewi - I am available to have a chat with the Kubeflow team at Google on this topic. The ONNX community went through that process and hosted the project in LF AI. I can explain how the ONNX community managed their internal process as an example of a large project who's done that very recently. I would also address any questions/concerns you may have. You can reach me via ibrahim(at)linuxfoundation(dot)org. Thank you.

**Comment by theadactyl** [comment]
Thanks @ibrahimhaddad, @bhack and @gaocegege for your thoughts here. Right now our focus as a project is getting to 1.0 and getting Kubeflow's incubating working groups established with accepted charters and guidelines around global working group governance. After that, we'll be looking at the cross-project technical leadership, guidelines & processes we need to work together effectively. The Project Steering Group will be sharing more on next steps around these efforts and in working towards Kubeflow's accepted governance structure [1] in early 2020.   
[1] https://docs.google.com/document/d/14GjeNlFB_LIlzA0wZRE3u0KnCvtIPfKgJKpwEvpDDxk/edit

**Comment by bhack** [comment]
> Q: Do you have a plan to donate Kubeflow to a foundation in the near term?
While we haven’t ruled out donating Kubeflow to an open source foundation, we have decided to first focus on 1) iteratively building an open, transparent, and structured system of governance that works for the Kubeflow project's unique community and challenges, and 2) working with our community partners to quickly build a minimum viable product for production use in the enterprise and reach the level of technical stability, usability, documentation, etc. necessary to support those users. We see the option of joining a foundation to be one of many tactics we as a community can explore to ensure that the project reaches its development and adoption goals.

**Comment by hannibalhuang** [comment]
+1 For LFAI

**Comment by bhack** [comment]
I suppose that the problem here It Is not only strictly to the Kubeflow governance but It Is part of a more general Google strategy on (semi-multistakeholders) assets around Kubernetes et al.:
https://www.theregister.co.uk/2019/12/20/ibm_istio_knative_tensorflow_should_be_under_open_governance/

**Comment by animeshsingh** [comment]
This is yet not resolved - so reopening it. 
cc @theadactyl @jimspohrer @ewilderj @jbottum @yuzisun

**Comment by animeshsingh** [comment]
This is moving in next phase - below is the doc/presentation we used in the community for the new WG proposal: 
Kubeflow Governance and Foundation Working Group
https://docs.google.com/document/d/1U5VJ2U4N14G0knSTdyS3HmfTjPnmkgNkS2SLX8jCny8/edit?usp=sharing

For folks who are interested in this, either in  Kubeflow Governance WG or Kubeflow Application WGs for particular application, please reach out to me either through email, or through Slack

The doc will be open for comments/feedback/nomination until June 10th, and then we will move into formalizing this and putting the WG in practice.

**Comment by jlewi** [comment]
Repasting from the [mailing list thread](https://groups.google.com/forum/#!topic/kubeflow-discuss/v6iS6F_iZSI)

> Hi Folks;

> I didn't want to derail your discussions here, but I thought I'd let you all know that Google does not intend to change the existing governance structure or donate the trademark to a new entity at this time. As an open source project, anyone is free to fork Kubeflow and create their own independent governance structures around that fork. Keep us informed of your plans, and we'll see if there are future opportunities to collaborate. 

> Chris

Chris is referring to the governance model [here](bit.ly/kf-governance)

**Comment by bhack** [comment]
> Google does not intend to change the existing governance structure or donate the trademark to a new entity at this time.

@jlewi It be better to add this in the FAQ instead of what we have now:

>  We see the option of joining a foundation to be one of many tactics we as a community can explore to ensure that the project reaches its development and adoption goals.

**Comment by jlewi** [comment]
@bhack Any interest in opening up a PR about this?

**Comment by gaocegege** [comment]
Just FYI, mlflow is donated to Linux Foundation.

[The MLflow Project Joins Linux Foundation](https://www.linuxfoundation.org/press-release/2020/06/the-mlflow-project-joins-linux-foundation/)

**Comment by bhack** [comment]
https://opensource.googleblog.com/2022/10/kubeflow-applies-to-become-a-cncf-incubating-project.html
